import {
  ShortcutDefinition,
  ShortcutContext,
  ShortcutCategory,
  ShortcutModifier,
} from "./shortcuts/types";

export const GLOBAL_SHORTCUTS: ShortcutDefinition[] = [
  {
    id: "global?.command-palette",
    key: "k",
    modifiers: ["cmd"],
    description: "Open command palette",
    category: "global",
    context: "global",
    action: "openCommandPalette",
    allowInInput: true,
  },
  {
    id: "global?.shortcuts-help",
    key: "/",
    modifiers: ["cmd"],
    description: "Show keyboard shortcuts",
    category: "global",
    context: "global",
    action: "showShortcutsHelp",
  },
  {
    id: "global?.settings",
    key: ",",
    modifiers: ["cmd"],
    description: "Open settings",
    category: "navigation",
    context: "global",
    action: "openSettings",
  },
  {
    id: "global?.search",
    key: "f",
    modifiers: ["cmd"],
    description: "Global search",
    category: "global",
    context: "global",
    action: "openSearch",
  },
  {
    id: "global?.new-project",
    key: "n",
    modifiers: ["cmd"],
    description: "New project",
    category: "actions",
    context: "global",
    action: "newProject",
  },
  {
    id: "global?.escape",
    key: "Escape",
    description: "Close modal/dialog",
    category: "global",
    context: "global",
    action: "closeModal",
    allowInInput: true,
  },
];

export const NAVIGATION_SHORTCUTS: ShortcutDefinition[] = [
  {
    id: "nav?.dashboard",
    key: "h",
    modifiers: ["alt"],
    description: "Go to Dashboard",
    category: "navigation",
    context: "global",
    action: "navigateDashboard",
  },
  {
    id: "nav?.studio",
    key: "s",
    modifiers: ["alt"],
    description: "Go to Studio",
    category: "navigation",
    context: "global",
    action: "navigateStudio",
  },
  {
    id: "nav?.projects",
    key: "p",
    modifiers: ["alt"],
    description: "Go to Projects",
    category: "navigation",
    context: "global",
    action: "navigateProjects",
  },
  {
    id: "nav?.analytics",
    key: "a",
    modifiers: ["alt"],
    description: "Go to Analytics",
    category: "navigation",
    context: "global",
    action: "navigateAnalytics",
  },
  {
    id: "nav?.distribution",
    key: "d",
    modifiers: ["alt"],
    description: "Go to Distribution",
    category: "navigation",
    context: "global",
    action: "navigateDistribution",
  },
  {
    id: "nav?.marketplace",
    key: "m",
    modifiers: ["alt"],
    description: "Go to Marketplace",
    category: "navigation",
    context: "global",
    action: "navigateMarketplace",
  },
  {
    id: "nav?.royalties",
    key: "r",
    modifiers: ["alt"],
    description: "Go to Royalties",
    category: "navigation",
    context: "global",
    action: "navigateRoyalties",
  },
];

export const STUDIO_SHORTCUTS: ShortcutDefinition[] = [
  {
    id: "studio?.play-pause",
    key: " ",
    description: "Play/Pause",
    category: "transport",
    context: "studio",
    action: "togglePlayPause",
  },
  {
    id: "studio?.stop",
    key: "s",
    description: "Stop",
    category: "transport",
    context: "studio",
    action: "stop",
  },
  {
    id: "studio?.record",
    key: "r",
    description: "Toggle recording",
    category: "transport",
    context: "studio",
    action: "toggleRecord",
  },
  {
    id: "studio?.loop",
    key: "l",
    description: "Toggle loop",
    category: "transport",
    context: "studio",
    action: "toggleLoop",
  },
  {
    id: "studio?.metronome",
    key: "c",
    description: "Toggle metronome",
    category: "transport",
    context: "studio",
    action: "toggleMetronome",
  },
  {
    id: "studio?.save",
    key: "s",
    modifiers: ["cmd"],
    description: "Save project",
    category: "file",
    context: "studio",
    action: "saveProject",
  },
  {
    id: "studio?.undo",
    key: "z",
    modifiers: ["cmd"],
    description: "Undo",
    category: "editing",
    context: "studio",
    action: "undo",
  },
  {
    id: "studio?.redo",
    key: "z",
    modifiers: ["cmd", "shift"],
    description: "Redo",
    category: "editing",
    context: "studio",
    action: "redo",
  },
  {
    id: "studio?.cut",
    key: "x",
    modifiers: ["cmd"],
    description: "Cut",
    category: "editing",
    context: "studio",
    action: "cut",
  },
  {
    id: "studio?.copy",
    key: "c",
    modifiers: ["cmd"],
    description: "Copy",
    category: "editing",
    context: "studio",
    action: "copy",
  },
  {
    id: "studio?.paste",
    key: "v",
    modifiers: ["cmd"],
    description: "Paste",
    category: "editing",
    context: "studio",
    action: "paste",
  },
  {
    id: "studio?.delete",
    key: "Delete",
    description: "Delete selected",
    category: "editing",
    context: "studio",
    action: "deleteSelected",
  },
  {
    id: "studio?.duplicate",
    key: "d",
    modifiers: ["cmd"],
    description: "Duplicate",
    category: "editing",
    context: "studio",
    action: "duplicate",
  },
  {
    id: "studio?.split",
    key: "b",
    description: "Split at playhead",
    category: "editing",
    context: "studio",
    action: "splitClip",
  },
  {
    id: "studio?.quantize",
    key: "q",
    description: "Quantize",
    category: "editing",
    context: "studio",
    action: "quantize",
  },
  {
    id: "studio?.mute",
    key: "m",
    description: "Mute track",
    category: "track",
    context: "studio",
    action: "toggleMute",
  },
  {
    id: "studio?.solo",
    key: "o",
    description: "Solo track",
    category: "track",
    context: "studio",
    action: "toggleSolo",
  },
  {
    id: "studio?.add-track",
    key: "t",
    modifiers: ["cmd"],
    description: "Add track",
    category: "track",
    context: "studio",
    action: "addTrack",
  },
  {
    id: "studio?.zoom-in",
    key: "=",
    modifiers: ["cmd"],
    description: "Zoom in",
    category: "view",
    context: "studio",
    action: "zoomIn",
  },
  {
    id: "studio?.zoom-out",
    key: "-",
    modifiers: ["cmd"],
    description: "Zoom out",
    category: "view",
    context: "studio",
    action: "zoomOut",
  },
  {
    id: "studio?.zoom-fit",
    key: "0",
    modifiers: ["cmd"],
    description: "Zoom to fit",
    category: "view",
    context: "studio",
    action: "zoomToFit",
  },
  {
    id: "studio?.mixer",
    key: "x",
    modifiers: ["shift"],
    description: "Toggle mixer",
    category: "view",
    context: "studio",
    action: "toggleMixer",
  },
  {
    id: "studio?.browser",
    key: "b",
    modifiers: ["shift"],
    description: "Toggle browser",
    category: "view",
    context: "studio",
    action: "toggleBrowser",
  },
  {
    id: "studio?.export",
    key: "e",
    modifiers: ["cmd", "shift"],
    description: "Export project",
    category: "file",
    context: "studio",
    action: "exportProject",
  },
  {
    id: "studio?.home",
    key: "Home",
    description: "Go to start",
    category: "transport",
    context: "studio",
    action: "goToStart",
  },
  {
    id: "studio?.end",
    key: "End",
    description: "Go to end",
    category: "transport",
    context: "studio",
    action: "goToEnd",
  },
  {
    id: "studio?.skip-back",
    key: ",",
    description: "Skip back",
    category: "transport",
    context: "studio",
    action: "skipBack",
  },
  {
    id: "studio?.skip-forward",
    key: ".",
    description: "Skip forward",
    category: "transport",
    context: "studio",
    action: "skipForward",
  },
  {
    id: "studio?.snap-toggle",
    key: "n",
    description: "Toggle snap",
    category: "editing",
    context: "studio",
    action: "toggleSnap",
  },
  {
    id: "studio?.select-all",
    key: "a",
    modifiers: ["cmd"],
    description: "Select all",
    category: "editing",
    context: "studio",
    action: "selectAll",
  },
];

export const DASHBOARD_SHORTCUTS: ShortcutDefinition[] = [
  {
    id: "dashboard?.new-project",
    key: "n",
    description: "Create new project",
    category: "actions",
    context: "dashboard",
    action: "newProject",
  },
  {
    id: "dashboard?.upload",
    key: "u",
    description: "Upload file",
    category: "actions",
    context: "dashboard",
    action: "uploadFile",
  },
  {
    id: "dashboard?.refresh",
    key: "r",
    modifiers: ["cmd"],
    description: "Refresh data",
    category: "actions",
    context: "dashboard",
    action: "refreshData",
  },
  {
    id: "dashboard?.distribution",
    key: "d",
    description: "Go to distribution",
    category: "navigation",
    context: "dashboard",
    action: "goToDistribution",
  },
  {
    id: "dashboard?.notifications",
    key: "n",
    modifiers: ["shift"],
    description: "View notifications",
    category: "navigation",
    context: "dashboard",
    action: "viewNotifications",
  },
];

export const SOCIAL_SHORTCUTS: ShortcutDefinition[] = [
  {
    id: "social?.new-post",
    key: "n",
    description: "Create new post",
    category: "actions",
    context: "social",
    action: "newPost",
  },
  {
    id: "social?.schedule",
    key: "s",
    description: "Open scheduler",
    category: "actions",
    context: "social",
    action: "openScheduler",
  },
  {
    id: "social?.inbox",
    key: "i",
    description: "View inbox",
    category: "navigation",
    context: "social",
    action: "viewInbox",
  },
  {
    id: "social?.analytics",
    key: "a",
    description: "View analytics",
    category: "navigation",
    context: "social",
    action: "viewAnalytics",
  },
  {
    id: "social?.calendar",
    key: "c",
    description: "View calendar",
    category: "navigation",
    context: "social",
    action: "viewCalendar",
  },
];

export const MARKETPLACE_SHORTCUTS: ShortcutDefinition[] = [
  {
    id: "marketplace?.search",
    key: "f",
    modifiers: ["cmd"],
    description: "Search beats",
    category: "actions",
    context: "marketplace",
    action: "searchBeats",
  },
  {
    id: "marketplace?.upload",
    key: "u",
    description: "Upload beat",
    category: "actions",
    context: "marketplace",
    action: "uploadBeat",
  },
  {
    id: "marketplace?.favorites",
    key: "f",
    description: "View favorites",
    category: "navigation",
    context: "marketplace",
    action: "viewFavorites",
  },
  {
    id: "marketplace?.cart",
    key: "c",
    description: "View cart",
    category: "navigation",
    context: "marketplace",
    action: "viewCart",
  },
  {
    id: "marketplace?.filters",
    key: "t",
    description: "Toggle filters",
    category: "view",
    context: "marketplace",
    action: "toggleFilters",
  },
  {
    id: "marketplace?.play-pause",
    key: " ",
    description: "Play/Pause preview",
    category: "actions",
    context: "marketplace",
    action: "togglePreview",
  },
];

export const ANALYTICS_SHORTCUTS: ShortcutDefinition[] = [
  {
    id: "analytics?.date-range",
    key: "d",
    description: "Change date range",
    category: "actions",
    context: "analytics",
    action: "changeDateRange",
  },
  {
    id: "analytics?.export",
    key: "e",
    modifiers: ["cmd"],
    description: "Export report",
    category: "actions",
    context: "analytics",
    action: "exportReport",
  },
  {
    id: "analytics?.refresh",
    key: "r",
    modifiers: ["cmd"],
    description: "Refresh data",
    category: "actions",
    context: "analytics",
    action: "refreshData",
  },
  {
    id: "analytics?.compare",
    key: "c",
    description: "Compare periods",
    category: "view",
    context: "analytics",
    action: "comparePeriods",
  },
];

export const ALL_SHORTCUTS: ShortcutDefinition[] = [
  ...GLOBAL_SHORTCUTS,
  ...NAVIGATION_SHORTCUTS,
  ...STUDIO_SHORTCUTS,
  ...DASHBOARD_SHORTCUTS,
  ...SOCIAL_SHORTCUTS,
  ...MARKETPLACE_SHORTCUTS,
  ...ANALYTICS_SHORTCUTS,
];

export function getShortcutsByContext(
  context: ShortcutContext,
): ShortcutDefinition[] {
  return ALL_SHORTCUTS?.filter(
    (s) => s?.context === context || s?.context === "global",
  );
}

export function getShortcutsByCategory(
  category: ShortcutCategory,
): ShortcutDefinition[] {
  return ALL_SHORTCUTS?.filter((s) => s?.category === category);
}

export function getShortcutById(id: string): ShortcutDefinition | undefined {
  return ALL_SHORTCUTS?.find((s) => s?.id === id);
}

export interface ShortcutMapping {
  [action: string]: {
    key: string;
    modifiers?: ShortcutModifier[];
    description: string;
  };
}

export const SHORTCUT_MAPPINGS: ShortcutMapping = {
  "play-pause": { key: " ", description: "Play/Pause" },
  stop: { key: "s", description: "Stop" },
  record: { key: "r", description: "Record" },
  loop: { key: "l", description: "Toggle loop" },
  undo: { key: "z", modifiers: ["cmd"], description: "Undo" },
  redo: { key: "z", modifiers: ["cmd", "shift"], description: "Redo" },
  save: { key: "s", modifiers: ["cmd"], description: "Save" },
  new: { key: "n", modifiers: ["cmd"], description: "New" },
  search: { key: "f", modifiers: ["cmd"], description: "Search" },
  "command-palette": {
    key: "k",
    modifiers: ["cmd"],
    description: "Command Palette",
  },
  help: { key: "/", modifiers: ["cmd"], description: "Help/Shortcuts" },
  settings: { key: ",", modifiers: ["cmd"], description: "Settings" },
};

export default ALL_SHORTCUTS;
