export interface TemplateTrack {
  id: string;
  name: string;
  trackType: 'audio' | 'midi' | 'instrument' | 'video' | 'bus';
  color: string;
  volume: number;
  pan: number;
  mute: boolean;
  solo: boolean;
  armed: boolean;
  recordEnabled: boolean;
  inputMonitoring: boolean;
  height: number;
  collapsed: boolean;
  outputBus: string;
  groupId?: string;
  effects?: TemplateEffect[];
  instrument?: string;
}

export interface TemplateEffect {
  id: string;
  name: string;
  type: 'eq' | 'compressor' | 'reverb' | 'delay' | 'limiter' | 'gate' | 'deesser' | 'saturation' | 'chorus' | 'phaser' | 'flanger';
  bypass: boolean;
  preset?: string;
  parameters?: Record<string, number>;
}

export interface TemplateRouting {
  from: string;
  to: string;
  gain?: number;
}

export interface StudioTemplate {
  id: string;
  name: string;
  description: string;
  category: TemplateCategory;
  icon: string;
  color: string;
  tempo: number;
  timeSignature: string;
  duration: number;
  tracks: TemplateTrack[];
  routing: TemplateRouting[];
  useCases: string[];
  tags: string[];
  isBuiltIn: boolean;
  isCommunity: boolean;
  author?: string;
  downloads?: number;
  rating?: number;
  createdAt: Date;
  updatedAt: Date;
}

export type TemplateCategory = 
  | 'recording'
  | 'beat-making'
  | 'mixing'
  | 'mastering'
  | 'podcast'
  | 'film-scoring'
  | 'custom'
  | 'community';

export interface TemplateFilter {
  category?: TemplateCategory;
  search?: string;
  tags?: string[];
}

const TRACK_COLORS = {
  vocal: '#4ade80',
  drums: '#f87171',
  bass: '#60a5fa',
  synth: '#a78bfa',
  guitar: '#fbbf24',
  keys: '#fb923c',
  fx: '#14b8a6',
  bus: '#8b5cf6',
  master: '#ec4899',
  video: '#06b6d4',
  voice: '#34d399',
  sfx: '#f472b6',
  orchestra: '#facc15',
};

export const RECORDING_TEMPLATE: StudioTemplate = {
  id: 'recording-vocals-instruments',
  name: 'Recording Session',
  description: 'Perfect setup for recording vocals and live instruments with monitoring, headphone mixes, and pre-configured processing chains.',
  category: 'recording',
  icon: 'Mic',
  color: '#4ade80',
  tempo: 120,
  timeSignature: '4/4',
  duration: 300,
  tracks: [
    {
      id: 'lead-vocal',
      name: 'Lead Vocal',
      trackType: 'audio',
      color: TRACK_COLORS.vocal,
      volume: 0.75,
      pan: 0,
      mute: false,
      solo: false,
      armed: true,
      recordEnabled: true,
      inputMonitoring: true,
      height: 100,
      collapsed: false,
      outputBus: 'vocal-bus',
      effects: [
        { id: 'lv-gate', name: 'Noise Gate', type: 'gate', bypass: false, parameters: { threshold: -40, ratio: 10, attack: 0.1, release: 100 } },
        { id: 'lv-comp', name: 'Vocal Comp', type: 'compressor', bypass: false, preset: 'vocal-smooth', parameters: { threshold: -18, ratio: 4, attack: 10, release: 100 } },
        { id: 'lv-eq', name: 'Vocal EQ', type: 'eq', bypass: false, parameters: { lowCut: 80, highBoost: 10000, presence: 3 } },
        { id: 'lv-deesser', name: 'De-Esser', type: 'deesser', bypass: false, parameters: { frequency: 6000, threshold: -20 } },
      ],
    },
    {
      id: 'backing-vocal-1',
      name: 'Backing Vocal 1',
      trackType: 'audio',
      color: TRACK_COLORS.vocal,
      volume: 0.6,
      pan: -0.3,
      mute: false,
      solo: false,
      armed: false,
      recordEnabled: true,
      inputMonitoring: false,
      height: 80,
      collapsed: false,
      outputBus: 'vocal-bus',
      effects: [
        { id: 'bv1-comp', name: 'Vocal Comp', type: 'compressor', bypass: false, preset: 'vocal-tight' },
        { id: 'bv1-eq', name: 'Vocal EQ', type: 'eq', bypass: false },
      ],
    },
    {
      id: 'backing-vocal-2',
      name: 'Backing Vocal 2',
      trackType: 'audio',
      color: TRACK_COLORS.vocal,
      volume: 0.6,
      pan: 0.3,
      mute: false,
      solo: false,
      armed: false,
      recordEnabled: true,
      inputMonitoring: false,
      height: 80,
      collapsed: false,
      outputBus: 'vocal-bus',
      effects: [
        { id: 'bv2-comp', name: 'Vocal Comp', type: 'compressor', bypass: false, preset: 'vocal-tight' },
        { id: 'bv2-eq', name: 'Vocal EQ', type: 'eq', bypass: false },
      ],
    },
    {
      id: 'acoustic-guitar',
      name: 'Acoustic Guitar',
      trackType: 'audio',
      color: TRACK_COLORS.guitar,
      volume: 0.7,
      pan: -0.2,
      mute: false,
      solo: false,
      armed: false,
      recordEnabled: true,
      inputMonitoring: false,
      height: 80,
      collapsed: false,
      outputBus: 'instrument-bus',
      effects: [
        { id: 'ag-eq', name: 'Guitar EQ', type: 'eq', bypass: false, parameters: { lowCut: 100, midBoost: 2 } },
        { id: 'ag-comp', name: 'Light Comp', type: 'compressor', bypass: false, parameters: { threshold: -12, ratio: 2 } },
      ],
    },
    {
      id: 'electric-guitar',
      name: 'Electric Guitar',
      trackType: 'audio',
      color: TRACK_COLORS.guitar,
      volume: 0.7,
      pan: 0.2,
      mute: false,
      solo: false,
      armed: false,
      recordEnabled: true,
      inputMonitoring: false,
      height: 80,
      collapsed: false,
      outputBus: 'instrument-bus',
      effects: [
        { id: 'eg-eq', name: 'Guitar EQ', type: 'eq', bypass: false },
        { id: 'eg-saturation', name: 'Tube Warmth', type: 'saturation', bypass: false, parameters: { drive: 2, mix: 30 } },
      ],
    },
    {
      id: 'vocal-bus',
      name: 'Vocal Bus',
      trackType: 'bus',
      color: TRACK_COLORS.bus,
      volume: 0.8,
      pan: 0,
      mute: false,
      solo: false,
      armed: false,
      recordEnabled: false,
      inputMonitoring: false,
      height: 60,
      collapsed: true,
      outputBus: 'master',
      effects: [
        { id: 'vb-reverb', name: 'Plate Reverb', type: 'reverb', bypass: false, preset: 'vocal-plate', parameters: { mix: 15, decay: 1.5 } },
        { id: 'vb-delay', name: 'Slap Delay', type: 'delay', bypass: false, parameters: { time: 80, feedback: 20, mix: 10 } },
      ],
    },
    {
      id: 'instrument-bus',
      name: 'Instrument Bus',
      trackType: 'bus',
      color: TRACK_COLORS.bus,
      volume: 0.75,
      pan: 0,
      mute: false,
      solo: false,
      armed: false,
      recordEnabled: false,
      inputMonitoring: false,
      height: 60,
      collapsed: true,
      outputBus: 'master',
      effects: [
        { id: 'ib-reverb', name: 'Room Reverb', type: 'reverb', bypass: false, preset: 'room-medium' },
      ],
    },
  ],
  routing: [
    { from: 'lead-vocal', to: 'vocal-bus' },
    { from: 'backing-vocal-1', to: 'vocal-bus' },
    { from: 'backing-vocal-2', to: 'vocal-bus' },
    { from: 'acoustic-guitar', to: 'instrument-bus' },
    { from: 'electric-guitar', to: 'instrument-bus' },
    { from: 'vocal-bus', to: 'master' },
    { from: 'instrument-bus', to: 'master' },
  ],
  useCases: [
    'Singer-songwriter recording',
    'Vocal overdubs',
    'Live acoustic sessions',
    'Demo production',
  ],
  tags: ['vocals', 'recording', 'instruments', 'live', 'acoustic'],
  isBuiltIn: true,
  isCommunity: false,
  createdAt: new Date('2024-01-01'),
  updatedAt: new Date('2024-01-01'),
};

export const BEAT_MAKING_TEMPLATE: StudioTemplate = {
  id: 'beat-making',
  name: 'Beat Making',
  description: 'Full production setup for creating beats with drums, bass, synths, and sample tracks. Pre-configured with drum patterns and sidechain routing.',
  category: 'beat-making',
  icon: 'Drum',
  color: '#f87171',
  tempo: 140,
  timeSignature: '4/4',
  duration: 240,
  tracks: [
    {
      id: 'kick',
      name: 'Kick',
      trackType: 'instrument',
      color: TRACK_COLORS.drums,
      volume: 0.85,
      pan: 0,
      mute: false,
      solo: false,
      armed: false,
      recordEnabled: false,
      inputMonitoring: false,
      height: 80,
      collapsed: false,
      outputBus: 'drum-bus',
      instrument: 'drum-machine',
      effects: [
        { id: 'kick-eq', name: 'Kick EQ', type: 'eq', bypass: false, parameters: { lowBoost: 60, midCut: 400 } },
        { id: 'kick-comp', name: 'Punch Comp', type: 'compressor', bypass: false, parameters: { threshold: -10, ratio: 4, attack: 5 } },
      ],
    },
    {
      id: 'snare',
      name: 'Snare',
      trackType: 'instrument',
      color: TRACK_COLORS.drums,
      volume: 0.8,
      pan: 0,
      mute: false,
      solo: false,
      armed: false,
      recordEnabled: false,
      inputMonitoring: false,
      height: 80,
      collapsed: false,
      outputBus: 'drum-bus',
      instrument: 'drum-machine',
      effects: [
        { id: 'snare-eq', name: 'Snare EQ', type: 'eq', bypass: false, parameters: { midBoost: 200, highBoost: 8000 } },
        { id: 'snare-comp', name: 'Snare Comp', type: 'compressor', bypass: false, parameters: { threshold: -15, ratio: 3 } },
      ],
    },
    {
      id: 'hihat',
      name: 'Hi-Hats',
      trackType: 'instrument',
      color: TRACK_COLORS.drums,
      volume: 0.65,
      pan: 0.1,
      mute: false,
      solo: false,
      armed: false,
      recordEnabled: false,
      inputMonitoring: false,
      height: 80,
      collapsed: false,
      outputBus: 'drum-bus',
      instrument: 'drum-machine',
      effects: [
        { id: 'hh-eq', name: 'Hi-Hat EQ', type: 'eq', bypass: false, parameters: { lowCut: 300, highBoost: 12000 } },
      ],
    },
    {
      id: 'percs',
      name: 'Percussion',
      trackType: 'audio',
      color: TRACK_COLORS.drums,
      volume: 0.6,
      pan: -0.2,
      mute: false,
      solo: false,
      armed: false,
      recordEnabled: false,
      inputMonitoring: false,
      height: 60,
      collapsed: false,
      outputBus: 'drum-bus',
    },
    {
      id: '808-bass',
      name: '808 Bass',
      trackType: 'instrument',
      color: TRACK_COLORS.bass,
      volume: 0.9,
      pan: 0,
      mute: false,
      solo: false,
      armed: false,
      recordEnabled: false,
      inputMonitoring: false,
      height: 80,
      collapsed: false,
      outputBus: 'bass-bus',
      instrument: '808-synth',
      effects: [
        { id: '808-saturation', name: '808 Saturation', type: 'saturation', bypass: false, parameters: { drive: 3, mix: 40 } },
        { id: '808-eq', name: '808 EQ', type: 'eq', bypass: false, parameters: { subBoost: 50, lowCut: 30 } },
      ],
    },
    {
      id: 'synth-lead',
      name: 'Synth Lead',
      trackType: 'instrument',
      color: TRACK_COLORS.synth,
      volume: 0.7,
      pan: 0,
      mute: false,
      solo: false,
      armed: false,
      recordEnabled: false,
      inputMonitoring: false,
      height: 80,
      collapsed: false,
      outputBus: 'synth-bus',
      instrument: 'wavetable-synth',
      effects: [
        { id: 'lead-delay', name: 'Stereo Delay', type: 'delay', bypass: false, parameters: { time: 250, feedback: 30, mix: 25 } },
        { id: 'lead-reverb', name: 'Hall Reverb', type: 'reverb', bypass: false, parameters: { mix: 20, decay: 2 } },
      ],
    },
    {
      id: 'synth-pad',
      name: 'Synth Pad',
      trackType: 'instrument',
      color: TRACK_COLORS.synth,
      volume: 0.55,
      pan: 0,
      mute: false,
      solo: false,
      armed: false,
      recordEnabled: false,
      inputMonitoring: false,
      height: 80,
      collapsed: false,
      outputBus: 'synth-bus',
      instrument: 'analog-pad',
      effects: [
        { id: 'pad-chorus', name: 'Wide Chorus', type: 'chorus', bypass: false, parameters: { rate: 0.5, depth: 50, mix: 40 } },
        { id: 'pad-reverb', name: 'Lush Reverb', type: 'reverb', bypass: false, parameters: { mix: 35, decay: 4 } },
      ],
    },
    {
      id: 'samples',
      name: 'Samples',
      trackType: 'audio',
      color: TRACK_COLORS.fx,
      volume: 0.65,
      pan: 0,
      mute: false,
      solo: false,
      armed: false,
      recordEnabled: false,
      inputMonitoring: false,
      height: 80,
      collapsed: false,
      outputBus: 'master',
    },
    {
      id: 'drum-bus',
      name: 'Drum Bus',
      trackType: 'bus',
      color: TRACK_COLORS.bus,
      volume: 0.85,
      pan: 0,
      mute: false,
      solo: false,
      armed: false,
      recordEnabled: false,
      inputMonitoring: false,
      height: 60,
      collapsed: true,
      outputBus: 'master',
      effects: [
        { id: 'db-comp', name: 'Glue Comp', type: 'compressor', bypass: false, preset: 'drum-glue', parameters: { threshold: -8, ratio: 4, attack: 10, release: 100 } },
        { id: 'db-saturation', name: 'Tape Saturation', type: 'saturation', bypass: false, parameters: { drive: 2, mix: 20 } },
      ],
    },
    {
      id: 'bass-bus',
      name: 'Bass Bus',
      trackType: 'bus',
      color: TRACK_COLORS.bus,
      volume: 0.9,
      pan: 0,
      mute: false,
      solo: false,
      armed: false,
      recordEnabled: false,
      inputMonitoring: false,
      height: 60,
      collapsed: true,
      outputBus: 'master',
      effects: [
        { id: 'bb-limiter', name: 'Bass Limiter', type: 'limiter', bypass: false, parameters: { ceiling: -1, release: 50 } },
      ],
    },
    {
      id: 'synth-bus',
      name: 'Synth Bus',
      trackType: 'bus',
      color: TRACK_COLORS.bus,
      volume: 0.7,
      pan: 0,
      mute: false,
      solo: false,
      armed: false,
      recordEnabled: false,
      inputMonitoring: false,
      height: 60,
      collapsed: true,
      outputBus: 'master',
      effects: [
        { id: 'sb-comp', name: 'Sidechain Comp', type: 'compressor', bypass: false, preset: 'sidechain-pump' },
      ],
    },
  ],
  routing: [
    { from: 'kick', to: 'drum-bus' },
    { from: 'snare', to: 'drum-bus' },
    { from: 'hihat', to: 'drum-bus' },
    { from: 'percs', to: 'drum-bus' },
    { from: '808-bass', to: 'bass-bus' },
    { from: 'synth-lead', to: 'synth-bus' },
    { from: 'synth-pad', to: 'synth-bus' },
    { from: 'drum-bus', to: 'master' },
    { from: 'bass-bus', to: 'master' },
    { from: 'synth-bus', to: 'master' },
    { from: 'kick', to: 'synth-bus', gain: -12 },
  ],
  useCases: [
    'Hip-hop production',
    'Trap beats',
    'Electronic music',
    'Lo-fi beats',
  ],
  tags: ['drums', 'bass', '808', 'synth', 'beat', 'hip-hop', 'trap'],
  isBuiltIn: true,
  isCommunity: false,
  createdAt: new Date('2024-01-01'),
  updatedAt: new Date('2024-01-01'),
};

export const MIXING_STEMS_TEMPLATE: StudioTemplate = {
  id: 'mixing-stems',
  name: 'Mixing Stems',
  description: 'Professional stem mixing workflow with organized bus routing, reference track, and color-coded track groups ready for import.',
  category: 'mixing',
  icon: 'Sliders',
  color: '#60a5fa',
  tempo: 120,
  timeSignature: '4/4',
  duration: 300,
  tracks: [
    {
      id: 'reference',
      name: 'Reference Track',
      trackType: 'audio',
      color: '#94a3b8',
      volume: 0.7,
      pan: 0,
      mute: true,
      solo: false,
      armed: false,
      recordEnabled: false,
      inputMonitoring: false,
      height: 60,
      collapsed: true,
      outputBus: 'master',
    },
    {
      id: 'vocals-stem',
      name: 'Vocals Stem',
      trackType: 'audio',
      color: TRACK_COLORS.vocal,
      volume: 0.75,
      pan: 0,
      mute: false,
      solo: false,
      armed: false,
      recordEnabled: false,
      inputMonitoring: false,
      height: 80,
      collapsed: false,
      outputBus: 'vocal-bus',
    },
    {
      id: 'drums-stem',
      name: 'Drums Stem',
      trackType: 'audio',
      color: TRACK_COLORS.drums,
      volume: 0.8,
      pan: 0,
      mute: false,
      solo: false,
      armed: false,
      recordEnabled: false,
      inputMonitoring: false,
      height: 80,
      collapsed: false,
      outputBus: 'drum-bus',
    },
    {
      id: 'bass-stem',
      name: 'Bass Stem',
      trackType: 'audio',
      color: TRACK_COLORS.bass,
      volume: 0.85,
      pan: 0,
      mute: false,
      solo: false,
      armed: false,
      recordEnabled: false,
      inputMonitoring: false,
      height: 80,
      collapsed: false,
      outputBus: 'bass-bus',
    },
    {
      id: 'music-stem',
      name: 'Music/Melody Stem',
      trackType: 'audio',
      color: TRACK_COLORS.synth,
      volume: 0.7,
      pan: 0,
      mute: false,
      solo: false,
      armed: false,
      recordEnabled: false,
      inputMonitoring: false,
      height: 80,
      collapsed: false,
      outputBus: 'music-bus',
    },
    {
      id: 'fx-stem',
      name: 'FX/Atmosphere Stem',
      trackType: 'audio',
      color: TRACK_COLORS.fx,
      volume: 0.6,
      pan: 0,
      mute: false,
      solo: false,
      armed: false,
      recordEnabled: false,
      inputMonitoring: false,
      height: 80,
      collapsed: false,
      outputBus: 'fx-bus',
    },
    {
      id: 'vocal-bus',
      name: 'Vocal Bus',
      trackType: 'bus',
      color: TRACK_COLORS.bus,
      volume: 0.8,
      pan: 0,
      mute: false,
      solo: false,
      armed: false,
      recordEnabled: false,
      inputMonitoring: false,
      height: 60,
      collapsed: false,
      outputBus: 'master',
      effects: [
        { id: 'vb-eq', name: 'Bus EQ', type: 'eq', bypass: false },
        { id: 'vb-comp', name: 'Bus Comp', type: 'compressor', bypass: false, preset: 'gentle-glue' },
        { id: 'vb-reverb', name: 'Reverb Send', type: 'reverb', bypass: false, parameters: { mix: 12 } },
      ],
    },
    {
      id: 'drum-bus',
      name: 'Drum Bus',
      trackType: 'bus',
      color: TRACK_COLORS.bus,
      volume: 0.85,
      pan: 0,
      mute: false,
      solo: false,
      armed: false,
      recordEnabled: false,
      inputMonitoring: false,
      height: 60,
      collapsed: false,
      outputBus: 'master',
      effects: [
        { id: 'db-eq', name: 'Bus EQ', type: 'eq', bypass: false },
        { id: 'db-comp', name: 'Parallel Comp', type: 'compressor', bypass: false, preset: 'drum-smash' },
        { id: 'db-saturation', name: 'Analog Heat', type: 'saturation', bypass: false, parameters: { drive: 1.5 } },
      ],
    },
    {
      id: 'bass-bus',
      name: 'Bass Bus',
      trackType: 'bus',
      color: TRACK_COLORS.bus,
      volume: 0.9,
      pan: 0,
      mute: false,
      solo: false,
      armed: false,
      recordEnabled: false,
      inputMonitoring: false,
      height: 60,
      collapsed: false,
      outputBus: 'master',
      effects: [
        { id: 'bb-eq', name: 'Low End EQ', type: 'eq', bypass: false },
        { id: 'bb-comp', name: 'Bass Comp', type: 'compressor', bypass: false },
      ],
    },
    {
      id: 'music-bus',
      name: 'Music Bus',
      trackType: 'bus',
      color: TRACK_COLORS.bus,
      volume: 0.75,
      pan: 0,
      mute: false,
      solo: false,
      armed: false,
      recordEnabled: false,
      inputMonitoring: false,
      height: 60,
      collapsed: false,
      outputBus: 'master',
      effects: [
        { id: 'mb-eq', name: 'Bus EQ', type: 'eq', bypass: false },
        { id: 'mb-comp', name: 'Glue Comp', type: 'compressor', bypass: false },
      ],
    },
    {
      id: 'fx-bus',
      name: 'FX Bus',
      trackType: 'bus',
      color: TRACK_COLORS.bus,
      volume: 0.6,
      pan: 0,
      mute: false,
      solo: false,
      armed: false,
      recordEnabled: false,
      inputMonitoring: false,
      height: 60,
      collapsed: false,
      outputBus: 'master',
      effects: [
        { id: 'fb-reverb', name: 'Ambient Reverb', type: 'reverb', bypass: false, parameters: { mix: 50, decay: 3 } },
        { id: 'fb-delay', name: 'Ping Pong Delay', type: 'delay', bypass: false, parameters: { time: 375, feedback: 40 } },
      ],
    },
  ],
  routing: [
    { from: 'vocals-stem', to: 'vocal-bus' },
    { from: 'drums-stem', to: 'drum-bus' },
    { from: 'bass-stem', to: 'bass-bus' },
    { from: 'music-stem', to: 'music-bus' },
    { from: 'fx-stem', to: 'fx-bus' },
    { from: 'vocal-bus', to: 'master' },
    { from: 'drum-bus', to: 'master' },
    { from: 'bass-bus', to: 'master' },
    { from: 'music-bus', to: 'master' },
    { from: 'fx-bus', to: 'master' },
  ],
  useCases: [
    'Stem mixing',
    'Client mixes',
    'Remix projects',
    'Mix revisions',
  ],
  tags: ['mixing', 'stems', 'professional', 'bus-routing', 'reference'],
  isBuiltIn: true,
  isCommunity: false,
  createdAt: new Date('2024-01-01'),
  updatedAt: new Date('2024-01-01'),
};

export const MASTERING_TEMPLATE: StudioTemplate = {
  id: 'mastering',
  name: 'Mastering',
  description: 'Professional mastering chain with metering, loudness analysis, and optimized signal flow for stereo master processing.',
  category: 'mastering',
  icon: 'Gauge',
  color: '#ec4899',
  tempo: 120,
  timeSignature: '4/4',
  duration: 300,
  tracks: [
    {
      id: 'reference-1',
      name: 'Reference A',
      trackType: 'audio',
      color: '#94a3b8',
      volume: 0.7,
      pan: 0,
      mute: true,
      solo: false,
      armed: false,
      recordEnabled: false,
      inputMonitoring: false,
      height: 60,
      collapsed: true,
      outputBus: 'monitor',
    },
    {
      id: 'reference-2',
      name: 'Reference B',
      trackType: 'audio',
      color: '#94a3b8',
      volume: 0.7,
      pan: 0,
      mute: true,
      solo: false,
      armed: false,
      recordEnabled: false,
      inputMonitoring: false,
      height: 60,
      collapsed: true,
      outputBus: 'monitor',
    },
    {
      id: 'stereo-master',
      name: 'Stereo Master',
      trackType: 'audio',
      color: TRACK_COLORS.master,
      volume: 1.0,
      pan: 0,
      mute: false,
      solo: false,
      armed: false,
      recordEnabled: false,
      inputMonitoring: false,
      height: 120,
      collapsed: false,
      outputBus: 'master-chain',
      effects: [],
    },
    {
      id: 'master-chain',
      name: 'Master Chain',
      trackType: 'bus',
      color: TRACK_COLORS.master,
      volume: 1.0,
      pan: 0,
      mute: false,
      solo: false,
      armed: false,
      recordEnabled: false,
      inputMonitoring: false,
      height: 100,
      collapsed: false,
      outputBus: 'master',
      effects: [
        { id: 'mc-eq', name: 'Linear Phase EQ', type: 'eq', bypass: false, preset: 'mastering-surgical' },
        { id: 'mc-comp', name: 'Mastering Comp', type: 'compressor', bypass: false, preset: 'mastering-glue', parameters: { threshold: -12, ratio: 1.5, attack: 30, release: 200 } },
        { id: 'mc-saturation', name: 'Analog Warmth', type: 'saturation', bypass: false, parameters: { drive: 0.5, mix: 15 } },
        { id: 'mc-limiter', name: 'Brickwall Limiter', type: 'limiter', bypass: false, parameters: { ceiling: -0.3, release: 100 } },
      ],
    },
    {
      id: 'monitor',
      name: 'Monitor Bus',
      trackType: 'bus',
      color: '#6b7280',
      volume: 0.7,
      pan: 0,
      mute: false,
      solo: false,
      armed: false,
      recordEnabled: false,
      inputMonitoring: false,
      height: 60,
      collapsed: true,
      outputBus: 'master',
    },
  ],
  routing: [
    { from: 'stereo-master', to: 'master-chain' },
    { from: 'master-chain', to: 'master' },
    { from: 'reference-1', to: 'monitor' },
    { from: 'reference-2', to: 'monitor' },
    { from: 'monitor', to: 'master' },
  ],
  useCases: [
    'Stereo mastering',
    'Album mastering',
    'Single releases',
    'Loudness optimization',
  ],
  tags: ['mastering', 'loudness', 'limiter', 'professional', 'stereo'],
  isBuiltIn: true,
  isCommunity: false,
  createdAt: new Date('2024-01-01'),
  updatedAt: new Date('2024-01-01'),
};

export const PODCAST_TEMPLATE: StudioTemplate = {
  id: 'podcast',
  name: 'Podcast Production',
  description: 'Complete podcast setup with host and guest tracks, voice processing, intro/outro beds, and export presets for various platforms.',
  category: 'podcast',
  icon: 'Podcast',
  color: '#34d399',
  tempo: 120,
  timeSignature: '4/4',
  duration: 3600,
  tracks: [
    {
      id: 'host',
      name: 'Host',
      trackType: 'audio',
      color: TRACK_COLORS.voice,
      volume: 0.85,
      pan: -0.15,
      mute: false,
      solo: false,
      armed: true,
      recordEnabled: true,
      inputMonitoring: true,
      height: 100,
      collapsed: false,
      outputBus: 'dialogue-bus',
      effects: [
        { id: 'host-gate', name: 'Noise Gate', type: 'gate', bypass: false, parameters: { threshold: -45, ratio: 10, attack: 0.5, release: 50 } },
        { id: 'host-eq', name: 'Voice EQ', type: 'eq', bypass: false, preset: 'podcast-voice', parameters: { lowCut: 80, presence: 4 } },
        { id: 'host-comp', name: 'Voice Leveler', type: 'compressor', bypass: false, preset: 'podcast-level', parameters: { threshold: -20, ratio: 4, attack: 5, release: 100 } },
        { id: 'host-deesser', name: 'De-Esser', type: 'deesser', bypass: false, parameters: { frequency: 5500, threshold: -25 } },
      ],
    },
    {
      id: 'guest-1',
      name: 'Guest 1',
      trackType: 'audio',
      color: TRACK_COLORS.voice,
      volume: 0.85,
      pan: 0.15,
      mute: false,
      solo: false,
      armed: false,
      recordEnabled: true,
      inputMonitoring: false,
      height: 100,
      collapsed: false,
      outputBus: 'dialogue-bus',
      effects: [
        { id: 'g1-gate', name: 'Noise Gate', type: 'gate', bypass: false, parameters: { threshold: -45 } },
        { id: 'g1-eq', name: 'Voice EQ', type: 'eq', bypass: false, preset: 'podcast-voice' },
        { id: 'g1-comp', name: 'Voice Leveler', type: 'compressor', bypass: false, preset: 'podcast-level' },
        { id: 'g1-deesser', name: 'De-Esser', type: 'deesser', bypass: false },
      ],
    },
    {
      id: 'guest-2',
      name: 'Guest 2',
      trackType: 'audio',
      color: TRACK_COLORS.voice,
      volume: 0.85,
      pan: 0,
      mute: true,
      solo: false,
      armed: false,
      recordEnabled: true,
      inputMonitoring: false,
      height: 80,
      collapsed: true,
      outputBus: 'dialogue-bus',
      effects: [
        { id: 'g2-gate', name: 'Noise Gate', type: 'gate', bypass: false },
        { id: 'g2-eq', name: 'Voice EQ', type: 'eq', bypass: false, preset: 'podcast-voice' },
        { id: 'g2-comp', name: 'Voice Leveler', type: 'compressor', bypass: false, preset: 'podcast-level' },
      ],
    },
    {
      id: 'intro-music',
      name: 'Intro/Outro',
      trackType: 'audio',
      color: TRACK_COLORS.synth,
      volume: 0.5,
      pan: 0,
      mute: false,
      solo: false,
      armed: false,
      recordEnabled: false,
      inputMonitoring: false,
      height: 60,
      collapsed: false,
      outputBus: 'music-bus',
    },
    {
      id: 'bed-music',
      name: 'Background Music',
      trackType: 'audio',
      color: TRACK_COLORS.synth,
      volume: 0.25,
      pan: 0,
      mute: false,
      solo: false,
      armed: false,
      recordEnabled: false,
      inputMonitoring: false,
      height: 60,
      collapsed: false,
      outputBus: 'music-bus',
    },
    {
      id: 'sfx',
      name: 'Sound Effects',
      trackType: 'audio',
      color: TRACK_COLORS.sfx,
      volume: 0.6,
      pan: 0,
      mute: false,
      solo: false,
      armed: false,
      recordEnabled: false,
      inputMonitoring: false,
      height: 60,
      collapsed: false,
      outputBus: 'master',
    },
    {
      id: 'dialogue-bus',
      name: 'Dialogue Bus',
      trackType: 'bus',
      color: TRACK_COLORS.bus,
      volume: 0.9,
      pan: 0,
      mute: false,
      solo: false,
      armed: false,
      recordEnabled: false,
      inputMonitoring: false,
      height: 60,
      collapsed: false,
      outputBus: 'master',
      effects: [
        { id: 'db-comp', name: 'Bus Leveler', type: 'compressor', bypass: false, preset: 'broadcast-leveler' },
        { id: 'db-limiter', name: 'Safety Limiter', type: 'limiter', bypass: false, parameters: { ceiling: -1 } },
      ],
    },
    {
      id: 'music-bus',
      name: 'Music Bus',
      trackType: 'bus',
      color: TRACK_COLORS.bus,
      volume: 0.4,
      pan: 0,
      mute: false,
      solo: false,
      armed: false,
      recordEnabled: false,
      inputMonitoring: false,
      height: 60,
      collapsed: false,
      outputBus: 'master',
      effects: [
        { id: 'mb-comp', name: 'Ducker', type: 'compressor', bypass: false, preset: 'sidechain-duck' },
      ],
    },
  ],
  routing: [
    { from: 'host', to: 'dialogue-bus' },
    { from: 'guest-1', to: 'dialogue-bus' },
    { from: 'guest-2', to: 'dialogue-bus' },
    { from: 'intro-music', to: 'music-bus' },
    { from: 'bed-music', to: 'music-bus' },
    { from: 'dialogue-bus', to: 'master' },
    { from: 'music-bus', to: 'master' },
    { from: 'host', to: 'music-bus', gain: -18 },
  ],
  useCases: [
    'Podcast recording',
    'Interview shows',
    'Audio blogs',
    'Voice-over work',
  ],
  tags: ['podcast', 'voice', 'interview', 'broadcast', 'audio-blog'],
  isBuiltIn: true,
  isCommunity: false,
  createdAt: new Date('2024-01-01'),
  updatedAt: new Date('2024-01-01'),
};

export const FILM_SCORING_TEMPLATE: StudioTemplate = {
  id: 'film-scoring',
  name: 'Film Scoring',
  description: 'Orchestral template with video track, marker cues, and pre-configured instrument sections for film and media composition.',
  category: 'film-scoring',
  icon: 'Film',
  color: '#facc15',
  tempo: 85,
  timeSignature: '4/4',
  duration: 600,
  tracks: [
    {
      id: 'video',
      name: 'Video',
      trackType: 'video',
      color: TRACK_COLORS.video,
      volume: 0,
      pan: 0,
      mute: false,
      solo: false,
      armed: false,
      recordEnabled: false,
      inputMonitoring: false,
      height: 150,
      collapsed: false,
      outputBus: 'master',
    },
    {
      id: 'click',
      name: 'Click Track',
      trackType: 'audio',
      color: '#9ca3af',
      volume: 0.5,
      pan: 0,
      mute: true,
      solo: false,
      armed: false,
      recordEnabled: false,
      inputMonitoring: false,
      height: 40,
      collapsed: true,
      outputBus: 'headphones',
    },
    {
      id: 'violins-1',
      name: 'Violins I',
      trackType: 'instrument',
      color: TRACK_COLORS.orchestra,
      volume: 0.75,
      pan: -0.3,
      mute: false,
      solo: false,
      armed: false,
      recordEnabled: false,
      inputMonitoring: false,
      height: 80,
      collapsed: false,
      outputBus: 'strings-bus',
      instrument: 'orchestral-strings',
    },
    {
      id: 'violins-2',
      name: 'Violins II',
      trackType: 'instrument',
      color: TRACK_COLORS.orchestra,
      volume: 0.7,
      pan: -0.15,
      mute: false,
      solo: false,
      armed: false,
      recordEnabled: false,
      inputMonitoring: false,
      height: 80,
      collapsed: false,
      outputBus: 'strings-bus',
      instrument: 'orchestral-strings',
    },
    {
      id: 'violas',
      name: 'Violas',
      trackType: 'instrument',
      color: TRACK_COLORS.orchestra,
      volume: 0.7,
      pan: 0,
      mute: false,
      solo: false,
      armed: false,
      recordEnabled: false,
      inputMonitoring: false,
      height: 80,
      collapsed: false,
      outputBus: 'strings-bus',
      instrument: 'orchestral-strings',
    },
    {
      id: 'cellos',
      name: 'Cellos',
      trackType: 'instrument',
      color: TRACK_COLORS.orchestra,
      volume: 0.75,
      pan: 0.15,
      mute: false,
      solo: false,
      armed: false,
      recordEnabled: false,
      inputMonitoring: false,
      height: 80,
      collapsed: false,
      outputBus: 'strings-bus',
      instrument: 'orchestral-strings',
    },
    {
      id: 'basses',
      name: 'Double Basses',
      trackType: 'instrument',
      color: TRACK_COLORS.orchestra,
      volume: 0.8,
      pan: 0.3,
      mute: false,
      solo: false,
      armed: false,
      recordEnabled: false,
      inputMonitoring: false,
      height: 80,
      collapsed: false,
      outputBus: 'strings-bus',
      instrument: 'orchestral-strings',
    },
    {
      id: 'french-horns',
      name: 'French Horns',
      trackType: 'instrument',
      color: '#b45309',
      volume: 0.7,
      pan: -0.2,
      mute: false,
      solo: false,
      armed: false,
      recordEnabled: false,
      inputMonitoring: false,
      height: 80,
      collapsed: false,
      outputBus: 'brass-bus',
      instrument: 'orchestral-brass',
    },
    {
      id: 'trumpets',
      name: 'Trumpets',
      trackType: 'instrument',
      color: '#b45309',
      volume: 0.65,
      pan: 0.2,
      mute: false,
      solo: false,
      armed: false,
      recordEnabled: false,
      inputMonitoring: false,
      height: 80,
      collapsed: false,
      outputBus: 'brass-bus',
      instrument: 'orchestral-brass',
    },
    {
      id: 'trombones',
      name: 'Trombones',
      trackType: 'instrument',
      color: '#b45309',
      volume: 0.7,
      pan: 0.3,
      mute: false,
      solo: false,
      armed: false,
      recordEnabled: false,
      inputMonitoring: false,
      height: 80,
      collapsed: false,
      outputBus: 'brass-bus',
      instrument: 'orchestral-brass',
    },
    {
      id: 'woodwinds',
      name: 'Woodwinds',
      trackType: 'instrument',
      color: '#059669',
      volume: 0.65,
      pan: 0,
      mute: false,
      solo: false,
      armed: false,
      recordEnabled: false,
      inputMonitoring: false,
      height: 80,
      collapsed: false,
      outputBus: 'winds-bus',
      instrument: 'orchestral-woodwinds',
    },
    {
      id: 'percussion',
      name: 'Percussion',
      trackType: 'instrument',
      color: TRACK_COLORS.drums,
      volume: 0.7,
      pan: 0,
      mute: false,
      solo: false,
      armed: false,
      recordEnabled: false,
      inputMonitoring: false,
      height: 80,
      collapsed: false,
      outputBus: 'perc-bus',
      instrument: 'orchestral-percussion',
    },
    {
      id: 'timpani',
      name: 'Timpani',
      trackType: 'instrument',
      color: TRACK_COLORS.drums,
      volume: 0.75,
      pan: 0.1,
      mute: false,
      solo: false,
      armed: false,
      recordEnabled: false,
      inputMonitoring: false,
      height: 80,
      collapsed: false,
      outputBus: 'perc-bus',
      instrument: 'orchestral-percussion',
    },
    {
      id: 'piano',
      name: 'Piano',
      trackType: 'instrument',
      color: TRACK_COLORS.keys,
      volume: 0.65,
      pan: 0,
      mute: false,
      solo: false,
      armed: false,
      recordEnabled: false,
      inputMonitoring: false,
      height: 80,
      collapsed: false,
      outputBus: 'keys-bus',
      instrument: 'concert-grand',
    },
    {
      id: 'harp',
      name: 'Harp',
      trackType: 'instrument',
      color: TRACK_COLORS.keys,
      volume: 0.6,
      pan: -0.25,
      mute: false,
      solo: false,
      armed: false,
      recordEnabled: false,
      inputMonitoring: false,
      height: 80,
      collapsed: false,
      outputBus: 'keys-bus',
      instrument: 'orchestral-harp',
    },
    {
      id: 'strings-bus',
      name: 'Strings Bus',
      trackType: 'bus',
      color: TRACK_COLORS.bus,
      volume: 0.85,
      pan: 0,
      mute: false,
      solo: false,
      armed: false,
      recordEnabled: false,
      inputMonitoring: false,
      height: 60,
      collapsed: true,
      outputBus: 'orchestra-bus',
      effects: [
        { id: 'sb-reverb', name: 'Hall Reverb', type: 'reverb', bypass: false, preset: 'concert-hall', parameters: { mix: 25, decay: 2.5 } },
        { id: 'sb-eq', name: 'String EQ', type: 'eq', bypass: false },
      ],
    },
    {
      id: 'brass-bus',
      name: 'Brass Bus',
      trackType: 'bus',
      color: TRACK_COLORS.bus,
      volume: 0.8,
      pan: 0,
      mute: false,
      solo: false,
      armed: false,
      recordEnabled: false,
      inputMonitoring: false,
      height: 60,
      collapsed: true,
      outputBus: 'orchestra-bus',
      effects: [
        { id: 'bb-reverb', name: 'Hall Reverb', type: 'reverb', bypass: false, preset: 'concert-hall', parameters: { mix: 20 } },
        { id: 'bb-eq', name: 'Brass EQ', type: 'eq', bypass: false },
      ],
    },
    {
      id: 'winds-bus',
      name: 'Woodwinds Bus',
      trackType: 'bus',
      color: TRACK_COLORS.bus,
      volume: 0.75,
      pan: 0,
      mute: false,
      solo: false,
      armed: false,
      recordEnabled: false,
      inputMonitoring: false,
      height: 60,
      collapsed: true,
      outputBus: 'orchestra-bus',
      effects: [
        { id: 'wb-reverb', name: 'Hall Reverb', type: 'reverb', bypass: false, preset: 'concert-hall' },
      ],
    },
    {
      id: 'perc-bus',
      name: 'Percussion Bus',
      trackType: 'bus',
      color: TRACK_COLORS.bus,
      volume: 0.8,
      pan: 0,
      mute: false,
      solo: false,
      armed: false,
      recordEnabled: false,
      inputMonitoring: false,
      height: 60,
      collapsed: true,
      outputBus: 'orchestra-bus',
      effects: [
        { id: 'pb-reverb', name: 'Hall Reverb', type: 'reverb', bypass: false, preset: 'concert-hall', parameters: { mix: 30 } },
      ],
    },
    {
      id: 'keys-bus',
      name: 'Keys Bus',
      trackType: 'bus',
      color: TRACK_COLORS.bus,
      volume: 0.7,
      pan: 0,
      mute: false,
      solo: false,
      armed: false,
      recordEnabled: false,
      inputMonitoring: false,
      height: 60,
      collapsed: true,
      outputBus: 'orchestra-bus',
      effects: [
        { id: 'kb-reverb', name: 'Hall Reverb', type: 'reverb', bypass: false, preset: 'concert-hall' },
      ],
    },
    {
      id: 'orchestra-bus',
      name: 'Orchestra Bus',
      trackType: 'bus',
      color: TRACK_COLORS.master,
      volume: 0.9,
      pan: 0,
      mute: false,
      solo: false,
      armed: false,
      recordEnabled: false,
      inputMonitoring: false,
      height: 60,
      collapsed: false,
      outputBus: 'master',
      effects: [
        { id: 'ob-eq', name: 'Master EQ', type: 'eq', bypass: false },
        { id: 'ob-comp', name: 'Glue Comp', type: 'compressor', bypass: false, preset: 'orchestral-glue' },
      ],
    },
  ],
  routing: [
    { from: 'violins-1', to: 'strings-bus' },
    { from: 'violins-2', to: 'strings-bus' },
    { from: 'violas', to: 'strings-bus' },
    { from: 'cellos', to: 'strings-bus' },
    { from: 'basses', to: 'strings-bus' },
    { from: 'french-horns', to: 'brass-bus' },
    { from: 'trumpets', to: 'brass-bus' },
    { from: 'trombones', to: 'brass-bus' },
    { from: 'woodwinds', to: 'winds-bus' },
    { from: 'percussion', to: 'perc-bus' },
    { from: 'timpani', to: 'perc-bus' },
    { from: 'piano', to: 'keys-bus' },
    { from: 'harp', to: 'keys-bus' },
    { from: 'strings-bus', to: 'orchestra-bus' },
    { from: 'brass-bus', to: 'orchestra-bus' },
    { from: 'winds-bus', to: 'orchestra-bus' },
    { from: 'perc-bus', to: 'orchestra-bus' },
    { from: 'keys-bus', to: 'orchestra-bus' },
    { from: 'orchestra-bus', to: 'master' },
  ],
  useCases: [
    'Film scoring',
    'TV/game music',
    'Orchestral compositions',
    'Trailer music',
  ],
  tags: ['orchestral', 'film', 'cinematic', 'video', 'soundtrack', 'scoring'],
  isBuiltIn: true,
  isCommunity: false,
  createdAt: new Date('2024-01-01'),
  updatedAt: new Date('2024-01-01'),
};

export const BUILT_IN_TEMPLATES: StudioTemplate[] = [
  RECORDING_TEMPLATE,
  BEAT_MAKING_TEMPLATE,
  MIXING_STEMS_TEMPLATE,
  MASTERING_TEMPLATE,
  PODCAST_TEMPLATE,
  FILM_SCORING_TEMPLATE,
];

export const CATEGORY_INFO: Record<TemplateCategory, { name: string; icon: string; color: string; description: string }> = {
  'recording': {
    name: 'Recording',
    icon: 'Mic',
    color: '#4ade80',
    description: 'Templates for recording vocals and live instruments',
  },
  'beat-making': {
    name: 'Beat Making',
    icon: 'Drum',
    color: '#f87171',
    description: 'Templates for creating beats, drums, and electronic production',
  },
  'mixing': {
    name: 'Mixing',
    icon: 'Sliders',
    color: '#60a5fa',
    description: 'Templates for mixing stems and professional audio work',
  },
  'mastering': {
    name: 'Mastering',
    icon: 'Gauge',
    color: '#ec4899',
    description: 'Templates for mastering and final audio processing',
  },
  'podcast': {
    name: 'Podcast',
    icon: 'Podcast',
    color: '#34d399',
    description: 'Templates for podcast and voice recording',
  },
  'film-scoring': {
    name: 'Film Scoring',
    icon: 'Film',
    color: '#facc15',
    description: 'Templates for film, TV, and game scoring',
  },
  'custom': {
    name: 'Custom',
    icon: 'Star',
    color: '#a78bfa',
    description: 'Your saved custom templates',
  },
  'community': {
    name: 'Community',
    icon: 'Users',
    color: '#f472b6',
    description: 'Templates shared by the community',
  },
};

export function filterTemplates(templates: StudioTemplate[], filter: TemplateFilter): StudioTemplate[] {
  return templates.filter((template) => {
    if (filter.category && template.category !== filter.category) {
      return false;
    }
    if (filter.search) {
      const searchLower = filter.search.toLowerCase();
      const matchesName = template.name.toLowerCase().includes(searchLower);
      const matchesDescription = template.description.toLowerCase().includes(searchLower);
      const matchesTags = template.tags.some((tag) => tag.toLowerCase().includes(searchLower));
      if (!matchesName && !matchesDescription && !matchesTags) {
        return false;
      }
    }
    if (filter.tags && filter.tags.length > 0) {
      const hasAllTags = filter.tags.every((tag) =>
        template.tags.some((t) => t.toLowerCase() === tag.toLowerCase())
      );
      if (!hasAllTags) {
        return false;
      }
    }
    return true;
  });
}

export function getTemplatesByCategory(templates: StudioTemplate[]): Record<TemplateCategory, StudioTemplate[]> {
  const result: Record<TemplateCategory, StudioTemplate[]> = {
    'recording': [],
    'beat-making': [],
    'mixing': [],
    'mastering': [],
    'podcast': [],
    'film-scoring': [],
    'custom': [],
    'community': [],
  };
  templates.forEach((template) => {
    result[template.category].push(template);
  });
  return result;
}

export function createCustomTemplate(
  name: string,
  description: string,
  tracks: TemplateTrack[],
  routing: TemplateRouting[],
  tempo: number = 120,
  timeSignature: string = '4/4'
): StudioTemplate {
  return {
    id: `custom-${Date.now()}`,
    name,
    description,
    category: 'custom',
    icon: 'Star',
    color: '#a78bfa',
    tempo,
    timeSignature,
    duration: 300,
    tracks,
    routing,
    useCases: [],
    tags: ['custom'],
    isBuiltIn: false,
    isCommunity: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  };
}
