"""
MaxCore DigitalGPU — RTL Sketch Generator (Phase 4)

Generates synthesizable SystemVerilog RTL for MaxCore PE tiles.
Output can be synthesized to FPGA (Xilinx/Intel) or handed to an
ASIC flow (Cadence/Synopsys) for first-silicon exploration.

Generated modules:
  1. maxcore_pe        — Single Processing Element (MAC unit + register file)
  2. maxcore_array     — N×N systolic array of PEs with data routing
  3. maxcore_tile_ctrl — Tile controller (sequencer, address gen, FSM)
  4. maxcore_sram      — Parameterized SRAM wrapper
  5. maxcore_top       — Top-level integration module

All modules are parameterized via `#(parameter ...)` blocks so the
same RTL covers different tile sizes (4×4 → 128×128) and dtypes.

Usage:
    gen = RTLGenerator(PEConfig(array_n=16, freq_ghz=1.0))
    rtl = gen.generate_all()
    gen.write(output_dir='./maxcore_rtl/')
"""

import os
import math
from dataclasses import dataclass
from typing import Dict, List
from .maxcore_tile import PEConfig


class RTLGenerator:
    """
    Generates SystemVerilog RTL for MaxCore tiles.

    The generated RTL implements:
      - Weight-stationary systolic array for GEMM
      - On-chip SRAM for weight storage
      - AXI4-Lite control interface
      - AXI4-Stream data interfaces (A input, C output)
      - Parameterized dtype (FP32/FP16/BF16/INT8)
    """

    def __init__(self, config: PEConfig = None):
        self.config = config or PEConfig()
        self._modules: Dict[str, str] = {}

    def generate_all(self) -> Dict[str, str]:
        """Generate all RTL modules. Returns dict of module_name→RTL_string."""
        self._modules = {
            'maxcore_pe':        self._gen_pe(),
            'maxcore_sram':      self._gen_sram(),
            'maxcore_array':     self._gen_array(),
            'maxcore_tile_ctrl': self._gen_tile_ctrl(),
            'maxcore_top':       self._gen_top(),
        }
        return self._modules

    def write(self, output_dir: str = './maxcore_rtl/'):
        """Write all generated modules to .sv files."""
        os.makedirs(output_dir, exist_ok=True)
        if not self._modules:
            self.generate_all()
        for name, rtl in self._modules.items():
            path = os.path.join(output_dir, f'{name}.sv')
            with open(path, 'w') as f:
                f.write(rtl)
        # Write a package file with shared parameters
        pkg = self._gen_package()
        with open(os.path.join(output_dir, 'maxcore_pkg.sv'), 'w') as f:
            f.write(pkg)
        return output_dir

    def _gen_package(self) -> str:
        N = self.config.array_n
        bits = self.config.dtype_bits
        return f"""\
// MaxCore DigitalGPU — RTL Package
// Auto-generated by RTLGenerator — do not edit manually
// Config: {N}×{N} array, FP{bits}, {self.config.freq_ghz} GHz

package maxcore_pkg;

  // Data type
  parameter int DATA_W  = {bits};                 // data width in bits
  parameter int ARRAY_N = {N};                    // PE array dimension
  parameter int REG_D   = {self.config.reg_file_depth}; // register file depth per PE
  parameter int SRAM_KB = {self.config.sram_kb};  // SRAM per PE in KB

  // Derived
  parameter int SRAM_WORDS = (SRAM_KB * 1024 * 8) / DATA_W;
  parameter int ADDR_W     = $clog2(SRAM_WORDS);

  // MaxCore ISA opcodes (6-bit)
  typedef enum logic [5:0] {{
    OP_NOP    = 6'h00,
    OP_LOAD   = 6'h01,  // LDG  — global load
    OP_STORE  = 6'h02,  // STG  — global store
    OP_LDS    = 6'h03,  // LDS  — shared/SRAM load
    OP_STS    = 6'h04,  // STS  — shared/SRAM store
    OP_TMM    = 6'h10,  // Tensor matmul tile
    OP_TCONV  = 6'h11,  // Tensor conv tile
    OP_TATTN  = 6'h12,  // Fused attention tile
    OP_REDUCE = 6'h20,  // Deterministic reduction
    OP_ACT    = 6'h30,  // Fused activation (SiLU/GELU/ReLU)
    OP_ADD    = 6'h40,  // Element-wise add
    OP_MUL    = 6'h41,  // Element-wise mul
    OP_SYNC   = 6'h50,  // Barrier sync
    OP_BRA    = 6'h60,  // Branch
    OP_HALT   = 6'h7F   // End of program
  }} maxcore_opcode_t;

  // Reduction operations
  typedef enum logic [1:0] {{
    REDUCE_SUM  = 2'b00,
    REDUCE_MAX  = 2'b01,
    REDUCE_MEAN = 2'b10,
    REDUCE_MIN  = 2'b11
  }} reduce_op_t;

  // Activation types
  typedef enum logic [1:0] {{
    ACT_RELU = 2'b00,
    ACT_SILU = 2'b01,
    ACT_GELU = 2'b10
  }} act_type_t;

  // Instruction format (32-bit fixed width)
  typedef struct packed {{
    maxcore_opcode_t opcode;   // [31:26]
    logic [4:0]      rd;       // [25:21] destination register
    logic [4:0]      rs1;      // [20:16] source register 1
    logic [4:0]      rs2;      // [15:11] source register 2
    logic [10:0]     imm;      // [10:0]  immediate / control
  }} maxcore_instr_t;

endpackage : maxcore_pkg
"""

    def _gen_pe(self) -> str:
        bits = self.config.dtype_bits
        acc_bits = bits * 2  # accumulator twice width for precision
        return f"""\
// MaxCore DigitalGPU — Processing Element (PE)
// Auto-generated by RTLGenerator
// Implements: MAC (multiply-accumulate) + register file + SRAM interface

`include "maxcore_pkg.sv"
import maxcore_pkg::*;

module maxcore_pe #(
  parameter int DATA_W = {bits},          // input data width
  parameter int ACC_W  = {acc_bits},      // accumulator width
  parameter int REG_D  = {self.config.reg_file_depth}  // register file depth
)(
  input  logic              clk,
  input  logic              rst_n,

  // Systolic data flow (weight-stationary)
  input  logic [DATA_W-1:0] a_in,         // input feature (from left)
  input  logic [DATA_W-1:0] b_weight,     // weight (preloaded)
  input  logic              valid_in,      // input valid

  // Output to next PE (pass-through for systolic)
  output logic [DATA_W-1:0] a_out,
  output logic              valid_out,

  // Accumulator output (to reduction tree)
  output logic [ACC_W-1:0]  acc_out,
  output logic              acc_valid,

  // Control
  input  logic              acc_clear,    // reset accumulator for new tile
  input  logic              acc_en        // enable accumulation
);

  // ── Registers ──────────────────────────────────────────────────────────
  logic [ACC_W-1:0]  accumulator;
  logic [DATA_W-1:0] b_reg;               // weight register (stationary)
  logic [DATA_W-1:0] a_pipe;              // pipeline register for a_in
  logic              valid_pipe;

  // ── Register file (used for conditioning / FiLM parameters) ──────────
  logic [DATA_W-1:0] reg_file [0:REG_D-1];

  // ── MAC unit ───────────────────────────────────────────────────────────
  // FP32 multiply-accumulate using DSP inference
  // Synthesizer maps this to DSP48 (Xilinx) or DSP (Intel)
  logic [ACC_W-1:0] product;
  assign product = {{{{(ACC_W-DATA_W){{a_in[DATA_W-1]}}}}, a_in}} *
                   {{{{(ACC_W-DATA_W){{b_reg[DATA_W-1]}}}}, b_reg}};

  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      accumulator <= '0;
      a_pipe      <= '0;
      valid_pipe  <= 1'b0;
    end else begin
      // Pipeline a_in for systolic pass-through
      a_pipe     <= a_in;
      valid_pipe <= valid_in;

      // Accumulate
      if (acc_clear)
        accumulator <= '0;
      else if (valid_in && acc_en)
        accumulator <= accumulator + product;
    end
  end

  // ── Outputs ─────────────────────────────────────────────────────────────
  assign a_out    = a_pipe;
  assign valid_out = valid_pipe;
  assign acc_out   = accumulator;
  assign acc_valid = ~acc_clear;

endmodule : maxcore_pe
"""

    def _gen_sram(self) -> str:
        N = self.config.array_n
        bits = self.config.dtype_bits
        depth = (self.config.sram_kb * 1024 * 8) // bits
        addr_w = max(1, math.ceil(math.log2(depth)))
        return f"""\
// MaxCore DigitalGPU — SRAM Wrapper
// Auto-generated by RTLGenerator
// Single-port SRAM, synthesizable to BRAM (FPGA) or custom SRAM cell (ASIC)

module maxcore_sram #(
  parameter int DATA_W = {bits},
  parameter int DEPTH  = {depth},
  parameter int ADDR_W = {addr_w}
)(
  input  logic              clk,
  input  logic              we,           // write enable
  input  logic [ADDR_W-1:0] addr,
  input  logic [DATA_W-1:0] din,
  output logic [DATA_W-1:0] dout
);
  // Inferred BRAM — 2 pipeline stages
  logic [DATA_W-1:0] mem [0:DEPTH-1];
  logic [DATA_W-1:0] dout_r;

  always_ff @(posedge clk) begin
    if (we)
      mem[addr] <= din;
    dout_r <= mem[addr];
  end
  assign dout = dout_r;

endmodule : maxcore_sram
"""

    def _gen_array(self) -> str:
        N = self.config.array_n
        bits = self.config.dtype_bits
        acc_bits = bits * 2
        return f"""\
// MaxCore DigitalGPU — {N}×{N} Systolic PE Array
// Auto-generated by RTLGenerator
// Weight-stationary dataflow:
//   A  streams left→right  (input features)
//   B  preloaded (weights stationary in PEs)
//   C  accumulated at each PE, read out column by column

import maxcore_pkg::*;

module maxcore_array #(
  parameter int N      = {N},
  parameter int DATA_W = {bits},
  parameter int ACC_W  = {acc_bits}
)(
  input  logic                         clk,
  input  logic                         rst_n,

  // A input: N parallel row inputs
  input  logic [N-1:0][DATA_W-1:0]     a_in,
  input  logic [N-1:0]                 a_valid,

  // B preload interface (column-major weight loading)
  input  logic [N-1:0][N-1:0][DATA_W-1:0] b_weights,
  input  logic                             b_load,

  // Control
  input  logic                         acc_clear,
  input  logic                         acc_en,

  // C output: N×N accumulator values
  output logic [N-1:0][N-1:0][ACC_W-1:0] c_out,
  output logic                            c_valid
);

  // ── PE Array instantiation (NxN) ────────────────────────────────────────
  // a_wire[i][j] carries the A value flowing through row i at column j
  // valid_wire[i][j] carries the valid signal
  logic [N:0][N-1:0][DATA_W-1:0] a_wire;
  logic [N:0][N-1:0]             valid_wire;

  // Connect external inputs to wire[0]
  assign a_wire[0]    = a_in;
  assign valid_wire[0] = a_valid;

  genvar row, col;
  generate
    for (row = 0; row < N; row++) begin : gen_row
      for (col = 0; col < N; col++) begin : gen_col
        maxcore_pe #(
          .DATA_W(DATA_W),
          .ACC_W(ACC_W)
        ) pe_inst (
          .clk      (clk),
          .rst_n    (rst_n),
          .a_in     (a_wire[col][row]),
          .b_weight (b_weights[row][col]),
          .valid_in (valid_wire[col][row]),
          .a_out    (a_wire[col+1][row]),
          .valid_out(valid_wire[col+1][row]),
          .acc_out  (c_out[row][col]),
          .acc_valid(),
          .acc_clear(acc_clear),
          .acc_en   (acc_en)
        );
      end
    end
  endgenerate

  // c_valid: assert one cycle after last a_valid
  logic c_valid_r;
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) c_valid_r <= 1'b0;
    else        c_valid_r <= |a_valid;
  end
  assign c_valid = c_valid_r;

endmodule : maxcore_array
"""

    def _gen_tile_ctrl(self) -> str:
        N = self.config.array_n
        return f"""\
// MaxCore DigitalGPU — Tile Controller (FSM)
// Auto-generated by RTLGenerator
// Controls sequencing of: weight preload → A streaming → accumulation → readout

import maxcore_pkg::*;

module maxcore_tile_ctrl #(
  parameter int N      = {N},
  parameter int DATA_W = {self.config.dtype_bits}
)(
  input  logic               clk,
  input  logic               rst_n,

  // AXI4-Lite control interface
  input  logic               cmd_valid,
  input  maxcore_opcode_t    cmd_opcode,
  input  logic [31:0]        cmd_m,      // matrix M dimension
  input  logic [31:0]        cmd_n,      // matrix N dimension
  input  logic [31:0]        cmd_k,      // matrix K dimension
  output logic               cmd_ready,

  // Array control outputs
  output logic               acc_clear,
  output logic               acc_en,
  output logic               b_load,

  // DMA interface (simplified)
  output logic               dma_req,
  output logic [31:0]        dma_addr,
  output logic [31:0]        dma_len,
  input  logic               dma_ack,

  // Status
  output logic               busy,
  output logic               done
);

  typedef enum logic [2:0] {{
    ST_IDLE     = 3'd0,
    ST_LOADB    = 3'd1,   // preload weights into PE array
    ST_COMPUTE  = 3'd2,   // stream A, accumulate
    ST_READOUT  = 3'd3,   // read C from PEs
    ST_DONE     = 3'd4
  }} state_t;

  state_t state, next_state;
  logic [31:0] cycle_cnt;
  logic [31:0] m_reg, n_reg, k_reg;

  // Derived: total cycles for this tile
  logic [31:0] compute_cycles;
  assign compute_cycles = m_reg + k_reg + n_reg - 2;

  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      state      <= ST_IDLE;
      cycle_cnt  <= '0;
      m_reg <= '0; n_reg <= '0; k_reg <= '0;
    end else begin
      state <= next_state;
      if (state == ST_IDLE && cmd_valid) begin
        m_reg <= cmd_m; n_reg <= cmd_n; k_reg <= cmd_k;
        cycle_cnt <= '0;
      end else if (state == ST_COMPUTE || state == ST_LOADB) begin
        cycle_cnt <= cycle_cnt + 1;
      end
    end
  end

  always_comb begin
    next_state = state;
    acc_clear  = 1'b0;
    acc_en     = 1'b0;
    b_load     = 1'b0;
    dma_req    = 1'b0;
    dma_addr   = '0;
    dma_len    = '0;
    busy       = 1'b1;
    done       = 1'b0;
    cmd_ready  = 1'b0;

    unique case (state)
      ST_IDLE: begin
        busy      = 1'b0;
        cmd_ready = 1'b1;
        if (cmd_valid && cmd_opcode == OP_TMM)
          next_state = ST_LOADB;
      end

      ST_LOADB: begin
        b_load  = 1'b1;
        dma_req = 1'b1;
        dma_len = n_reg * k_reg;  // load B matrix
        if (dma_ack && cycle_cnt >= n_reg - 1)
          next_state = ST_COMPUTE;
      end

      ST_COMPUTE: begin
        acc_en = 1'b1;
        acc_clear = (cycle_cnt == '0);
        if (cycle_cnt >= compute_cycles - 1)
          next_state = ST_READOUT;
      end

      ST_READOUT: begin
        dma_req = 1'b1;
        dma_len = m_reg * n_reg;  // write C matrix
        if (dma_ack)
          next_state = ST_DONE;
      end

      ST_DONE: begin
        done       = 1'b1;
        next_state = ST_IDLE;
      end
    endcase
  end

endmodule : maxcore_tile_ctrl
"""

    def _gen_top(self) -> str:
        N = self.config.array_n
        bits = self.config.dtype_bits
        return f"""\
// MaxCore DigitalGPU — Top-Level Integration
// Auto-generated by RTLGenerator
// Integrates: PE array + SRAM + tile controller + AXI interfaces

import maxcore_pkg::*;

module maxcore_top #(
  parameter int N      = {N},
  parameter int DATA_W = {bits}
)(
  input  logic        clk,
  input  logic        rst_n,

  // AXI4-Lite control
  input  logic [31:0] s_axil_awaddr,
  input  logic        s_axil_awvalid,
  output logic        s_axil_awready,
  input  logic [31:0] s_axil_wdata,
  input  logic [3:0]  s_axil_wstrb,
  input  logic        s_axil_wvalid,
  output logic        s_axil_wready,
  output logic [1:0]  s_axil_bresp,
  output logic        s_axil_bvalid,
  input  logic        s_axil_bready,
  input  logic [31:0] s_axil_araddr,
  input  logic        s_axil_arvalid,
  output logic        s_axil_arready,
  output logic [31:0] s_axil_rdata,
  output logic [1:0]  s_axil_rresp,
  output logic        s_axil_rvalid,
  input  logic        s_axil_rready,

  // AXI4 memory (HBM/DDR)
  output logic [39:0] m_axi_araddr,
  output logic [7:0]  m_axi_arlen,
  output logic        m_axi_arvalid,
  input  logic        m_axi_arready,
  input  logic [DATA_W*N-1:0] m_axi_rdata,
  input  logic        m_axi_rvalid,
  output logic        m_axi_rready,

  // Status
  output logic        irq_done,    // interrupt when operation complete
  output logic [31:0] perf_cycles  // cycle counter for profiling
);

  // ── Internal wires ────────────────────────────────────────────────────
  logic [N-1:0][DATA_W-1:0]         a_array_in;
  logic [N-1:0]                     a_valid;
  logic [N-1:0][N-1:0][DATA_W-1:0]  b_weights;
  logic                              b_load, acc_clear, acc_en;
  logic [N-1:0][N-1:0][DATA_W*2-1:0] c_out;
  logic                               c_valid;
  logic                               dma_req, dma_ack;
  logic [31:0]                        dma_addr, dma_len;
  logic                               busy, done;
  maxcore_opcode_t                    cmd_opcode;
  logic                               cmd_valid, cmd_ready;
  logic [31:0]                        cmd_m, cmd_n, cmd_k;

  // ── Submodule instances ───────────────────────────────────────────────
  maxcore_array #(.N(N), .DATA_W(DATA_W)) u_array (
    .clk(clk), .rst_n(rst_n),
    .a_in(a_array_in), .a_valid(a_valid),
    .b_weights(b_weights), .b_load(b_load),
    .acc_clear(acc_clear), .acc_en(acc_en),
    .c_out(c_out), .c_valid(c_valid)
  );

  maxcore_tile_ctrl #(.N(N), .DATA_W(DATA_W)) u_ctrl (
    .clk(clk), .rst_n(rst_n),
    .cmd_valid(cmd_valid), .cmd_opcode(cmd_opcode),
    .cmd_m(cmd_m), .cmd_n(cmd_n), .cmd_k(cmd_k),
    .cmd_ready(cmd_ready),
    .acc_clear(acc_clear), .acc_en(acc_en), .b_load(b_load),
    .dma_req(dma_req), .dma_addr(dma_addr), .dma_len(dma_len),
    .dma_ack(dma_ack),
    .busy(busy), .done(done)
  );

  // ── Performance counter ───────────────────────────────────────────────
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n)     perf_cycles <= '0;
    else if (busy)  perf_cycles <= perf_cycles + 1;
  end

  assign irq_done = done;
  assign dma_ack  = m_axi_arready & m_axi_arvalid;

endmodule : maxcore_top
"""

    def summary(self) -> str:
        N = self.config.array_n
        bits = self.config.dtype_bits
        return (
            f"\nMaxCore RTL Generator Summary\n"
            f"  Array:     {N}×{N} = {N*N} PEs\n"
            f"  Dtype:     FP{bits}\n"
            f"  Freq:      {self.config.freq_ghz} GHz\n"
            f"  Peak:      {self.config.peak_tflops:.3f} TFLOP/s\n"
            f"  Modules:   {', '.join(self._modules.keys()) if self._modules else 'not generated'}\n"
        )
