import { useQuery } from "@tanstack/react-query";
import { getCsrfTokenFromCookie } from "@/lib/queryClient";
import { AppLayout } from "@/components/layout/AppLayout";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import { useRequireSubscription } from "@/hooks/useRequireAuth";
import { AlertCircle, Brain, Loader2, RefreshCw, Sparkles } from "lucide-react";

interface AnalyticsInsightResponse {
  insight: string;
  generatedAt: string;
  dataWindow: {
    start: string;
    end: string;
    dataPoints: number;
  };
}

async function generateAnalyticsInsight(): Promise<AnalyticsInsightResponse> {
  const csrfToken = getCsrfTokenFromCookie();
  const response = await fetch("/api/ai/analytics/insights", {
    method: "POST",
    credentials: "include",
    headers: {
      "Content-Type": "application/json",
      ...(csrfToken ? { "X-CSRF-Token": csrfToken } : {}),
    },
  });

  const body = await response.json().catch(() => null);
  if (!response.ok) {
    throw new Error(
      body?.error || `AI analysis could not be generated (HTTP ${response.status}).`,
    );
  }
  return body;
}

export default function AIDashboard() {
  const { user, isLoading: authLoading } = useRequireSubscription();
  const {
    data: insight,
    error,
    isFetching,
    refetch,
  } = useQuery({
    queryKey: ["/api/ai/analytics/insights"],
    queryFn: generateAnalyticsInsight,
    enabled: !!user,
    retry: false,
  });

  if (authLoading) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <div className="flex flex-col items-center gap-4">
          <Loader2 className="w-8 h-8 animate-spin text-primary" />
          <p className="text-muted-foreground">Loading AI analytics…</p>
        </div>
      </div>
    );
  }

  if (!user) return null;

  return (
    <AppLayout
      title="AI Analytics"
      subtitle="MaxCore analysis of your actual performance data"
    >
      <div className="max-w-4xl space-y-6">
        <div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
          <div>
            <h1 className="flex items-center gap-2 text-3xl font-bold">
              <Brain className="h-8 w-8 text-primary" />
              AI Analytics Dashboard
            </h1>
            <p className="mt-1 text-muted-foreground">
              Personalized analysis generated by MaxCore from your recorded analytics.
            </p>
          </div>
          <Button onClick={() => refetch()} disabled={isFetching}>
            {isFetching ? (
              <Loader2 className="mr-2 h-4 w-4 animate-spin" />
            ) : (
              <RefreshCw className="mr-2 h-4 w-4" />
            )}
            Generate analysis
          </Button>
        </div>

        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Sparkles className="h-5 w-5 text-primary" />
              Your AI insight
            </CardTitle>
            <CardDescription>
              This analysis is not available until MaxCore can process your data.
            </CardDescription>
          </CardHeader>
          <CardContent>
            {isFetching ? (
              <div className="flex min-h-40 flex-col items-center justify-center gap-3 text-center">
                <Loader2 className="h-8 w-8 animate-spin text-primary" />
                <p className="text-sm text-muted-foreground">
                  MaxCore is analyzing your performance data…
                </p>
              </div>
            ) : error ? (
              <Alert variant="destructive">
                <AlertCircle className="h-4 w-4" />
                <AlertTitle>AI analysis unavailable</AlertTitle>
                <AlertDescription>
                  {error instanceof Error ? error.message : "AI analysis could not be generated."}
                </AlertDescription>
              </Alert>
            ) : insight ? (
              <div className="space-y-5">
                <p className="whitespace-pre-wrap leading-7 text-foreground">
                  {insight.insight}
                </p>
                <div className="border-t pt-4 text-sm text-muted-foreground">
                  Based on {insight.dataWindow.dataPoints} recorded analytics data point
                  {insight.dataWindow.dataPoints === 1 ? "" : "s"} from{" "}
                  {new Date(insight.dataWindow.start).toLocaleDateString()} through{" "}
                  {new Date(insight.dataWindow.end).toLocaleDateString()}. Generated{" "}
                  {new Date(insight.generatedAt).toLocaleString()}.
                </div>
              </div>
            ) : (
              <p className="text-sm text-muted-foreground">
                Generate an analysis to see a MaxCore insight based on your analytics.
              </p>
            )}
          </CardContent>
        </Card>
      </div>
    </AppLayout>
  );
}