// Plugin type definitions and built-in plugin data.
// Extracted from pluginHostService.ts to break circular imports.

export type PluginCategory = 'instrument' | 'effect';
export type InstrumentType =
  | 'piano' | 'strings' | 'drums' | 'bass' | 'pad' | 'synth' | 'analog' | 'fm' | 'wavetable' | 'sampler'
  | 'brass' | 'woodwind' | 'guitar' | 'organ' | 'vocal' | 'ethnic' | 'mallet' | 'bell';
export type EffectType =
  | 'reverb' | 'delay' | 'chorus' | 'compressor' | 'eq' | 'limiter' | 'gate' | 'distortion' | 'phaser' | 'flanger'
  | 'stereo' | 'microphone' | 'mastering' | 'mixing'
  | 'plate' | 'hall' | 'spring' | 'shimmer' | 'ambient' | 'chamber'
  | 'tremolo' | 'vibrato' | 'ring-mod' | 'rotary' | 'auto-pan' | 'ensemble' | 'dimension'
  | 'transient-shaper' | 'de-esser' | 'maximizer' | 'leveler' | 'expander' | 'ducker'
  | 'vocal' | 'auto-tune' | 'harmony' | 'formant';

export interface PluginParameter {
  id: string;
  name: string;
  type: 'float' | 'int' | 'bool' | 'choice';
  defaultValue: number | boolean | string;
  minValue?: number;
  maxValue?: number;
  step?: number;
  choices?: string[];
  unit?: string;
  automatable: boolean;
}

export interface PluginDefinition {
  id: string;
  slug: string;
  name: string;
  category: PluginCategory;
  type: InstrumentType | EffectType;
  version: string;
  description: string;
  author: string;
  grade?: string;
  parameters: PluginParameter[];
  defaultPreset: Record<string, number | boolean | string>;
  oscillators?: OscillatorConfig[];
  envelope?: EnvelopeConfig;
}

export interface OscillatorConfig {
  type: 'sine' | 'square' | 'sawtooth' | 'triangle' | 'noise';
  detune: number;
  gain: number;
}

export interface EnvelopeConfig {
  attack: number;
  decay: number;
  sustain: number;
  release: number;
}

export interface PluginInstance {
  id: string;
  pluginId: string;
  projectId: string;
  trackId?: string;
  chainPosition: number;
  parameters: Record<string, number | boolean | string>;
  bypassed: boolean;
  createdAt: Date;
  updatedAt: Date;
}

export interface PluginPreset {
  id: string;
  userId: string;
  pluginId: string;
  name: string;
  category?: string;
  parameters: Record<string, number | boolean | string>;
  isDefault: boolean;
  isPublic: boolean;
  createdAt: Date;
}

export interface AudioBuffer {
  sampleRate: number;
  channels: number;
  length: number;
  data: Float32Array[];
}

export interface RenderContext {
  sampleRate: number;
  blockSize: number;
  currentTime: number;
  tempo: number;
}

export const BUILT_IN_INSTRUMENTS: PluginDefinition[] = [
  {
    id: 'mb-piano',
    slug: 'mb-piano',
    name: 'MB Piano',
    category: 'instrument',
    type: 'piano',
    version: '1.0.0',
    description: 'Virtual acoustic piano with realistic tone and dynamics',
    author: 'Max Booster', grade: 'A',
    oscillators: [
      { type: 'triangle', detune: 0, gain: 0.6 },
      { type: 'sine', detune: 0.5, gain: 0.3 },
      { type: 'sine', detune: 1200, gain: 0.1 },
    ],
    envelope: { attack: 0.002, decay: 0.3, sustain: 0.6, release: 0.5 },
    parameters: [
      { id: 'brightness', name: 'Brightness', type: 'float', defaultValue: 0.5, minValue: 0, maxValue: 1, automatable: true },
      { id: 'dynamics', name: 'Dynamics', type: 'float', defaultValue: 0.7, minValue: 0, maxValue: 1, automatable: true },
      { id: 'attack', name: 'Attack', type: 'float', defaultValue: 0.002, minValue: 0.001, maxValue: 0.5, unit: 's', automatable: true },
      { id: 'release', name: 'Release', type: 'float', defaultValue: 0.5, minValue: 0.01, maxValue: 5, unit: 's', automatable: true },
      { id: 'reverb', name: 'Reverb Amount', type: 'float', defaultValue: 0.2, minValue: 0, maxValue: 1, automatable: true },
      { id: 'tuning', name: 'Tuning', type: 'float', defaultValue: 0, minValue: -100, maxValue: 100, unit: 'cents', automatable: false },
      { id: 'volume', name: 'Volume', type: 'float', defaultValue: 0.8, minValue: 0, maxValue: 1, automatable: true },
    ],
    defaultPreset: { brightness: 0.5, dynamics: 0.7, attack: 0.002, release: 0.5, reverb: 0.2, tuning: 0, volume: 0.8 },
  },
  {
    id: 'mb-strings',
    slug: 'mb-strings',
    name: 'MB Strings',
    category: 'instrument',
    type: 'strings',
    version: '1.0.0',
    description: 'Lush string ensemble with multiple articulations',
    author: 'Max Booster', grade: 'A',
    oscillators: [
      { type: 'sawtooth', detune: -5, gain: 0.3 },
      { type: 'sawtooth', detune: 5, gain: 0.3 },
      { type: 'triangle', detune: 0, gain: 0.4 },
    ],
    envelope: { attack: 0.3, decay: 0.5, sustain: 0.8, release: 1.0 },
    parameters: [
      { id: 'attack', name: 'Attack', type: 'float', defaultValue: 0.3, minValue: 0.01, maxValue: 2, unit: 's', automatable: true },
      { id: 'release', name: 'Release', type: 'float', defaultValue: 1.0, minValue: 0.1, maxValue: 5, unit: 's', automatable: true },
      { id: 'warmth', name: 'Warmth', type: 'float', defaultValue: 0.6, minValue: 0, maxValue: 1, automatable: true },
      { id: 'ensemble', name: 'Ensemble Width', type: 'float', defaultValue: 0.5, minValue: 0, maxValue: 1, automatable: true },
      { id: 'vibrato', name: 'Vibrato', type: 'float', defaultValue: 0.3, minValue: 0, maxValue: 1, automatable: true },
      { id: 'expression', name: 'Expression', type: 'float', defaultValue: 1.0, minValue: 0, maxValue: 1, automatable: true },
      { id: 'volume', name: 'Volume', type: 'float', defaultValue: 0.8, minValue: 0, maxValue: 1, automatable: true },
    ],
    defaultPreset: { attack: 0.3, release: 1.0, warmth: 0.6, ensemble: 0.5, vibrato: 0.3, expression: 1.0, volume: 0.8 },
  },
  {
    id: 'mb-drums',
    slug: 'mb-drums',
    name: 'MB Drums',
    category: 'instrument',
    type: 'drums',
    version: '1.0.0',
    description: 'Punchy drum kit with multiple kits and samples',
    author: 'Max Booster', grade: 'A',
    oscillators: [
      { type: 'sine', detune: 0, gain: 1.0 },
      { type: 'noise', detune: 0, gain: 0.5 },
    ],
    envelope: { attack: 0.001, decay: 0.2, sustain: 0.0, release: 0.3 },
    parameters: [
      { id: 'kit', name: 'Drum Kit', type: 'choice', defaultValue: 'acoustic', choices: ['acoustic', 'electronic', 'hip-hop', 'rock', 'jazz'], automatable: false },
      { id: 'punch', name: 'Punch', type: 'float', defaultValue: 0.7, minValue: 0, maxValue: 1, automatable: true },
      { id: 'tone', name: 'Tone', type: 'float', defaultValue: 0.5, minValue: 0, maxValue: 1, automatable: true },
      { id: 'decay', name: 'Decay', type: 'float', defaultValue: 0.5, minValue: 0.1, maxValue: 2, unit: 's', automatable: true },
      { id: 'overhead', name: 'Overhead Mix', type: 'float', defaultValue: 0.3, minValue: 0, maxValue: 1, automatable: true },
      { id: 'room', name: 'Room', type: 'float', defaultValue: 0.2, minValue: 0, maxValue: 1, automatable: true },
      { id: 'volume', name: 'Volume', type: 'float', defaultValue: 0.8, minValue: 0, maxValue: 1, automatable: true },
    ],
    defaultPreset: { kit: 'acoustic', punch: 0.7, tone: 0.5, decay: 0.5, overhead: 0.3, room: 0.2, volume: 0.8 },
  },
  {
    id: 'mb-bass',
    slug: 'mb-bass',
    name: 'MB Bass',
    category: 'instrument',
    type: 'bass',
    version: '1.0.0',
    description: 'Deep bass synthesizer with sub and harmonics',
    author: 'Max Booster', grade: 'A',
    oscillators: [
      { type: 'sine', detune: 0, gain: 0.6 },
      { type: 'sawtooth', detune: -1200, gain: 0.3 },
      { type: 'square', detune: 0, gain: 0.1 },
    ],
    envelope: { attack: 0.01, decay: 0.3, sustain: 0.7, release: 0.2 },
    parameters: [
      { id: 'sub', name: 'Sub Level', type: 'float', defaultValue: 0.7, minValue: 0, maxValue: 1, automatable: true },
      { id: 'drive', name: 'Drive', type: 'float', defaultValue: 0.3, minValue: 0, maxValue: 1, automatable: true },
      { id: 'cutoff', name: 'Filter Cutoff', type: 'float', defaultValue: 2000, minValue: 20, maxValue: 20000, unit: 'Hz', automatable: true },
      { id: 'resonance', name: 'Resonance', type: 'float', defaultValue: 0.3, minValue: 0, maxValue: 1, automatable: true },
      { id: 'attack', name: 'Attack', type: 'float', defaultValue: 0.01, minValue: 0.001, maxValue: 0.5, unit: 's', automatable: true },
      { id: 'release', name: 'Release', type: 'float', defaultValue: 0.2, minValue: 0.01, maxValue: 2, unit: 's', automatable: true },
      { id: 'volume', name: 'Volume', type: 'float', defaultValue: 0.8, minValue: 0, maxValue: 1, automatable: true },
    ],
    defaultPreset: { sub: 0.7, drive: 0.3, cutoff: 2000, resonance: 0.3, attack: 0.01, release: 0.2, volume: 0.8 },
  },
  {
    id: 'mb-pad',
    slug: 'mb-pad',
    name: 'MB Synth Pad',
    category: 'instrument',
    type: 'pad',
    version: '1.0.0',
    description: 'Atmospheric pad synthesizer with rich textures',
    author: 'Max Booster', grade: 'A',
    oscillators: [
      { type: 'sawtooth', detune: -7, gain: 0.25 },
      { type: 'sawtooth', detune: 7, gain: 0.25 },
      { type: 'sine', detune: 1200, gain: 0.2 },
      { type: 'triangle', detune: 0, gain: 0.3 },
    ],
    envelope: { attack: 0.8, decay: 1.0, sustain: 0.9, release: 2.0 },
    parameters: [
      { id: 'attack', name: 'Attack', type: 'float', defaultValue: 0.8, minValue: 0.01, maxValue: 5, unit: 's', automatable: true },
      { id: 'release', name: 'Release', type: 'float', defaultValue: 2.0, minValue: 0.1, maxValue: 10, unit: 's', automatable: true },
      { id: 'detune', name: 'Detune', type: 'float', defaultValue: 7, minValue: 0, maxValue: 50, unit: 'cents', automatable: true },
      { id: 'filter', name: 'Filter Cutoff', type: 'float', defaultValue: 5000, minValue: 100, maxValue: 20000, unit: 'Hz', automatable: true },
      { id: 'lfoRate', name: 'LFO Rate', type: 'float', defaultValue: 0.5, minValue: 0.01, maxValue: 10, unit: 'Hz', automatable: true },
      { id: 'lfoDepth', name: 'LFO Depth', type: 'float', defaultValue: 0.3, minValue: 0, maxValue: 1, automatable: true },
      { id: 'chorus', name: 'Chorus', type: 'float', defaultValue: 0.4, minValue: 0, maxValue: 1, automatable: true },
      { id: 'volume', name: 'Volume', type: 'float', defaultValue: 0.7, minValue: 0, maxValue: 1, automatable: true },
    ],
    defaultPreset: { attack: 0.8, release: 2.0, detune: 7, filter: 5000, lfoRate: 0.5, lfoDepth: 0.3, chorus: 0.4, volume: 0.7 },
  },
  {
    id: 'mb-analog-synth',
    slug: 'mb-analog-synth',
    name: 'MB Analog Synth',
    category: 'instrument',
    type: 'analog',
    version: '1.0.0',
    description: 'Classic analog synthesizer with dual oscillators, ladder filter, and modulation',
    author: 'Max Booster', grade: 'A',
    oscillators: [
      { type: 'sawtooth', detune: 0, gain: 0.5 },
      { type: 'square', detune: -0.1, gain: 0.3 },
    ],
    envelope: { attack: 0.01, decay: 0.3, sustain: 0.6, release: 0.4 },
    parameters: [
      { id: 'osc1Wave', name: 'Osc 1 Wave', type: 'choice', defaultValue: 'sawtooth', choices: ['sine', 'square', 'sawtooth', 'triangle'], automatable: false },
      { id: 'osc1Detune', name: 'Osc 1 Detune', type: 'float', defaultValue: 0, minValue: -100, maxValue: 100, unit: 'cents', automatable: true },
      { id: 'osc1Level', name: 'Osc 1 Level', type: 'float', defaultValue: 0.5, minValue: 0, maxValue: 1, automatable: true },
      { id: 'osc2Wave', name: 'Osc 2 Wave', type: 'choice', defaultValue: 'square', choices: ['sine', 'square', 'sawtooth', 'triangle'], automatable: false },
      { id: 'osc2Detune', name: 'Osc 2 Detune', type: 'float', defaultValue: 7, minValue: -100, maxValue: 100, unit: 'cents', automatable: true },
      { id: 'osc2Level', name: 'Osc 2 Level', type: 'float', defaultValue: 0.3, minValue: 0, maxValue: 1, automatable: true },
      { id: 'oscMix', name: 'Oscillator Mix', type: 'float', defaultValue: 0.5, minValue: 0, maxValue: 1, automatable: true },
      { id: 'filterCutoff', name: 'Filter Cutoff', type: 'float', defaultValue: 5000, minValue: 20, maxValue: 20000, unit: 'Hz', automatable: true },
      { id: 'filterResonance', name: 'Filter Resonance', type: 'float', defaultValue: 0.3, minValue: 0, maxValue: 1, automatable: true },
      { id: 'filterEnvAmount', name: 'Filter Env Amount', type: 'float', defaultValue: 0.5, minValue: 0, maxValue: 1, automatable: true },
      { id: 'filterType', name: 'Filter Type', type: 'choice', defaultValue: 'lowpass', choices: ['lowpass', 'highpass', 'bandpass'], automatable: false },
      { id: 'lfoRate', name: 'LFO Rate', type: 'float', defaultValue: 2, minValue: 0.01, maxValue: 20, unit: 'Hz', automatable: true },
      { id: 'lfoDepth', name: 'LFO Depth', type: 'float', defaultValue: 0.2, minValue: 0, maxValue: 1, automatable: true },
      { id: 'lfoTarget', name: 'LFO Target', type: 'choice', defaultValue: 'filter', choices: ['filter', 'pitch', 'amp'], automatable: false },
      { id: 'attack', name: 'Attack', type: 'float', defaultValue: 0.01, minValue: 0.001, maxValue: 5, unit: 's', automatable: true },
      { id: 'decay', name: 'Decay', type: 'float', defaultValue: 0.3, minValue: 0.01, maxValue: 5, unit: 's', automatable: true },
      { id: 'sustain', name: 'Sustain', type: 'float', defaultValue: 0.6, minValue: 0, maxValue: 1, automatable: true },
      { id: 'release', name: 'Release', type: 'float', defaultValue: 0.4, minValue: 0.01, maxValue: 10, unit: 's', automatable: true },
      { id: 'glide', name: 'Glide Time', type: 'float', defaultValue: 0, minValue: 0, maxValue: 1, unit: 's', automatable: true },
      { id: 'volume', name: 'Volume', type: 'float', defaultValue: 0.8, minValue: 0, maxValue: 1, automatable: true },
    ],
    defaultPreset: {
      osc1Wave: 'sawtooth', osc1Detune: 0, osc1Level: 0.5,
      osc2Wave: 'square', osc2Detune: 7, osc2Level: 0.3, oscMix: 0.5,
      filterCutoff: 5000, filterResonance: 0.3, filterEnvAmount: 0.5, filterType: 'lowpass',
      lfoRate: 2, lfoDepth: 0.2, lfoTarget: 'filter',
      attack: 0.01, decay: 0.3, sustain: 0.6, release: 0.4, glide: 0, volume: 0.8,
    },
  },
  {
    id: 'mb-fm-synth',
    slug: 'mb-fm-synth',
    name: 'MB FM Synth',
    category: 'instrument',
    type: 'fm',
    version: '1.0.0',
    description: 'FM synthesis engine with 6 operators and 32 algorithms for complex harmonic content',
    author: 'Max Booster', grade: 'A',
    oscillators: [
      { type: 'sine', detune: 0, gain: 1.0 },
    ],
    envelope: { attack: 0.01, decay: 0.5, sustain: 0.4, release: 0.3 },
    parameters: [
      { id: 'algorithm', name: 'Algorithm', type: 'int', defaultValue: 1, minValue: 1, maxValue: 32, automatable: false },
      { id: 'op1Ratio', name: 'Op 1 Ratio', type: 'float', defaultValue: 1, minValue: 0.5, maxValue: 16, automatable: true },
      { id: 'op1Level', name: 'Op 1 Level', type: 'float', defaultValue: 1.0, minValue: 0, maxValue: 1, automatable: true },
      { id: 'op1Feedback', name: 'Op 1 Feedback', type: 'float', defaultValue: 0, minValue: 0, maxValue: 1, automatable: true },
      { id: 'op2Ratio', name: 'Op 2 Ratio', type: 'float', defaultValue: 2, minValue: 0.5, maxValue: 16, automatable: true },
      { id: 'op2Level', name: 'Op 2 Level', type: 'float', defaultValue: 0.5, minValue: 0, maxValue: 1, automatable: true },
      { id: 'op3Ratio', name: 'Op 3 Ratio', type: 'float', defaultValue: 3, minValue: 0.5, maxValue: 16, automatable: true },
      { id: 'op3Level', name: 'Op 3 Level', type: 'float', defaultValue: 0.3, minValue: 0, maxValue: 1, automatable: true },
      { id: 'op4Ratio', name: 'Op 4 Ratio', type: 'float', defaultValue: 4, minValue: 0.5, maxValue: 16, automatable: true },
      { id: 'op4Level', name: 'Op 4 Level', type: 'float', defaultValue: 0.2, minValue: 0, maxValue: 1, automatable: true },
      { id: 'op5Ratio', name: 'Op 5 Ratio', type: 'float', defaultValue: 5, minValue: 0.5, maxValue: 16, automatable: true },
      { id: 'op5Level', name: 'Op 5 Level', type: 'float', defaultValue: 0.15, minValue: 0, maxValue: 1, automatable: true },
      { id: 'op6Ratio', name: 'Op 6 Ratio', type: 'float', defaultValue: 7, minValue: 0.5, maxValue: 16, automatable: true },
      { id: 'op6Level', name: 'Op 6 Level', type: 'float', defaultValue: 0.1, minValue: 0, maxValue: 1, automatable: true },
      { id: 'modIndex', name: 'Modulation Index', type: 'float', defaultValue: 2.0, minValue: 0, maxValue: 10, automatable: true },
      { id: 'attack', name: 'Attack', type: 'float', defaultValue: 0.01, minValue: 0.001, maxValue: 5, unit: 's', automatable: true },
      { id: 'decay', name: 'Decay', type: 'float', defaultValue: 0.5, minValue: 0.01, maxValue: 5, unit: 's', automatable: true },
      { id: 'sustain', name: 'Sustain', type: 'float', defaultValue: 0.4, minValue: 0, maxValue: 1, automatable: true },
      { id: 'release', name: 'Release', type: 'float', defaultValue: 0.3, minValue: 0.01, maxValue: 10, unit: 's', automatable: true },
      { id: 'brightness', name: 'Brightness', type: 'float', defaultValue: 0.5, minValue: 0, maxValue: 1, automatable: true },
      { id: 'volume', name: 'Volume', type: 'float', defaultValue: 0.8, minValue: 0, maxValue: 1, automatable: true },
    ],
    defaultPreset: {
      algorithm: 1,
      op1Ratio: 1, op1Level: 1.0, op1Feedback: 0,
      op2Ratio: 2, op2Level: 0.5,
      op3Ratio: 3, op3Level: 0.3,
      op4Ratio: 4, op4Level: 0.2,
      op5Ratio: 5, op5Level: 0.15,
      op6Ratio: 7, op6Level: 0.1,
      modIndex: 2.0, attack: 0.01, decay: 0.5, sustain: 0.4, release: 0.3,
      brightness: 0.5, volume: 0.8,
    },
  },
  {
    id: 'mb-wavetable-synth',
    slug: 'mb-wavetable-synth',
    name: 'MB Wavetable Synth',
    category: 'instrument',
    type: 'wavetable',
    version: '1.0.0',
    description: 'Modern wavetable synthesizer with morphing capabilities',
    author: 'Max Booster', grade: 'A',
    oscillators: [
      { type: 'sine', detune: 0, gain: 1.0 },
    ],
    envelope: { attack: 0.05, decay: 0.4, sustain: 0.7, release: 0.5 },
    parameters: [
      { id: 'wavetable', name: 'Wavetable', type: 'choice', defaultValue: 'basic', choices: ['basic', 'digital', 'vocal', 'metallic', 'organic', 'chaos'], automatable: false },
      { id: 'wavePosition', name: 'Wave Position', type: 'float', defaultValue: 0, minValue: 0, maxValue: 1, automatable: true },
      { id: 'morphSpeed', name: 'Morph Speed', type: 'float', defaultValue: 0, minValue: 0, maxValue: 10, unit: 'Hz', automatable: true },
      { id: 'unison', name: 'Unison Voices', type: 'int', defaultValue: 1, minValue: 1, maxValue: 8, automatable: false },
      { id: 'unisonDetune', name: 'Unison Detune', type: 'float', defaultValue: 10, minValue: 0, maxValue: 100, unit: 'cents', automatable: true },
      { id: 'unisonSpread', name: 'Unison Spread', type: 'float', defaultValue: 0.5, minValue: 0, maxValue: 1, automatable: true },
      { id: 'filterCutoff', name: 'Filter Cutoff', type: 'float', defaultValue: 8000, minValue: 20, maxValue: 20000, unit: 'Hz', automatable: true },
      { id: 'filterResonance', name: 'Filter Resonance', type: 'float', defaultValue: 0.2, minValue: 0, maxValue: 1, automatable: true },
      { id: 'attack', name: 'Attack', type: 'float', defaultValue: 0.05, minValue: 0.001, maxValue: 5, unit: 's', automatable: true },
      { id: 'decay', name: 'Decay', type: 'float', defaultValue: 0.4, minValue: 0.01, maxValue: 5, unit: 's', automatable: true },
      { id: 'sustain', name: 'Sustain', type: 'float', defaultValue: 0.7, minValue: 0, maxValue: 1, automatable: true },
      { id: 'release', name: 'Release', type: 'float', defaultValue: 0.5, minValue: 0.01, maxValue: 10, unit: 's', automatable: true },
      { id: 'lfoToPosition', name: 'LFO to Position', type: 'float', defaultValue: 0, minValue: 0, maxValue: 1, automatable: true },
      { id: 'lfoRate', name: 'LFO Rate', type: 'float', defaultValue: 1, minValue: 0.01, maxValue: 20, unit: 'Hz', automatable: true },
      { id: 'volume', name: 'Volume', type: 'float', defaultValue: 0.8, minValue: 0, maxValue: 1, automatable: true },
    ],
    defaultPreset: {
      wavetable: 'basic', wavePosition: 0, morphSpeed: 0,
      unison: 1, unisonDetune: 10, unisonSpread: 0.5,
      filterCutoff: 8000, filterResonance: 0.2,
      attack: 0.05, decay: 0.4, sustain: 0.7, release: 0.5,
      lfoToPosition: 0, lfoRate: 1, volume: 0.8,
    },
  },
  {
    id: 'mb-sampler',
    slug: 'mb-sampler',
    name: 'MB Sampler',
    category: 'instrument',
    type: 'sampler',
    version: '1.0.0',
    description: 'Professional sampler with multi-sample support and advanced playback',
    author: 'Max Booster', grade: 'A',
    oscillators: [],
    envelope: { attack: 0.001, decay: 0.1, sustain: 1.0, release: 0.2 },
    parameters: [
      { id: 'sampleBank', name: 'Sample Bank', type: 'choice', defaultValue: 'piano', choices: ['piano', 'strings', 'brass', 'woodwinds', 'choir', 'percussion', 'synth', 'custom'], automatable: false },
      { id: 'rootNote', name: 'Root Note', type: 'int', defaultValue: 60, minValue: 0, maxValue: 127, automatable: false },
      { id: 'pitchRange', name: 'Pitch Range', type: 'int', defaultValue: 24, minValue: 1, maxValue: 48, automatable: false },
      { id: 'startPoint', name: 'Start Point', type: 'float', defaultValue: 0, minValue: 0, maxValue: 1, automatable: true },
      { id: 'endPoint', name: 'End Point', type: 'float', defaultValue: 1, minValue: 0, maxValue: 1, automatable: true },
      { id: 'loopEnabled', name: 'Loop', type: 'bool', defaultValue: false, automatable: false },
      { id: 'loopStart', name: 'Loop Start', type: 'float', defaultValue: 0.3, minValue: 0, maxValue: 1, automatable: true },
      { id: 'loopEnd', name: 'Loop End', type: 'float', defaultValue: 0.9, minValue: 0, maxValue: 1, automatable: true },
      { id: 'loopCrossfade', name: 'Loop Crossfade', type: 'float', defaultValue: 0.02, minValue: 0, maxValue: 0.5, automatable: true },
      { id: 'playbackMode', name: 'Playback Mode', type: 'choice', defaultValue: 'oneshot', choices: ['oneshot', 'sustain', 'loop'], automatable: false },
      { id: 'velocitySensitivity', name: 'Velocity Sensitivity', type: 'float', defaultValue: 0.8, minValue: 0, maxValue: 1, automatable: true },
      { id: 'attack', name: 'Attack', type: 'float', defaultValue: 0.001, minValue: 0.001, maxValue: 5, unit: 's', automatable: true },
      { id: 'decay', name: 'Decay', type: 'float', defaultValue: 0.1, minValue: 0.01, maxValue: 5, unit: 's', automatable: true },
      { id: 'sustain', name: 'Sustain', type: 'float', defaultValue: 1.0, minValue: 0, maxValue: 1, automatable: true },
      { id: 'release', name: 'Release', type: 'float', defaultValue: 0.2, minValue: 0.01, maxValue: 10, unit: 's', automatable: true },
      { id: 'filterCutoff', name: 'Filter Cutoff', type: 'float', defaultValue: 20000, minValue: 20, maxValue: 20000, unit: 'Hz', automatable: true },
      { id: 'filterResonance', name: 'Filter Resonance', type: 'float', defaultValue: 0, minValue: 0, maxValue: 1, automatable: true },
      { id: 'reverse', name: 'Reverse', type: 'bool', defaultValue: false, automatable: false },
      { id: 'timeStretch', name: 'Time Stretch', type: 'float', defaultValue: 1, minValue: 0.25, maxValue: 4, automatable: true },
      { id: 'volume', name: 'Volume', type: 'float', defaultValue: 0.8, minValue: 0, maxValue: 1, automatable: true },
    ],
    defaultPreset: {
      sampleBank: 'piano', rootNote: 60, pitchRange: 24,
      startPoint: 0, endPoint: 1, loopEnabled: false,
      loopStart: 0.3, loopEnd: 0.9, loopCrossfade: 0.02,
      playbackMode: 'oneshot', velocitySensitivity: 0.8,
      attack: 0.001, decay: 0.1, sustain: 1.0, release: 0.2,
      filterCutoff: 20000, filterResonance: 0, reverse: false,
      timeStretch: 1, volume: 0.8,
    },
  },
];

export const BUILT_IN_EFFECTS: PluginDefinition[] = [
  {
    id: 'mb-reverb',
    slug: 'mb-reverb',
    name: 'MB Reverb',
    category: 'effect',
    type: 'reverb',
    version: '1.0.0',
    description: 'Algorithmic reverb with multiple room types',
    author: 'Max Booster', grade: 'A',
    parameters: [
      { id: 'roomSize', name: 'Room Size', type: 'float', defaultValue: 0.5, minValue: 0, maxValue: 1, automatable: true },
      { id: 'decay', name: 'Decay Time', type: 'float', defaultValue: 2.0, minValue: 0.1, maxValue: 20, unit: 's', automatable: true },
      { id: 'damping', name: 'Damping', type: 'float', defaultValue: 0.5, minValue: 0, maxValue: 1, automatable: true },
      { id: 'preDelay', name: 'Pre-Delay', type: 'float', defaultValue: 20, minValue: 0, maxValue: 200, unit: 'ms', automatable: true },
      { id: 'diffusion', name: 'Diffusion', type: 'float', defaultValue: 0.8, minValue: 0, maxValue: 1, automatable: true },
      { id: 'highCut', name: 'High Cut', type: 'float', defaultValue: 8000, minValue: 1000, maxValue: 20000, unit: 'Hz', automatable: true },
      { id: 'lowCut', name: 'Low Cut', type: 'float', defaultValue: 100, minValue: 20, maxValue: 1000, unit: 'Hz', automatable: true },
      { id: 'mix', name: 'Dry/Wet Mix', type: 'float', defaultValue: 0.3, minValue: 0, maxValue: 1, automatable: true },
    ],
    defaultPreset: { roomSize: 0.5, decay: 2.0, damping: 0.5, preDelay: 20, diffusion: 0.8, highCut: 8000, lowCut: 100, mix: 0.3 },
  },
  {
    id: 'mb-delay',
    slug: 'mb-delay',
    name: 'MB Delay',
    category: 'effect',
    type: 'delay',
    version: '1.0.0',
    description: 'Stereo delay with sync and modulation',
    author: 'Max Booster', grade: 'A',
    parameters: [
      { id: 'timeLeft', name: 'Time Left', type: 'float', defaultValue: 250, minValue: 1, maxValue: 2000, unit: 'ms', automatable: true },
      { id: 'timeRight', name: 'Time Right', type: 'float', defaultValue: 375, minValue: 1, maxValue: 2000, unit: 'ms', automatable: true },
      { id: 'sync', name: 'Tempo Sync', type: 'bool', defaultValue: false, automatable: false },
      { id: 'syncNoteLeft', name: 'Sync Note L', type: 'choice', defaultValue: '1/4', choices: ['1/1', '1/2', '1/4', '1/8', '1/16', '1/4T', '1/8T'], automatable: false },
      { id: 'syncNoteRight', name: 'Sync Note R', type: 'choice', defaultValue: '1/4D', choices: ['1/1', '1/2', '1/4', '1/8', '1/16', '1/4D', '1/8D'], automatable: false },
      { id: 'feedback', name: 'Feedback', type: 'float', defaultValue: 0.4, minValue: 0, maxValue: 0.95, automatable: true },
      { id: 'highCut', name: 'High Cut', type: 'float', defaultValue: 6000, minValue: 500, maxValue: 20000, unit: 'Hz', automatable: true },
      { id: 'modRate', name: 'Mod Rate', type: 'float', defaultValue: 0.5, minValue: 0, maxValue: 5, unit: 'Hz', automatable: true },
      { id: 'modDepth', name: 'Mod Depth', type: 'float', defaultValue: 0.1, minValue: 0, maxValue: 1, automatable: true },
      { id: 'mix', name: 'Dry/Wet Mix', type: 'float', defaultValue: 0.3, minValue: 0, maxValue: 1, automatable: true },
    ],
    defaultPreset: { timeLeft: 250, timeRight: 375, sync: false, syncNoteLeft: '1/4', syncNoteRight: '1/4D', feedback: 0.4, highCut: 6000, modRate: 0.5, modDepth: 0.1, mix: 0.3 },
  },
  {
    id: 'mb-chorus',
    slug: 'mb-chorus',
    name: 'MB Chorus',
    category: 'effect',
    type: 'chorus',
    version: '1.0.0',
    description: 'Rich stereo chorus effect',
    author: 'Max Booster', grade: 'A',
    parameters: [
      { id: 'rate', name: 'Rate', type: 'float', defaultValue: 1.0, minValue: 0.1, maxValue: 10, unit: 'Hz', automatable: true },
      { id: 'depth', name: 'Depth', type: 'float', defaultValue: 0.5, minValue: 0, maxValue: 1, automatable: true },
      { id: 'delay', name: 'Delay', type: 'float', defaultValue: 7, minValue: 1, maxValue: 30, unit: 'ms', automatable: true },
      { id: 'voices', name: 'Voices', type: 'int', defaultValue: 3, minValue: 1, maxValue: 6, automatable: false },
      { id: 'spread', name: 'Stereo Spread', type: 'float', defaultValue: 0.7, minValue: 0, maxValue: 1, automatable: true },
      { id: 'mix', name: 'Dry/Wet Mix', type: 'float', defaultValue: 0.5, minValue: 0, maxValue: 1, automatable: true },
    ],
    defaultPreset: { rate: 1.0, depth: 0.5, delay: 7, voices: 3, spread: 0.7, mix: 0.5 },
  },
  {
    id: 'mb-compressor',
    slug: 'mb-compressor',
    name: 'MB Compressor',
    category: 'effect',
    type: 'compressor',
    version: '1.0.0',
    description: 'Professional dynamics compressor',
    author: 'Max Booster', grade: 'A',
    parameters: [
      { id: 'threshold', name: 'Threshold', type: 'float', defaultValue: -20, minValue: -60, maxValue: 0, unit: 'dB', automatable: true },
      { id: 'ratio', name: 'Ratio', type: 'float', defaultValue: 4, minValue: 1, maxValue: 20, automatable: true },
      { id: 'attack', name: 'Attack', type: 'float', defaultValue: 10, minValue: 0.1, maxValue: 200, unit: 'ms', automatable: true },
      { id: 'release', name: 'Release', type: 'float', defaultValue: 100, minValue: 10, maxValue: 2000, unit: 'ms', automatable: true },
      { id: 'knee', name: 'Knee', type: 'float', defaultValue: 6, minValue: 0, maxValue: 20, unit: 'dB', automatable: true },
      { id: 'makeupGain', name: 'Makeup Gain', type: 'float', defaultValue: 0, minValue: -12, maxValue: 24, unit: 'dB', automatable: true },
      { id: 'autoMakeup', name: 'Auto Makeup', type: 'bool', defaultValue: true, automatable: false },
      { id: 'sidechain', name: 'Sidechain', type: 'bool', defaultValue: false, automatable: false },
      { id: 'mix', name: 'Dry/Wet Mix', type: 'float', defaultValue: 1.0, minValue: 0, maxValue: 1, automatable: true },
    ],
    defaultPreset: { threshold: -20, ratio: 4, attack: 10, release: 100, knee: 6, makeupGain: 0, autoMakeup: true, sidechain: false, mix: 1.0 },
  },
  {
    id: 'mb-eq',
    slug: 'mb-eq',
    name: 'MB Parametric EQ',
    category: 'effect',
    type: 'eq',
    version: '1.0.0',
    description: '3-band parametric equalizer',
    author: 'Max Booster', grade: 'A',
    parameters: [
      { id: 'lowFreq', name: 'Low Freq', type: 'float', defaultValue: 80, minValue: 20, maxValue: 500, unit: 'Hz', automatable: true },
      { id: 'lowGain', name: 'Low Gain', type: 'float', defaultValue: 0, minValue: -24, maxValue: 24, unit: 'dB', automatable: true },
      { id: 'lowQ', name: 'Low Q', type: 'float', defaultValue: 0.7, minValue: 0.1, maxValue: 10, automatable: true },
      { id: 'lowType', name: 'Low Type', type: 'choice', defaultValue: 'shelf', choices: ['shelf', 'peak', 'highpass'], automatable: false },
      { id: 'midFreq', name: 'Mid Freq', type: 'float', defaultValue: 1000, minValue: 100, maxValue: 10000, unit: 'Hz', automatable: true },
      { id: 'midGain', name: 'Mid Gain', type: 'float', defaultValue: 0, minValue: -24, maxValue: 24, unit: 'dB', automatable: true },
      { id: 'midQ', name: 'Mid Q', type: 'float', defaultValue: 1.0, minValue: 0.1, maxValue: 10, automatable: true },
      { id: 'highFreq', name: 'High Freq', type: 'float', defaultValue: 8000, minValue: 2000, maxValue: 20000, unit: 'Hz', automatable: true },
      { id: 'highGain', name: 'High Gain', type: 'float', defaultValue: 0, minValue: -24, maxValue: 24, unit: 'dB', automatable: true },
      { id: 'highQ', name: 'High Q', type: 'float', defaultValue: 0.7, minValue: 0.1, maxValue: 10, automatable: true },
      { id: 'highType', name: 'High Type', type: 'choice', defaultValue: 'shelf', choices: ['shelf', 'peak', 'lowpass'], automatable: false },
      { id: 'outputGain', name: 'Output Gain', type: 'float', defaultValue: 0, minValue: -12, maxValue: 12, unit: 'dB', automatable: true },
    ],
    defaultPreset: { lowFreq: 80, lowGain: 0, lowQ: 0.7, lowType: 'shelf', midFreq: 1000, midGain: 0, midQ: 1.0, highFreq: 8000, highGain: 0, highQ: 0.7, highType: 'shelf', outputGain: 0 },
  },
  {
    id: 'mb-limiter',
    slug: 'mb-limiter',
    name: 'MB Limiter',
    category: 'effect',
    type: 'limiter',
    version: '1.0.0',
    description: 'Brickwall limiter for mastering',
    author: 'Max Booster', grade: 'A',
    parameters: [
      { id: 'ceiling', name: 'Ceiling', type: 'float', defaultValue: -0.3, minValue: -6, maxValue: 0, unit: 'dB', automatable: true },
      { id: 'threshold', name: 'Threshold', type: 'float', defaultValue: -6, minValue: -24, maxValue: 0, unit: 'dB', automatable: true },
      { id: 'release', name: 'Release', type: 'float', defaultValue: 100, minValue: 10, maxValue: 1000, unit: 'ms', automatable: true },
      { id: 'lookahead', name: 'Lookahead', type: 'float', defaultValue: 5, minValue: 0, maxValue: 20, unit: 'ms', automatable: false },
      { id: 'truePeak', name: 'True Peak', type: 'bool', defaultValue: true, automatable: false },
      { id: 'link', name: 'Stereo Link', type: 'bool', defaultValue: true, automatable: false },
    ],
    defaultPreset: { ceiling: -0.3, threshold: -6, release: 100, lookahead: 5, truePeak: true, link: true },
  },
  {
    id: 'mb-gate',
    slug: 'mb-gate',
    name: 'MB Noise Gate',
    category: 'effect',
    type: 'gate',
    version: '1.0.0',
    description: 'Noise gate with expander mode',
    author: 'Max Booster', grade: 'A',
    parameters: [
      { id: 'threshold', name: 'Threshold', type: 'float', defaultValue: -40, minValue: -80, maxValue: 0, unit: 'dB', automatable: true },
      { id: 'range', name: 'Range', type: 'float', defaultValue: -80, minValue: -80, maxValue: 0, unit: 'dB', automatable: true },
      { id: 'attack', name: 'Attack', type: 'float', defaultValue: 1, minValue: 0.01, maxValue: 50, unit: 'ms', automatable: true },
      { id: 'hold', name: 'Hold', type: 'float', defaultValue: 50, minValue: 0, maxValue: 500, unit: 'ms', automatable: true },
      { id: 'release', name: 'Release', type: 'float', defaultValue: 100, minValue: 10, maxValue: 2000, unit: 'ms', automatable: true },
      { id: 'hysteresis', name: 'Hysteresis', type: 'float', defaultValue: 3, minValue: 0, maxValue: 12, unit: 'dB', automatable: true },
      { id: 'sidechain', name: 'Sidechain', type: 'bool', defaultValue: false, automatable: false },
      { id: 'scFilter', name: 'SC Filter', type: 'float', defaultValue: 100, minValue: 20, maxValue: 5000, unit: 'Hz', automatable: true },
    ],
    defaultPreset: { threshold: -40, range: -80, attack: 1, hold: 50, release: 100, hysteresis: 3, sidechain: false, scFilter: 100 },
  },
    { id: 'mb-distortion', slug: 'mb-distortion', name: 'MB Distortion FX', category: 'effect', type: 'distortion', version: '2.0.0', description: 'All-purpose multi-mode distortion effect unit', author: 'Max Booster', grade: 'A', parameters: [{ id: 'type', name: 'Distortion Type', type: 'choice', defaultValue: 'distortion', choices: ['overdrive','distortion','fuzz','bitcrush','waveshape','tube','transistor','tape'], automatable: false }, { id: 'drive', name: 'Drive', type: 'float', defaultValue: 0.5, minValue: 0, maxValue: 1, automatable: true }, { id: 'tone', name: 'Tone', type: 'float', defaultValue: 0.5, minValue: 0, maxValue: 1, automatable: true }, { id: 'presence', name: 'Presence', type: 'float', defaultValue: 0.5, minValue: 0, maxValue: 1, automatable: true }, { id: 'low_cut', name: 'Low Cut', type: 'float', defaultValue: 100, minValue: 20, maxValue: 2000, unit: 'Hz', automatable: true }, { id: 'high_cut', name: 'High Cut', type: 'float', defaultValue: 8000, minValue: 1000, maxValue: 20000, unit: 'Hz', automatable: true }, { id: 'output', name: 'Output Level', type: 'float', defaultValue: 0, minValue: -18, maxValue: 18, unit: 'dB', automatable: true }, { id: 'mix', name: 'Mix', type: 'float', defaultValue: 0.5, minValue: 0, maxValue: 1, automatable: true }], defaultPreset: { type: 'distortion', drive: 0.5, tone: 0.5, presence: 0.5, low_cut: 100, high_cut: 8000, output: 0, mix: 0.5 } },
  {
    id: 'mb-phaser',
    slug: 'mb-phaser',
    name: 'MB Phaser',
    category: 'effect',
    type: 'phaser',
    version: '1.0.0',
    description: 'Classic phaser with multiple stages and stereo modulation',
    author: 'Max Booster', grade: 'A',
    parameters: [
      { id: 'rate', name: 'Rate', type: 'float', defaultValue: 0.5, minValue: 0.01, maxValue: 10, unit: 'Hz', automatable: true },
      { id: 'depth', name: 'Depth', type: 'float', defaultValue: 0.7, minValue: 0, maxValue: 1, automatable: true },
      { id: 'feedback', name: 'Feedback', type: 'float', defaultValue: 0.5, minValue: 0, maxValue: 0.99, automatable: true },
      { id: 'stages', name: 'Stages', type: 'int', defaultValue: 4, minValue: 2, maxValue: 12, automatable: false },
      { id: 'centerFreq', name: 'Center Frequency', type: 'float', defaultValue: 1000, minValue: 100, maxValue: 5000, unit: 'Hz', automatable: true },
      { id: 'spread', name: 'Stereo Spread', type: 'float', defaultValue: 0.5, minValue: 0, maxValue: 1, automatable: true },
      { id: 'mix', name: 'Mix', type: 'float', defaultValue: 0.5, minValue: 0, maxValue: 1, automatable: true },
      { id: 'lfoWave', name: 'LFO Wave', type: 'choice', defaultValue: 'sine', choices: ['sine', 'triangle', 'sample_hold'], automatable: false },
      { id: 'tempoSync', name: 'Tempo Sync', type: 'bool', defaultValue: false, automatable: false },
      { id: 'syncDivision', name: 'Sync Division', type: 'choice', defaultValue: '1/4', choices: ['1/16', '1/8', '1/4', '1/2', '1/1', '2/1'], automatable: false },
    ],
    defaultPreset: { rate: 0.5, depth: 0.7, feedback: 0.5, stages: 4, centerFreq: 1000, spread: 0.5, mix: 0.5, lfoWave: 'sine', tempoSync: false, syncDivision: '1/4' },
  },
  {
    id: 'mb-flanger',
    slug: 'mb-flanger',
    name: 'MB Flanger',
    category: 'effect',
    type: 'flanger',
    version: '1.0.0',
    description: 'Vintage flanger with through-zero capability',
    author: 'Max Booster', grade: 'A',
    parameters: [
      { id: 'rate', name: 'Rate', type: 'float', defaultValue: 0.3, minValue: 0.01, maxValue: 10, unit: 'Hz', automatable: true },
      { id: 'depth', name: 'Depth', type: 'float', defaultValue: 0.6, minValue: 0, maxValue: 1, automatable: true },
      { id: 'delay', name: 'Delay', type: 'float', defaultValue: 5, minValue: 0.5, maxValue: 20, unit: 'ms', automatable: true },
      { id: 'feedback', name: 'Feedback', type: 'float', defaultValue: 0.5, minValue: -0.99, maxValue: 0.99, automatable: true },
      { id: 'mix', name: 'Mix', type: 'float', defaultValue: 0.5, minValue: 0, maxValue: 1, automatable: true },
      { id: 'stereoPhase', name: 'Stereo Phase', type: 'float', defaultValue: 0.25, minValue: 0, maxValue: 0.5, automatable: true },
      { id: 'throughZero', name: 'Through Zero', type: 'bool', defaultValue: false, automatable: false },
      { id: 'manualMode', name: 'Manual Mode', type: 'bool', defaultValue: false, automatable: false },
      { id: 'manualDelay', name: 'Manual Delay', type: 'float', defaultValue: 5, minValue: 0.1, maxValue: 20, unit: 'ms', automatable: true },
      { id: 'lfoWave', name: 'LFO Wave', type: 'choice', defaultValue: 'sine', choices: ['sine', 'triangle'], automatable: false },
      { id: 'tempoSync', name: 'Tempo Sync', type: 'bool', defaultValue: false, automatable: false },
    ],
    defaultPreset: { rate: 0.3, depth: 0.6, delay: 5, feedback: 0.5, mix: 0.5, stereoPhase: 0.25, throughZero: false, manualMode: false, manualDelay: 5, lfoWave: 'sine', tempoSync: false },
  },

  // ─── REVERB VARIANTS (unlocked from DSP engine) ───────────────────────────
  {
    id: 'mb-plate-reverb',
    slug: 'mb-plate-reverb',
    name: 'MB Plate Reverb',
    category: 'effect',
    type: 'plate',
    version: '1.0.0',
    description: 'Classic EMT 140-style plate reverb — dense, smooth, and silky',
    author: 'Max Booster', grade: 'A',
    parameters: [
      { id: 'decay', name: 'Decay Time', type: 'float', defaultValue: 2.5, minValue: 0.3, maxValue: 10, unit: 's', automatable: true },
      { id: 'preDelay', name: 'Pre-Delay', type: 'float', defaultValue: 10, minValue: 0, maxValue: 150, unit: 'ms', automatable: true },
      { id: 'damping', name: 'Damping', type: 'float', defaultValue: 0.6, minValue: 0, maxValue: 1, automatable: true },
      { id: 'diffusion', name: 'Diffusion', type: 'float', defaultValue: 0.9, minValue: 0, maxValue: 1, automatable: true },
      { id: 'lowCut', name: 'Low Cut', type: 'float', defaultValue: 80, minValue: 20, maxValue: 500, unit: 'Hz', automatable: true },
      { id: 'highCut', name: 'High Cut', type: 'float', defaultValue: 10000, minValue: 2000, maxValue: 20000, unit: 'Hz', automatable: true },
      { id: 'mix', name: 'Dry/Wet', type: 'float', defaultValue: 0.3, minValue: 0, maxValue: 1, automatable: true },
    ],
    defaultPreset: { decay: 2.5, preDelay: 10, damping: 0.6, diffusion: 0.9, lowCut: 80, highCut: 10000, mix: 0.3 },
  },
  {
    id: 'mb-hall-reverb',
    slug: 'mb-hall-reverb',
    name: 'MB Hall Reverb',
    category: 'effect',
    type: 'hall',
    version: '1.0.0',
    description: 'Large concert hall reverb with wide, three-dimensional space',
    author: 'Max Booster', grade: 'A',
    parameters: [
      { id: 'size', name: 'Hall Size', type: 'float', defaultValue: 0.8, minValue: 0.1, maxValue: 1, automatable: true },
      { id: 'decay', name: 'Decay Time', type: 'float', defaultValue: 4.0, minValue: 0.5, maxValue: 20, unit: 's', automatable: true },
      { id: 'preDelay', name: 'Pre-Delay', type: 'float', defaultValue: 30, minValue: 0, maxValue: 200, unit: 'ms', automatable: true },
      { id: 'earlyReflections', name: 'Early Reflections', type: 'float', defaultValue: 0.5, minValue: 0, maxValue: 1, automatable: true },
      { id: 'damping', name: 'Damping', type: 'float', defaultValue: 0.4, minValue: 0, maxValue: 1, automatable: true },
      { id: 'diffusion', name: 'Diffusion', type: 'float', defaultValue: 0.85, minValue: 0, maxValue: 1, automatable: true },
      { id: 'lowCut', name: 'Low Cut', type: 'float', defaultValue: 60, minValue: 20, maxValue: 500, unit: 'Hz', automatable: true },
      { id: 'highCut', name: 'High Cut', type: 'float', defaultValue: 12000, minValue: 2000, maxValue: 20000, unit: 'Hz', automatable: true },
      { id: 'modDepth', name: 'Modulation', type: 'float', defaultValue: 0.1, minValue: 0, maxValue: 1, automatable: true },
      { id: 'mix', name: 'Dry/Wet', type: 'float', defaultValue: 0.25, minValue: 0, maxValue: 1, automatable: true },
    ],
    defaultPreset: { size: 0.8, decay: 4.0, preDelay: 30, earlyReflections: 0.5, damping: 0.4, diffusion: 0.85, lowCut: 60, highCut: 12000, modDepth: 0.1, mix: 0.25 },
  },
  {
    id: 'mb-spring-reverb',
    slug: 'mb-spring-reverb',
    name: 'MB Spring Reverb',
    category: 'effect',
    type: 'spring',
    version: '1.0.0',
    description: 'Vintage spring tank reverb — drip, twang, and surf-guitar character',
    author: 'Max Booster', grade: 'A',
    parameters: [
      { id: 'decay', name: 'Decay', type: 'float', defaultValue: 1.8, minValue: 0.3, maxValue: 6, unit: 's', automatable: true },
      { id: 'tension', name: 'Spring Tension', type: 'float', defaultValue: 0.5, minValue: 0, maxValue: 1, automatable: true },
      { id: 'drip', name: 'Drip', type: 'float', defaultValue: 0.4, minValue: 0, maxValue: 1, automatable: true },
      { id: 'diffusion', name: 'Diffusion', type: 'float', defaultValue: 0.6, minValue: 0, maxValue: 1, automatable: true },
      { id: 'toneFilter', name: 'Tone', type: 'float', defaultValue: 0.5, minValue: 0, maxValue: 1, automatable: true },
      { id: 'mix', name: 'Dry/Wet', type: 'float', defaultValue: 0.35, minValue: 0, maxValue: 1, automatable: true },
    ],
    defaultPreset: { decay: 1.8, tension: 0.5, drip: 0.4, diffusion: 0.6, toneFilter: 0.5, mix: 0.35 },
  },
  {
    id: 'mb-shimmer-reverb',
    slug: 'mb-shimmer-reverb',
    name: 'MB Shimmer Reverb',
    category: 'effect',
    type: 'shimmer',
    version: '1.0.0',
    description: 'Ethereal shimmer reverb with pitch-shifted feedback — cinematic and evolving',
    author: 'Max Booster', grade: 'A',
    parameters: [
      { id: 'decay', name: 'Decay Time', type: 'float', defaultValue: 5.0, minValue: 1, maxValue: 20, unit: 's', automatable: true },
      { id: 'shimmer', name: 'Shimmer Amount', type: 'float', defaultValue: 0.6, minValue: 0, maxValue: 1, automatable: true },
      { id: 'shimmerPitch', name: 'Shimmer Pitch', type: 'choice', defaultValue: '+1oct', choices: ['+1oct', '+2oct', '+5th', '-1oct', '+har'], automatable: false },
      { id: 'feedback', name: 'Feedback', type: 'float', defaultValue: 0.7, minValue: 0, maxValue: 0.99, automatable: true },
      { id: 'diffusion', name: 'Diffusion', type: 'float', defaultValue: 0.8, minValue: 0, maxValue: 1, automatable: true },
      { id: 'damping', name: 'Damping', type: 'float', defaultValue: 0.3, minValue: 0, maxValue: 1, automatable: true },
      { id: 'modRate', name: 'Mod Rate', type: 'float', defaultValue: 0.2, minValue: 0, maxValue: 2, unit: 'Hz', automatable: true },
      { id: 'mix', name: 'Dry/Wet', type: 'float', defaultValue: 0.4, minValue: 0, maxValue: 1, automatable: true },
    ],
    defaultPreset: { decay: 5.0, shimmer: 0.6, shimmerPitch: '+1oct', feedback: 0.7, diffusion: 0.8, damping: 0.3, modRate: 0.2, mix: 0.4 },
  },
    { id: 'mb-gated-reverb', slug: 'mb-gated-reverb', name: 'MB Gated Reverb FX', category: 'effect', type: 'reverb', version: '2.0.0', description: '1980s gated snare reverb with hard gate cutoff', author: 'Max Booster', grade: 'A', parameters: [{ id: 'size', name: 'Room Size', type: 'float', defaultValue: 0.4, minValue: 0, maxValue: 1, automatable: true }, { id: 'decay', name: 'Decay Time', type: 'float', defaultValue: 0.6, minValue: 0.1, maxValue: 20, unit: 's', automatable: true }, { id: 'pre_delay', name: 'Pre-Delay', type: 'float', defaultValue: 8, minValue: 0, maxValue: 150, unit: 'ms', automatable: true }, { id: 'diffusion', name: 'Diffusion', type: 'float', defaultValue: 0.5, minValue: 0, maxValue: 1, automatable: true }, { id: 'damping', name: 'Damping', type: 'float', defaultValue: 0.6, minValue: 0, maxValue: 1, automatable: true }, { id: 'high_cut', name: 'High Cut', type: 'float', defaultValue: 6000, minValue: 500, maxValue: 20000, unit: 'Hz', automatable: true }, { id: 'width', name: 'Stereo Width', type: 'float', defaultValue: 1, minValue: 0, maxValue: 1, automatable: true }, { id: 'early_mix', name: 'Early/Tail Mix', type: 'float', defaultValue: 0.5, minValue: 0, maxValue: 1, automatable: true }, { id: 'mix', name: 'Mix', type: 'float', defaultValue: 0.5, minValue: 0, maxValue: 1, automatable: true }], defaultPreset: { size: 0.4, decay: 0.6, pre_delay: 8, diffusion: 0.5, damping: 0.6, high_cut: 6000, width: 1, early_mix: 0.5, mix: 0.5 } },
  {
    id: 'mb-ambient-reverb',
    slug: 'mb-ambient-reverb',
    name: 'MB Ambient Reverb',
    category: 'effect',
    type: 'ambient',
    version: '1.0.0',
    description: 'Infinite-sustain ambient reverb for drone and soundscape textures',
    author: 'Max Booster', grade: 'A',
    parameters: [
      { id: 'density', name: 'Density', type: 'float', defaultValue: 0.9, minValue: 0, maxValue: 1, automatable: true },
      { id: 'size', name: 'Space Size', type: 'float', defaultValue: 0.95, minValue: 0, maxValue: 1, automatable: true },
      { id: 'decay', name: 'Decay', type: 'float', defaultValue: 12.0, minValue: 2, maxValue: 40, unit: 's', automatable: true },
      { id: 'freeze', name: 'Freeze', type: 'bool', defaultValue: false, automatable: true },
      { id: 'modDepth', name: 'Modulation', type: 'float', defaultValue: 0.3, minValue: 0, maxValue: 1, automatable: true },
      { id: 'lowCut', name: 'Low Cut', type: 'float', defaultValue: 100, minValue: 20, maxValue: 1000, unit: 'Hz', automatable: true },
      { id: 'highCut', name: 'High Cut', type: 'float', defaultValue: 8000, minValue: 1000, maxValue: 20000, unit: 'Hz', automatable: true },
      { id: 'mix', name: 'Dry/Wet', type: 'float', defaultValue: 0.5, minValue: 0, maxValue: 1, automatable: true },
    ],
    defaultPreset: { density: 0.9, size: 0.95, decay: 12.0, freeze: false, modDepth: 0.3, lowCut: 100, highCut: 8000, mix: 0.5 },
  },

  // ─── COMPRESSOR CHARACTERS (unlocked from DSP engine) ────────────────────
  {
    id: 'mb-vca-compressor',
    slug: 'mb-vca-compressor',
    name: 'MB VCA Compressor',
    category: 'effect',
    type: 'compressor',
    version: '1.0.0',
    description: 'Ultra-fast VCA compressor — punchy and precise, inspired by the 1176 classic',
    author: 'Max Booster', grade: 'A',
    parameters: [
      { id: 'threshold', name: 'Threshold', type: 'float', defaultValue: -18, minValue: -60, maxValue: 0, unit: 'dB', automatable: true },
      { id: 'ratio', name: 'Ratio', type: 'float', defaultValue: 4, minValue: 1, maxValue: 20, automatable: true },
      { id: 'attack', name: 'Attack', type: 'float', defaultValue: 3, minValue: 0.05, maxValue: 50, unit: 'ms', automatable: true },
      { id: 'release', name: 'Release', type: 'float', defaultValue: 100, minValue: 10, maxValue: 1200, unit: 'ms', automatable: true },
      { id: 'knee', name: 'Knee', type: 'float', defaultValue: 3, minValue: 0, maxValue: 20, unit: 'dB', automatable: true },
      { id: 'makeup', name: 'Makeup Gain', type: 'float', defaultValue: 0, minValue: -12, maxValue: 24, unit: 'dB', automatable: true },
      { id: 'mix', name: 'Mix', type: 'float', defaultValue: 1.0, minValue: 0, maxValue: 1, automatable: true },
    ],
    defaultPreset: { threshold: -18, ratio: 4, attack: 3, release: 100, knee: 3, makeup: 0, mix: 1.0 },
  },
  {
    id: 'mb-optical-compressor',
    slug: 'mb-optical-compressor',
    name: 'MB Optical Compressor',
    category: 'effect',
    type: 'compressor',
    version: '1.0.0',
    description: 'Program-dependent optical compressor — smooth, musical gain riding inspired by LA-2A',
    author: 'Max Booster', grade: 'A',
    parameters: [
      { id: 'threshold', name: 'Threshold', type: 'float', defaultValue: -20, minValue: -60, maxValue: 0, unit: 'dB', automatable: true },
      { id: 'ratio', name: 'Ratio', type: 'float', defaultValue: 3, minValue: 1.5, maxValue: 10, automatable: true },
      { id: 'attack', name: 'Attack', type: 'float', defaultValue: 15, minValue: 5, maxValue: 100, unit: 'ms', automatable: true },
      { id: 'release', name: 'Release', type: 'float', defaultValue: 250, minValue: 50, maxValue: 2000, unit: 'ms', automatable: true },
      { id: 'programRelease', name: 'Program-Dependent Release', type: 'bool', defaultValue: true, automatable: false },
      { id: 'makeup', name: 'Makeup Gain', type: 'float', defaultValue: 0, minValue: -12, maxValue: 24, unit: 'dB', automatable: true },
      { id: 'mix', name: 'Mix', type: 'float', defaultValue: 1.0, minValue: 0, maxValue: 1, automatable: true },
    ],
    defaultPreset: { threshold: -20, ratio: 3, attack: 15, release: 250, programRelease: true, makeup: 0, mix: 1.0 },
  },
  {
    id: 'mb-fet-compressor',
    slug: 'mb-fet-compressor',
    name: 'MB FET Compressor',
    category: 'effect',
    type: 'compressor',
    version: '1.0.0',
    description: 'Aggressive FET compressor — adds grit and excitement, perfect for drums and bus',
    author: 'Max Booster', grade: 'A',
    parameters: [
      { id: 'threshold', name: 'Threshold', type: 'float', defaultValue: -20, minValue: -60, maxValue: 0, unit: 'dB', automatable: true },
      { id: 'ratio', name: 'Ratio', type: 'choice', defaultValue: '4:1', choices: ['2:1', '4:1', '8:1', '12:1', '20:1', 'Limit'], automatable: false },
      { id: 'attack', name: 'Attack', type: 'float', defaultValue: 1, minValue: 0.05, maxValue: 10, unit: 'ms', automatable: true },
      { id: 'release', name: 'Release', type: 'choice', defaultValue: 'auto', choices: ['50ms', '100ms', '200ms', '400ms', '800ms', 'auto'], automatable: false },
      { id: 'character', name: 'Character', type: 'float', defaultValue: 0.5, minValue: 0, maxValue: 1, automatable: true },
      { id: 'makeup', name: 'Makeup Gain', type: 'float', defaultValue: 0, minValue: -12, maxValue: 24, unit: 'dB', automatable: true },
      { id: 'mix', name: 'Mix', type: 'float', defaultValue: 1.0, minValue: 0, maxValue: 1, automatable: true },
    ],
    defaultPreset: { threshold: -20, ratio: '4:1', attack: 1, release: 'auto', character: 0.5, makeup: 0, mix: 1.0 },
  },
  {
    id: 'mb-tube-compressor',
    slug: 'mb-tube-compressor',
    name: 'MB Tube Compressor',
    category: 'effect',
    type: 'compressor',
    version: '1.0.0',
    description: 'Warm tube compressor — gentle saturation and harmonic richness, inspired by the Fairchild',
    author: 'Max Booster', grade: 'A',
    parameters: [
      { id: 'threshold', name: 'Threshold', type: 'float', defaultValue: -22, minValue: -60, maxValue: 0, unit: 'dB', automatable: true },
      { id: 'ratio', name: 'Ratio', type: 'float', defaultValue: 3, minValue: 1, maxValue: 10, automatable: true },
      { id: 'attack', name: 'Attack', type: 'float', defaultValue: 20, minValue: 5, maxValue: 200, unit: 'ms', automatable: true },
      { id: 'release', name: 'Release', type: 'float', defaultValue: 300, minValue: 50, maxValue: 3000, unit: 'ms', automatable: true },
      { id: 'tubeSaturation', name: 'Tube Saturation', type: 'float', defaultValue: 0.4, minValue: 0, maxValue: 1, automatable: true },
      { id: 'warmth', name: 'Warmth', type: 'float', defaultValue: 0.5, minValue: 0, maxValue: 1, automatable: true },
      { id: 'makeup', name: 'Makeup Gain', type: 'float', defaultValue: 0, minValue: -12, maxValue: 24, unit: 'dB', automatable: true },
      { id: 'mix', name: 'Mix', type: 'float', defaultValue: 1.0, minValue: 0, maxValue: 1, automatable: true },
    ],
    defaultPreset: { threshold: -22, ratio: 3, attack: 20, release: 300, tubeSaturation: 0.4, warmth: 0.5, makeup: 0, mix: 1.0 },
  },
  {
    id: 'mb-multiband-compressor',
    slug: 'mb-multiband-compressor',
    name: 'MB Multiband Compressor',
    category: 'effect',
    type: 'mastering',
    version: '1.0.0',
    description: '4-band multiband compressor for mastering and advanced mix shaping',
    author: 'Max Booster', grade: 'A',
    parameters: [
      { id: 'band1Threshold', name: 'Low Threshold', type: 'float', defaultValue: -18, minValue: -60, maxValue: 0, unit: 'dB', automatable: true },
      { id: 'band1Ratio', name: 'Low Ratio', type: 'float', defaultValue: 3, minValue: 1, maxValue: 20, automatable: true },
      { id: 'band1Attack', name: 'Low Attack', type: 'float', defaultValue: 20, minValue: 0.5, maxValue: 200, unit: 'ms', automatable: true },
      { id: 'band1Release', name: 'Low Release', type: 'float', defaultValue: 200, minValue: 20, maxValue: 2000, unit: 'ms', automatable: true },
      { id: 'band2Threshold', name: 'Low-Mid Threshold', type: 'float', defaultValue: -20, minValue: -60, maxValue: 0, unit: 'dB', automatable: true },
      { id: 'band2Ratio', name: 'Low-Mid Ratio', type: 'float', defaultValue: 4, minValue: 1, maxValue: 20, automatable: true },
      { id: 'band3Threshold', name: 'High-Mid Threshold', type: 'float', defaultValue: -22, minValue: -60, maxValue: 0, unit: 'dB', automatable: true },
      { id: 'band3Ratio', name: 'High-Mid Ratio', type: 'float', defaultValue: 4, minValue: 1, maxValue: 20, automatable: true },
      { id: 'band4Threshold', name: 'High Threshold', type: 'float', defaultValue: -24, minValue: -60, maxValue: 0, unit: 'dB', automatable: true },
      { id: 'band4Ratio', name: 'High Ratio', type: 'float', defaultValue: 5, minValue: 1, maxValue: 20, automatable: true },
      { id: 'crossover1', name: 'Crossover 1', type: 'float', defaultValue: 200, minValue: 40, maxValue: 500, unit: 'Hz', automatable: true },
      { id: 'crossover2', name: 'Crossover 2', type: 'float', defaultValue: 2000, minValue: 500, maxValue: 8000, unit: 'Hz', automatable: true },
      { id: 'crossover3', name: 'Crossover 3', type: 'float', defaultValue: 8000, minValue: 4000, maxValue: 18000, unit: 'Hz', automatable: true },
      { id: 'outputGain', name: 'Output Gain', type: 'float', defaultValue: 0, minValue: -12, maxValue: 12, unit: 'dB', automatable: true },
    ],
    defaultPreset: {
      band1Threshold: -18, band1Ratio: 3, band1Attack: 20, band1Release: 200,
      band2Threshold: -20, band2Ratio: 4,
      band3Threshold: -22, band3Ratio: 4,
      band4Threshold: -24, band4Ratio: 5,
      crossover1: 200, crossover2: 2000, crossover3: 8000, outputGain: 0,
    },
  },
  {
    id: 'mb-bus-compressor',
    slug: 'mb-bus-compressor',
    name: 'MB Bus Compressor',
    category: 'effect',
    type: 'compressor',
    version: '1.0.0',
    description: 'Smooth SSL-style bus compressor — glues the mix and adds punch',
    author: 'Max Booster', grade: 'A',
    parameters: [
      { id: 'threshold', name: 'Threshold', type: 'float', defaultValue: -15, minValue: -40, maxValue: 0, unit: 'dB', automatable: true },
      { id: 'ratio', name: 'Ratio', type: 'choice', defaultValue: '4:1', choices: ['2:1', '4:1', '10:1'], automatable: false },
      { id: 'attack', name: 'Attack', type: 'choice', defaultValue: '30ms', choices: ['0.1ms', '1ms', '3ms', '10ms', '30ms', '100ms', '300ms'], automatable: false },
      { id: 'release', name: 'Release', type: 'choice', defaultValue: '0.4s', choices: ['0.1s', '0.2s', '0.4s', '0.8s', '1.2s', 'auto'], automatable: false },
      { id: 'makeup', name: 'Makeup Gain', type: 'float', defaultValue: 0, minValue: -12, maxValue: 12, unit: 'dB', automatable: true },
      { id: 'stereoLink', name: 'Stereo Link', type: 'float', defaultValue: 1.0, minValue: 0, maxValue: 1, automatable: true },
      { id: 'mix', name: 'Mix', type: 'float', defaultValue: 1.0, minValue: 0, maxValue: 1, automatable: true },
    ],
    defaultPreset: { threshold: -15, ratio: '4:1', attack: '30ms', release: '0.4s', makeup: 0, stereoLink: 1.0, mix: 1.0 },
  },
  {
    id: 'mb-glue-compressor',
    slug: 'mb-glue-compressor',
    name: 'MB Glue Compressor',
    category: 'effect',
    type: 'compressor',
    version: '1.0.0',
    description: 'API-style glue compressor — adds cohesion and energy to group buses',
    author: 'Max Booster', grade: 'A',
    parameters: [
      { id: 'threshold', name: 'Threshold', type: 'float', defaultValue: -16, minValue: -40, maxValue: 0, unit: 'dB', automatable: true },
      { id: 'ratio', name: 'Ratio', type: 'float', defaultValue: 4, minValue: 1, maxValue: 10, automatable: true },
      { id: 'attack', name: 'Attack', type: 'float', defaultValue: 5, minValue: 0.1, maxValue: 100, unit: 'ms', automatable: true },
      { id: 'release', name: 'Release', type: 'float', defaultValue: 200, minValue: 10, maxValue: 1000, unit: 'ms', automatable: true },
      { id: 'glue', name: 'Glue Amount', type: 'float', defaultValue: 0.5, minValue: 0, maxValue: 1, automatable: true },
      { id: 'transient', name: 'Transient Preserve', type: 'float', defaultValue: 0.3, minValue: 0, maxValue: 1, automatable: true },
      { id: 'makeup', name: 'Makeup Gain', type: 'float', defaultValue: 0, minValue: -12, maxValue: 12, unit: 'dB', automatable: true },
      { id: 'mix', name: 'Mix', type: 'float', defaultValue: 1.0, minValue: 0, maxValue: 1, automatable: true },
    ],
    defaultPreset: { threshold: -16, ratio: 4, attack: 5, release: 200, glue: 0.5, transient: 0.3, makeup: 0, mix: 1.0 },
  },
  {
    id: 'mb-mastering-compressor',
    slug: 'mb-mastering-compressor',
    name: 'MB Mastering Compressor',
    category: 'effect',
    type: 'mastering',
    version: '1.0.0',
    description: 'Transparent mastering compressor with intelligent program detection',
    author: 'Max Booster', grade: 'A',
    parameters: [
      { id: 'threshold', name: 'Threshold', type: 'float', defaultValue: -12, minValue: -40, maxValue: 0, unit: 'dB', automatable: true },
      { id: 'ratio', name: 'Ratio', type: 'float', defaultValue: 2, minValue: 1, maxValue: 8, automatable: true },
      { id: 'attack', name: 'Attack', type: 'float', defaultValue: 30, minValue: 1, maxValue: 200, unit: 'ms', automatable: true },
      { id: 'release', name: 'Release', type: 'float', defaultValue: 300, minValue: 50, maxValue: 2000, unit: 'ms', automatable: true },
      { id: 'knee', name: 'Soft Knee', type: 'float', defaultValue: 12, minValue: 0, maxValue: 24, unit: 'dB', automatable: true },
      { id: 'style', name: 'Style', type: 'choice', defaultValue: 'transparent', choices: ['transparent', 'warm', 'punchy', 'vintage'], automatable: false },
      { id: 'makeup', name: 'Makeup Gain', type: 'float', defaultValue: 0, minValue: -12, maxValue: 12, unit: 'dB', automatable: true },
      { id: 'autoGain', name: 'Auto Gain', type: 'bool', defaultValue: true, automatable: false },
      { id: 'mix', name: 'Mix', type: 'float', defaultValue: 1.0, minValue: 0, maxValue: 1, automatable: true },
    ],
    defaultPreset: { threshold: -12, ratio: 2, attack: 30, release: 300, knee: 12, style: 'transparent', makeup: 0, autoGain: true, mix: 1.0 },
  },

  // ─── EQ VARIANTS (unlocked from DSP engine) ───────────────────────────────
  {
    id: 'mb-parametric-eq',
    slug: 'mb-parametric-eq',
    name: 'MB Parametric EQ',
    category: 'effect',
    type: 'eq',
    version: '2.0.0',
    description: '8-band fully parametric EQ with HP/LP filters — professional mastering precision',
    author: 'Max Booster', grade: 'A',
    parameters: [
      { id: 'hpEnabled', name: 'HP Filter', type: 'bool', defaultValue: false, automatable: false },
      { id: 'hpFreq', name: 'HP Frequency', type: 'float', defaultValue: 20, minValue: 20, maxValue: 1000, unit: 'Hz', automatable: true },
      { id: 'lpEnabled', name: 'LP Filter', type: 'bool', defaultValue: false, automatable: false },
      { id: 'lpFreq', name: 'LP Frequency', type: 'float', defaultValue: 20000, minValue: 1000, maxValue: 20000, unit: 'Hz', automatable: true },
      { id: 'band1Freq', name: 'Band 1 Freq', type: 'float', defaultValue: 80, minValue: 20, maxValue: 500, unit: 'Hz', automatable: true },
      { id: 'band1Gain', name: 'Band 1 Gain', type: 'float', defaultValue: 0, minValue: -24, maxValue: 24, unit: 'dB', automatable: true },
      { id: 'band1Q', name: 'Band 1 Q', type: 'float', defaultValue: 0.7, minValue: 0.1, maxValue: 10, automatable: true },
      { id: 'band2Freq', name: 'Band 2 Freq', type: 'float', defaultValue: 300, minValue: 50, maxValue: 2000, unit: 'Hz', automatable: true },
      { id: 'band2Gain', name: 'Band 2 Gain', type: 'float', defaultValue: 0, minValue: -24, maxValue: 24, unit: 'dB', automatable: true },
      { id: 'band2Q', name: 'Band 2 Q', type: 'float', defaultValue: 1.0, minValue: 0.1, maxValue: 10, automatable: true },
      { id: 'band3Freq', name: 'Band 3 Freq', type: 'float', defaultValue: 1000, minValue: 200, maxValue: 5000, unit: 'Hz', automatable: true },
      { id: 'band3Gain', name: 'Band 3 Gain', type: 'float', defaultValue: 0, minValue: -24, maxValue: 24, unit: 'dB', automatable: true },
      { id: 'band3Q', name: 'Band 3 Q', type: 'float', defaultValue: 1.0, minValue: 0.1, maxValue: 10, automatable: true },
      { id: 'band4Freq', name: 'Band 4 Freq', type: 'float', defaultValue: 4000, minValue: 1000, maxValue: 16000, unit: 'Hz', automatable: true },
      { id: 'band4Gain', name: 'Band 4 Gain', type: 'float', defaultValue: 0, minValue: -24, maxValue: 24, unit: 'dB', automatable: true },
      { id: 'band4Q', name: 'Band 4 Q', type: 'float', defaultValue: 1.0, minValue: 0.1, maxValue: 10, automatable: true },
      { id: 'output', name: 'Output Gain', type: 'float', defaultValue: 0, minValue: -12, maxValue: 12, unit: 'dB', automatable: true },
    ],
    defaultPreset: {
      hpEnabled: false, hpFreq: 20, lpEnabled: false, lpFreq: 20000,
      band1Freq: 80, band1Gain: 0, band1Q: 0.7,
      band2Freq: 300, band2Gain: 0, band2Q: 1.0,
      band3Freq: 1000, band3Gain: 0, band3Q: 1.0,
      band4Freq: 4000, band4Gain: 0, band4Q: 1.0,
      output: 0,
    },
  },
  {
    id: 'mb-dynamic-eq',
    slug: 'mb-dynamic-eq',
    name: 'MB Dynamic EQ',
    category: 'effect',
    type: 'eq',
    version: '1.0.0',
    description: '4-band dynamic EQ — frequency-specific compression or expansion with full band control',
    author: 'Max Booster', grade: 'A',
    parameters: [
      { id: 'band1Freq', name: 'Band 1 Freq', type: 'float', defaultValue: 150, minValue: 20, maxValue: 500, unit: 'Hz', automatable: true },
      { id: 'band1Gain', name: 'Band 1 Gain', type: 'float', defaultValue: 0, minValue: -18, maxValue: 18, unit: 'dB', automatable: true },
      { id: 'band1Q', name: 'Band 1 Q', type: 'float', defaultValue: 1.0, minValue: 0.1, maxValue: 10, automatable: true },
      { id: 'band1Threshold', name: 'Band 1 Threshold', type: 'float', defaultValue: -20, minValue: -60, maxValue: 0, unit: 'dB', automatable: true },
      { id: 'band1Ratio', name: 'Band 1 Ratio', type: 'float', defaultValue: 3, minValue: 1, maxValue: 10, automatable: true },
      { id: 'band2Freq', name: 'Band 2 Freq', type: 'float', defaultValue: 800, minValue: 200, maxValue: 3000, unit: 'Hz', automatable: true },
      { id: 'band2Gain', name: 'Band 2 Gain', type: 'float', defaultValue: 0, minValue: -18, maxValue: 18, unit: 'dB', automatable: true },
      { id: 'band2Q', name: 'Band 2 Q', type: 'float', defaultValue: 1.0, minValue: 0.1, maxValue: 10, automatable: true },
      { id: 'band2Threshold', name: 'Band 2 Threshold', type: 'float', defaultValue: -22, minValue: -60, maxValue: 0, unit: 'dB', automatable: true },
      { id: 'band2Ratio', name: 'Band 2 Ratio', type: 'float', defaultValue: 3, minValue: 1, maxValue: 10, automatable: true },
      { id: 'band3Freq', name: 'Band 3 Freq', type: 'float', defaultValue: 3500, minValue: 1000, maxValue: 10000, unit: 'Hz', automatable: true },
      { id: 'band3Gain', name: 'Band 3 Gain', type: 'float', defaultValue: 0, minValue: -18, maxValue: 18, unit: 'dB', automatable: true },
      { id: 'band3Threshold', name: 'Band 3 Threshold', type: 'float', defaultValue: -25, minValue: -60, maxValue: 0, unit: 'dB', automatable: true },
      { id: 'band3Ratio', name: 'Band 3 Ratio', type: 'float', defaultValue: 4, minValue: 1, maxValue: 10, automatable: true },
      { id: 'band4Freq', name: 'Band 4 Freq', type: 'float', defaultValue: 10000, minValue: 4000, maxValue: 20000, unit: 'Hz', automatable: true },
      { id: 'band4Gain', name: 'Band 4 Gain', type: 'float', defaultValue: 0, minValue: -18, maxValue: 18, unit: 'dB', automatable: true },
      { id: 'band4Threshold', name: 'Band 4 Threshold', type: 'float', defaultValue: -28, minValue: -60, maxValue: 0, unit: 'dB', automatable: true },
      { id: 'band4Ratio', name: 'Band 4 Ratio', type: 'float', defaultValue: 4, minValue: 1, maxValue: 10, automatable: true },
      { id: 'outputGain', name: 'Output Gain', type: 'float', defaultValue: 0, minValue: -12, maxValue: 12, unit: 'dB', automatable: true },
    ],
    defaultPreset: {
      band1Freq: 150, band1Gain: 0, band1Q: 1.0, band1Threshold: -20, band1Ratio: 3,
      band2Freq: 800, band2Gain: 0, band2Q: 1.0, band2Threshold: -22, band2Ratio: 3,
      band3Freq: 3500, band3Gain: 0, band3Threshold: -25, band3Ratio: 4,
      band4Freq: 10000, band4Gain: 0, band4Threshold: -28, band4Ratio: 4,
      outputGain: 0,
    },
  },
  {
    id: 'mb-mid-side-eq',
    slug: 'mb-mid-side-eq',
    name: 'MB Mid-Side EQ',
    category: 'effect',
    type: 'eq',
    version: '1.0.0',
    description: 'M/S parametric EQ — independent mid and side channel sculpting for mastering',
    author: 'Max Booster', grade: 'A',
    parameters: [
      { id: 'midLowFreq', name: 'Mid Low Freq', type: 'float', defaultValue: 100, minValue: 20, maxValue: 500, unit: 'Hz', automatable: true },
      { id: 'midLowGain', name: 'Mid Low Gain', type: 'float', defaultValue: 0, minValue: -18, maxValue: 18, unit: 'dB', automatable: true },
      { id: 'midMidFreq', name: 'Mid Mid Freq', type: 'float', defaultValue: 1000, minValue: 100, maxValue: 10000, unit: 'Hz', automatable: true },
      { id: 'midMidGain', name: 'Mid Mid Gain', type: 'float', defaultValue: 0, minValue: -18, maxValue: 18, unit: 'dB', automatable: true },
      { id: 'midMidQ', name: 'Mid Mid Q', type: 'float', defaultValue: 1.0, minValue: 0.1, maxValue: 10, automatable: true },
      { id: 'midHighFreq', name: 'Mid High Freq', type: 'float', defaultValue: 8000, minValue: 2000, maxValue: 20000, unit: 'Hz', automatable: true },
      { id: 'midHighGain', name: 'Mid High Gain', type: 'float', defaultValue: 0, minValue: -18, maxValue: 18, unit: 'dB', automatable: true },
      { id: 'sideLowFreq', name: 'Side Low Freq', type: 'float', defaultValue: 200, minValue: 20, maxValue: 1000, unit: 'Hz', automatable: true },
      { id: 'sideLowGain', name: 'Side Low Gain', type: 'float', defaultValue: 0, minValue: -18, maxValue: 18, unit: 'dB', automatable: true },
      { id: 'sideMidFreq', name: 'Side Mid Freq', type: 'float', defaultValue: 2000, minValue: 200, maxValue: 12000, unit: 'Hz', automatable: true },
      { id: 'sideMidGain', name: 'Side Mid Gain', type: 'float', defaultValue: 0, minValue: -18, maxValue: 18, unit: 'dB', automatable: true },
      { id: 'sideHighFreq', name: 'Side High Freq', type: 'float', defaultValue: 10000, minValue: 4000, maxValue: 20000, unit: 'Hz', automatable: true },
      { id: 'sideHighGain', name: 'Side High Gain', type: 'float', defaultValue: 0, minValue: -18, maxValue: 18, unit: 'dB', automatable: true },
      { id: 'midGain', name: 'Mid Level', type: 'float', defaultValue: 0, minValue: -12, maxValue: 12, unit: 'dB', automatable: true },
      { id: 'sideGain', name: 'Side Level', type: 'float', defaultValue: 0, minValue: -12, maxValue: 12, unit: 'dB', automatable: true },
    ],
    defaultPreset: {
      midLowFreq: 100, midLowGain: 0, midMidFreq: 1000, midMidGain: 0, midMidQ: 1.0,
      midHighFreq: 8000, midHighGain: 0,
      sideLowFreq: 200, sideLowGain: 0, sideMidFreq: 2000, sideMidGain: 0,
      sideHighFreq: 10000, sideHighGain: 0,
      midGain: 0, sideGain: 0,
    },
  },
  {
    id: 'mb-linear-phase-eq',
    slug: 'mb-linear-phase-eq',
    name: 'MB Linear Phase EQ',
    category: 'effect',
    type: 'mastering',
    version: '1.0.0',
    description: 'Linear-phase EQ with zero phase distortion — ideal for mastering bus and mid-side work',
    author: 'Max Booster', grade: 'A',
    parameters: [
      { id: 'hpFreq', name: 'HP Frequency', type: 'float', defaultValue: 20, minValue: 20, maxValue: 500, unit: 'Hz', automatable: true },
      { id: 'hpEnabled', name: 'HP Enabled', type: 'bool', defaultValue: false, automatable: false },
      { id: 'lpFreq', name: 'LP Frequency', type: 'float', defaultValue: 20000, minValue: 1000, maxValue: 20000, unit: 'Hz', automatable: true },
      { id: 'lpEnabled', name: 'LP Enabled', type: 'bool', defaultValue: false, automatable: false },
      { id: 'band1Freq', name: 'Band 1 Freq', type: 'float', defaultValue: 80, minValue: 20, maxValue: 400, unit: 'Hz', automatable: true },
      { id: 'band1Gain', name: 'Band 1 Gain', type: 'float', defaultValue: 0, minValue: -12, maxValue: 12, unit: 'dB', automatable: true },
      { id: 'band1Q', name: 'Band 1 Q', type: 'float', defaultValue: 0.7, minValue: 0.1, maxValue: 8, automatable: true },
      { id: 'band2Freq', name: 'Band 2 Freq', type: 'float', defaultValue: 500, minValue: 100, maxValue: 3000, unit: 'Hz', automatable: true },
      { id: 'band2Gain', name: 'Band 2 Gain', type: 'float', defaultValue: 0, minValue: -12, maxValue: 12, unit: 'dB', automatable: true },
      { id: 'band2Q', name: 'Band 2 Q', type: 'float', defaultValue: 1.0, minValue: 0.1, maxValue: 8, automatable: true },
      { id: 'band3Freq', name: 'Band 3 Freq', type: 'float', defaultValue: 3000, minValue: 500, maxValue: 12000, unit: 'Hz', automatable: true },
      { id: 'band3Gain', name: 'Band 3 Gain', type: 'float', defaultValue: 0, minValue: -12, maxValue: 12, unit: 'dB', automatable: true },
      { id: 'band3Q', name: 'Band 3 Q', type: 'float', defaultValue: 1.0, minValue: 0.1, maxValue: 8, automatable: true },
      { id: 'band4Freq', name: 'Band 4 Freq', type: 'float', defaultValue: 10000, minValue: 3000, maxValue: 20000, unit: 'Hz', automatable: true },
      { id: 'band4Gain', name: 'Band 4 Gain', type: 'float', defaultValue: 0, minValue: -12, maxValue: 12, unit: 'dB', automatable: true },
      { id: 'band4Q', name: 'Band 4 Q', type: 'float', defaultValue: 0.7, minValue: 0.1, maxValue: 8, automatable: true },
      { id: 'latencyMode', name: 'Latency Mode', type: 'choice', defaultValue: 'balanced', choices: ['low', 'balanced', 'high'], automatable: false },
      { id: 'output', name: 'Output Gain', type: 'float', defaultValue: 0, minValue: -12, maxValue: 12, unit: 'dB', automatable: true },
    ],
    defaultPreset: {
      hpFreq: 20, hpEnabled: false, lpFreq: 20000, lpEnabled: false,
      band1Freq: 80, band1Gain: 0, band1Q: 0.7,
      band2Freq: 500, band2Gain: 0, band2Q: 1.0,
      band3Freq: 3000, band3Gain: 0, band3Q: 1.0,
      band4Freq: 10000, band4Gain: 0, band4Q: 0.7,
      latencyMode: 'balanced', output: 0,
    },
  },

  // ─── DYNAMICS — standalone processors (unlocked from DSP engine) ──────────
  {
    id: 'mb-transient-shaper',
    slug: 'mb-transient-shaper',
    name: 'MB Transient Shaper',
    category: 'effect',
    type: 'transient-shaper',
    version: '1.0.0',
    description: 'Independent attack and sustain shaping — sculpt punch and tail without compression',
    author: 'Max Booster', grade: 'A',
    parameters: [
      { id: 'attack', name: 'Attack Gain', type: 'float', defaultValue: 0, minValue: -24, maxValue: 24, unit: 'dB', automatable: true },
      { id: 'attackSpeed', name: 'Attack Speed', type: 'float', defaultValue: 0.5, minValue: 0, maxValue: 1, automatable: true },
      { id: 'sustain', name: 'Sustain Gain', type: 'float', defaultValue: 0, minValue: -24, maxValue: 24, unit: 'dB', automatable: true },
      { id: 'sustainLength', name: 'Sustain Length', type: 'float', defaultValue: 0.5, minValue: 0, maxValue: 1, automatable: true },
      { id: 'sensitivity', name: 'Sensitivity', type: 'float', defaultValue: 0.5, minValue: 0, maxValue: 1, automatable: true },
      { id: 'outputGain', name: 'Output Gain', type: 'float', defaultValue: 0, minValue: -12, maxValue: 12, unit: 'dB', automatable: true },
      { id: 'mix', name: 'Mix', type: 'float', defaultValue: 1.0, minValue: 0, maxValue: 1, automatable: true },
    ],
    defaultPreset: { attack: 0, attackSpeed: 0.5, sustain: 0, sustainLength: 0.5, sensitivity: 0.5, outputGain: 0, mix: 1.0 },
  },
  {
    id: 'mb-de-esser',
    slug: 'mb-de-esser',
    name: 'MB De-Esser',
    category: 'effect',
    type: 'de-esser',
    version: '1.0.0',
    description: 'Frequency-selective de-esser for vocal sibilance control',
    author: 'Max Booster', grade: 'A',
    parameters: [
      { id: 'frequency', name: 'Detection Freq', type: 'float', defaultValue: 7000, minValue: 3000, maxValue: 16000, unit: 'Hz', automatable: true },
      { id: 'range', name: 'Reduction Range', type: 'float', defaultValue: -10, minValue: -30, maxValue: 0, unit: 'dB', automatable: true },
      { id: 'threshold', name: 'Threshold', type: 'float', defaultValue: -20, minValue: -50, maxValue: 0, unit: 'dB', automatable: true },
      { id: 'attack', name: 'Attack', type: 'float', defaultValue: 2, minValue: 0.1, maxValue: 20, unit: 'ms', automatable: true },
      { id: 'release', name: 'Release', type: 'float', defaultValue: 50, minValue: 10, maxValue: 500, unit: 'ms', automatable: true },
      { id: 'mode', name: 'Mode', type: 'choice', defaultValue: 'broadband', choices: ['broadband', 'split', 'dynamic'], automatable: false },
      { id: 'listen', name: 'Solo Listen', type: 'bool', defaultValue: false, automatable: false },
    ],
    defaultPreset: { frequency: 7000, range: -10, threshold: -20, attack: 2, release: 50, mode: 'broadband', listen: false },
  },
  {
    id: 'mb-maximizer',
    slug: 'mb-maximizer',
    name: 'MB Maximizer',
    category: 'effect',
    type: 'maximizer',
    version: '1.0.0',
    description: 'Loudness maximizer with intelligent peak limiting and LUFS targeting',
    author: 'Max Booster', grade: 'A',
    parameters: [
      { id: 'ceiling', name: 'Output Ceiling', type: 'float', defaultValue: -0.1, minValue: -6, maxValue: 0, unit: 'dB', automatable: true },
      { id: 'intensity', name: 'Intensity', type: 'float', defaultValue: 0.5, minValue: 0, maxValue: 1, automatable: true },
      { id: 'character', name: 'Character', type: 'choice', defaultValue: 'transparent', choices: ['transparent', 'punchy', 'warm', 'excite'], automatable: false },
      { id: 'attack', name: 'Attack', type: 'float', defaultValue: 3, minValue: 0.1, maxValue: 30, unit: 'ms', automatable: true },
      { id: 'release', name: 'Release', type: 'float', defaultValue: 150, minValue: 10, maxValue: 1000, unit: 'ms', automatable: true },
      { id: 'truePeak', name: 'True Peak', type: 'bool', defaultValue: true, automatable: false },
      { id: 'stereoLink', name: 'Stereo Link', type: 'float', defaultValue: 1.0, minValue: 0, maxValue: 1, automatable: true },
    ],
    defaultPreset: { ceiling: -0.1, intensity: 0.5, character: 'transparent', attack: 3, release: 150, truePeak: true, stereoLink: 1.0 },
  },
  {
    id: 'mb-leveler',
    slug: 'mb-leveler',
    name: 'MB Auto Leveler',
    category: 'effect',
    type: 'leveler',
    version: '1.0.0',
    description: 'Automatic gain rider for consistent loudness over long passages',
    author: 'Max Booster', grade: 'A',
    parameters: [
      { id: 'target', name: 'Target Level', type: 'float', defaultValue: -18, minValue: -40, maxValue: -6, unit: 'dBFS', automatable: false },
      { id: 'speed', name: 'Leveling Speed', type: 'float', defaultValue: 0.5, minValue: 0, maxValue: 1, automatable: true },
      { id: 'maxGain', name: 'Max Gain', type: 'float', defaultValue: 12, minValue: 0, maxValue: 24, unit: 'dB', automatable: true },
      { id: 'maxAttenuation', name: 'Max Attenuation', type: 'float', defaultValue: -24, minValue: -60, maxValue: 0, unit: 'dB', automatable: true },
      { id: 'noiseFloor', name: 'Noise Floor', type: 'float', defaultValue: -60, minValue: -80, maxValue: -40, unit: 'dB', automatable: true },
      { id: 'lookahead', name: 'Lookahead', type: 'float', defaultValue: 50, minValue: 0, maxValue: 500, unit: 'ms', automatable: false },
    ],
    defaultPreset: { target: -18, speed: 0.5, maxGain: 12, maxAttenuation: -24, noiseFloor: -60, lookahead: 50 },
  },
  {
    id: 'mb-expander',
    slug: 'mb-expander',
    name: 'MB Expander',
    category: 'effect',
    type: 'expander',
    version: '1.0.0',
    description: 'Downward expander — reduces low-level signals for noise reduction and punch',
    author: 'Max Booster', grade: 'A',
    parameters: [
      { id: 'threshold', name: 'Threshold', type: 'float', defaultValue: -40, minValue: -80, maxValue: 0, unit: 'dB', automatable: true },
      { id: 'ratio', name: 'Ratio', type: 'float', defaultValue: 2, minValue: 1, maxValue: 10, automatable: true },
      { id: 'attack', name: 'Attack', type: 'float', defaultValue: 5, minValue: 0.1, maxValue: 100, unit: 'ms', automatable: true },
      { id: 'release', name: 'Release', type: 'float', defaultValue: 200, minValue: 10, maxValue: 2000, unit: 'ms', automatable: true },
      { id: 'range', name: 'Range', type: 'float', defaultValue: -40, minValue: -80, maxValue: 0, unit: 'dB', automatable: true },
      { id: 'knee', name: 'Knee', type: 'float', defaultValue: 6, minValue: 0, maxValue: 20, unit: 'dB', automatable: true },
      { id: 'mix', name: 'Mix', type: 'float', defaultValue: 1.0, minValue: 0, maxValue: 1, automatable: true },
    ],
    defaultPreset: { threshold: -40, ratio: 2, attack: 5, release: 200, range: -40, knee: 6, mix: 1.0 },
  },
  {
    id: 'mb-limiter-pro',
    slug: 'mb-limiter-pro',
    name: 'MB Limiter Pro',
    category: 'effect',
    type: 'limiter',
    version: '2.0.0',
    description: 'Advanced true-peak limiter with 8 limiting algorithms and LUFS metering',
    author: 'Max Booster', grade: 'A',
    parameters: [
      { id: 'ceiling', name: 'Ceiling', type: 'float', defaultValue: -0.1, minValue: -6, maxValue: 0, unit: 'dBTP', automatable: true },
      { id: 'threshold', name: 'Threshold', type: 'float', defaultValue: -3, minValue: -20, maxValue: 0, unit: 'dB', automatable: true },
      { id: 'algorithm', name: 'Algorithm', type: 'choice', defaultValue: 'transparent', choices: ['transparent', 'dynamic', 'aggressive', 'bus', 'safe', 'modern', 'vintage', 'surgical'], automatable: false },
      { id: 'attack', name: 'Attack', type: 'float', defaultValue: 1, minValue: 0.05, maxValue: 50, unit: 'ms', automatable: true },
      { id: 'release', name: 'Release', type: 'float', defaultValue: 100, minValue: 10, maxValue: 1000, unit: 'ms', automatable: true },
      { id: 'lookahead', name: 'Lookahead', type: 'float', defaultValue: 5, minValue: 0, maxValue: 20, unit: 'ms', automatable: false },
      { id: 'truePeak', name: 'True Peak', type: 'bool', defaultValue: true, automatable: false },
      { id: 'stereoLink', name: 'Stereo Link', type: 'float', defaultValue: 1.0, minValue: 0, maxValue: 1, automatable: true },
      { id: 'oversampling', name: 'Oversampling', type: 'choice', defaultValue: '4x', choices: ['1x', '2x', '4x', '8x'], automatable: false },
    ],
    defaultPreset: { ceiling: -0.1, threshold: -3, algorithm: 'transparent', attack: 1, release: 100, lookahead: 5, truePeak: true, stereoLink: 1.0, oversampling: '4x' },
  },

  // ─── MODULATION EXTRAS (unlocked from DSP engine) ─────────────────────────
  {
    id: 'mb-tremolo',
    slug: 'mb-tremolo',
    name: 'MB Tremolo',
    category: 'effect',
    type: 'tremolo',
    version: '1.0.0',
    description: 'Amplitude tremolo with multiple LFO shapes and tempo sync',
    author: 'Max Booster', grade: 'A',
    parameters: [
      { id: 'rate', name: 'Rate', type: 'float', defaultValue: 4, minValue: 0.1, maxValue: 30, unit: 'Hz', automatable: true },
      { id: 'depth', name: 'Depth', type: 'float', defaultValue: 0.5, minValue: 0, maxValue: 1, automatable: true },
      { id: 'shape', name: 'LFO Shape', type: 'choice', defaultValue: 'sine', choices: ['sine', 'triangle', 'square', 'sawtooth', 'random'], automatable: false },
      { id: 'tempoSync', name: 'Tempo Sync', type: 'bool', defaultValue: false, automatable: false },
      { id: 'syncDivision', name: 'Sync Division', type: 'choice', defaultValue: '1/4', choices: ['1/16', '1/8', '1/4', '1/2', '1/1'], automatable: false },
      { id: 'stereoPhase', name: 'Stereo Phase', type: 'float', defaultValue: 0, minValue: 0, maxValue: 1, automatable: true },
      { id: 'mix', name: 'Mix', type: 'float', defaultValue: 1.0, minValue: 0, maxValue: 1, automatable: true },
    ],
    defaultPreset: { rate: 4, depth: 0.5, shape: 'sine', tempoSync: false, syncDivision: '1/4', stereoPhase: 0, mix: 1.0 },
  },
  {
    id: 'mb-vibrato',
    slug: 'mb-vibrato',
    name: 'MB Vibrato',
    category: 'effect',
    type: 'vibrato',
    version: '1.0.0',
    description: 'Pitch vibrato with expression-curve LFO and MIDI CC control',
    author: 'Max Booster', grade: 'A',
    parameters: [
      { id: 'rate', name: 'Rate', type: 'float', defaultValue: 5, minValue: 0.1, maxValue: 20, unit: 'Hz', automatable: true },
      { id: 'depth', name: 'Depth', type: 'float', defaultValue: 0.5, minValue: 0, maxValue: 1, automatable: true },
      { id: 'shape', name: 'LFO Shape', type: 'choice', defaultValue: 'sine', choices: ['sine', 'triangle', 'random'], automatable: false },
      { id: 'delay', name: 'Onset Delay', type: 'float', defaultValue: 0, minValue: 0, maxValue: 2, unit: 's', automatable: true },
      { id: 'tempoSync', name: 'Tempo Sync', type: 'bool', defaultValue: false, automatable: false },
    ],
    defaultPreset: { rate: 5, depth: 0.5, shape: 'sine', delay: 0, tempoSync: false },
  },
      { id: 'mb-ring-mod', slug: 'mb-ring-mod', name: 'MB Ring Modulator', category: 'effect', type: 'ring-mod', version: '2.0.0', description: 'Carrier-frequency ring modulation for metallic and robotic tones', author: 'Max Booster', grade: 'A', parameters: [{ id: 'frequency', name: 'Carrier Freq', type: 'float', defaultValue: 100, minValue: 1, maxValue: 5000, unit: 'Hz', automatable: true }, { id: 'depth', name: 'Modulation Depth', type: 'float', defaultValue: 1.0, minValue: 0, maxValue: 1, automatable: true }, { id: 'shape', name: 'Carrier Shape', type: 'choice', defaultValue: 'sine', choices: ['sine','triangle','square','sawtooth','random'], automatable: false }, { id: 'sideband', name: 'Sideband', type: 'choice', defaultValue: 'both', choices: ['both','upper','lower'], automatable: false }, { id: 'fine', name: 'Fine Tune', type: 'float', defaultValue: 0, minValue: -50, maxValue: 50, unit: 'ct', automatable: true }, { id: 'lfo_rate', name: 'LFO Modulation', type: 'float', defaultValue: 0, minValue: 0, maxValue: 10, unit: 'Hz', automatable: true }, { id: 'mix', name: 'Mix', type: 'float', defaultValue: 0.5, minValue: 0, maxValue: 1, automatable: true }], defaultPreset: { frequency: 100, depth: 1.0, shape: 'sine', sideband: 'both', fine: 0, lfo_rate: 0, mix: 0.5 } },
  {
    id: 'mb-rotary',
    slug: 'mb-rotary',
    name: 'MB Rotary Speaker',
    category: 'effect',
    type: 'rotary',
    version: '1.0.0',
    description: 'Leslie cabinet simulation — spinning speaker Doppler with fast/slow horn speeds',
    author: 'Max Booster', grade: 'A',
    parameters: [
      { id: 'speed', name: 'Speed', type: 'choice', defaultValue: 'slow', choices: ['stop', 'slow', 'fast'], automatable: true },
      { id: 'acceleration', name: 'Acceleration', type: 'float', defaultValue: 0.5, minValue: 0, maxValue: 1, automatable: true },
      { id: 'hornLevel', name: 'Horn Level', type: 'float', defaultValue: 0.7, minValue: 0, maxValue: 1, automatable: true },
      { id: 'drumLevel', name: 'Drum Level', type: 'float', defaultValue: 0.5, minValue: 0, maxValue: 1, automatable: true },
      { id: 'slowRate', name: 'Slow Rate', type: 'float', defaultValue: 0.8, minValue: 0.1, maxValue: 3, unit: 'Hz', automatable: true },
      { id: 'fastRate', name: 'Fast Rate', type: 'float', defaultValue: 7, minValue: 3, maxValue: 15, unit: 'Hz', automatable: true },
      { id: 'spread', name: 'Stereo Spread', type: 'float', defaultValue: 0.8, minValue: 0, maxValue: 1, automatable: true },
      { id: 'mix', name: 'Mix', type: 'float', defaultValue: 1.0, minValue: 0, maxValue: 1, automatable: true },
    ],
    defaultPreset: { speed: 'slow', acceleration: 0.5, hornLevel: 0.7, drumLevel: 0.5, slowRate: 0.8, fastRate: 7, spread: 0.8, mix: 1.0 },
  },
      { id: 'mb-auto-pan', slug: 'mb-auto-pan', name: 'MB Auto Pan', category: 'effect', type: 'auto-pan', version: '2.0.0', description: 'LFO auto-panning with stereo widening, shape and output control', author: 'Max Booster', grade: 'A', parameters: [{ id: 'rate', name: 'Rate', type: 'float', defaultValue: 1.0, minValue: 0.01, maxValue: 20, unit: 'Hz', automatable: true }, { id: 'depth', name: 'Depth', type: 'float', defaultValue: 0.8, minValue: 0, maxValue: 1, automatable: true }, { id: 'shape', name: 'LFO Shape', type: 'choice', defaultValue: 'sine', choices: ['sine','triangle','square','sawtooth','random'], automatable: false }, { id: 'width', name: 'Width', type: 'float', defaultValue: 1.0, minValue: 0, maxValue: 1, automatable: true }, { id: 'sync', name: 'Tempo Sync', type: 'bool', defaultValue: false, automatable: false }, { id: 'phase', name: 'Initial Phase', type: 'float', defaultValue: 0, minValue: 0, maxValue: 1, automatable: true }, { id: 'output', name: 'Output', type: 'float', defaultValue: 0, minValue: -12, maxValue: 12, unit: 'dB', automatable: true }], defaultPreset: { rate: 1.0, depth: 0.8, shape: 'sine', width: 1.0, sync: false, phase: 0, output: 0 } },
    { id: 'mb-ensemble', slug: 'mb-ensemble', name: 'MB Ensemble', category: 'effect', type: 'ensemble', version: '2.0.0', description: 'Unison ensemble with pitch scatter — Roland Juno class', author: 'Max Booster', grade: 'A', parameters: [{ id: 'rate', name: 'Rate', type: 'float', defaultValue: 0.5, minValue: 0.01, maxValue: 10, unit: 'Hz', automatable: true }, { id: 'depth', name: 'Depth', type: 'float', defaultValue: 0.4, minValue: 0, maxValue: 1, automatable: true }, { id: 'delay', name: 'Delay Time', type: 'float', defaultValue: 25, minValue: 1, maxValue: 50, unit: 'ms', automatable: true }, { id: 'feedback', name: 'Feedback', type: 'float', defaultValue: 0.2, minValue: -0.95, maxValue: 0.95, automatable: true }, { id: 'shape', name: 'LFO Shape', type: 'choice', defaultValue: 'sine', choices: ['sine','triangle','square','sawtooth','random'], automatable: false }, { id: 'width', name: 'Stereo Width', type: 'float', defaultValue: 1.0, minValue: 0, maxValue: 1, automatable: true }, { id: 'mix', name: 'Mix', type: 'float', defaultValue: 0.5, minValue: 0, maxValue: 1, automatable: true }], defaultPreset: { rate: 0.5, depth: 0.4, delay: 25, feedback: 0.2, shape: 'sine', width: 1.0, mix: 0.5 } },
];

export const EXPANDED_INSTRUMENTS: PluginDefinition[] = BUILT_IN_INSTRUMENTS;
export const EXPANDED_EFFECTS: PluginDefinition[] = BUILT_IN_EFFECTS;
export const ALL_PLUGINS: PluginDefinition[] = [...BUILT_IN_INSTRUMENTS, ...BUILT_IN_EFFECTS];
