import type { PluginDefinition } from '../pluginHostService';

export const ADDITIONAL_SYNTH_PLUGINS: PluginDefinition[] = [
  {
    id: 'mb-analog-polysynth',
    slug: 'mb-analog-polysynth',
    name: 'MB Analog Poly',
    category: 'instrument',
    type: 'analog',
    version: '1.0.0',
    description: 'Classic analog polyphonic synthesizer with fat oscillators and resonant filters',
    author: 'Max Booster',
    oscillators: [
      { type: 'sawtooth', detune: -7, gain: 0.4 },
      { type: 'sawtooth', detune: 7, gain: 0.4 },
      { type: 'square', detune: 0, gain: 0.2 },
    ],
    envelope: { attack: 0.01, decay: 0.3, sustain: 0.7, release: 0.3 },
    parameters: [
      { id: 'osc1_shape', name: 'Osc 1 Shape', type: 'float', defaultValue: 0.5, minValue: 0, maxValue: 1, automatable: true },
      { id: 'osc2_shape', name: 'Osc 2 Shape', type: 'float', defaultValue: 0.5, minValue: 0, maxValue: 1, automatable: true },
      { id: 'osc_mix', name: 'Oscillator Mix', type: 'float', defaultValue: 0.5, minValue: 0, maxValue: 1, automatable: true },
      { id: 'filter_cutoff', name: 'Filter Cutoff', type: 'float', defaultValue: 8000, minValue: 20, maxValue: 20000, unit: 'Hz', automatable: true },
      { id: 'filter_res', name: 'Filter Resonance', type: 'float', defaultValue: 0.3, minValue: 0, maxValue: 1, automatable: true },
      { id: 'filter_env', name: 'Filter Envelope', type: 'float', defaultValue: 0.5, minValue: 0, maxValue: 1, automatable: true },
      { id: 'lfo_rate', name: 'LFO Rate', type: 'float', defaultValue: 2, minValue: 0.1, maxValue: 20, unit: 'Hz', automatable: true },
      { id: 'lfo_depth', name: 'LFO Depth', type: 'float', defaultValue: 0.2, minValue: 0, maxValue: 1, automatable: true },
      { id: 'unison', name: 'Unison Voices', type: 'int', defaultValue: 1, minValue: 1, maxValue: 8, automatable: false },
      { id: 'detune', name: 'Unison Detune', type: 'float', defaultValue: 10, minValue: 0, maxValue: 50, unit: 'cents', automatable: true },
      { id: 'volume', name: 'Volume', type: 'float', defaultValue: 0.8, minValue: 0, maxValue: 1, automatable: true },
    ],
    defaultPreset: { osc1_shape: 0.5, osc2_shape: 0.5, osc_mix: 0.5, filter_cutoff: 8000, filter_res: 0.3, filter_env: 0.5, lfo_rate: 2, lfo_depth: 0.2, unison: 1, detune: 10, volume: 0.8 },
  },
  {
    id: 'mb-supersaw-lead',
    slug: 'mb-supersaw-lead',
    name: 'MB Supersaw Lead',
    category: 'instrument',
    type: 'synth',
    version: '1.0.0',
    description: 'Massive supersaw lead synth for EDM and trance productions',
    author: 'Max Booster',
    oscillators: [
      { type: 'sawtooth', detune: -25, gain: 0.15 },
      { type: 'sawtooth', detune: -15, gain: 0.2 },
      { type: 'sawtooth', detune: -5, gain: 0.25 },
      { type: 'sawtooth', detune: 0, gain: 0.3 },
      { type: 'sawtooth', detune: 5, gain: 0.25 },
      { type: 'sawtooth', detune: 15, gain: 0.2 },
      { type: 'sawtooth', detune: 25, gain: 0.15 },
    ],
    envelope: { attack: 0.01, decay: 0.2, sustain: 0.8, release: 0.4 },
    parameters: [
      { id: 'voices', name: 'Supersaw Voices', type: 'int', defaultValue: 7, minValue: 3, maxValue: 16, automatable: false },
      { id: 'detune', name: 'Supersaw Detune', type: 'float', defaultValue: 25, minValue: 0, maxValue: 100, unit: 'cents', automatable: true },
      { id: 'filter_cutoff', name: 'Filter Cutoff', type: 'float', defaultValue: 12000, minValue: 100, maxValue: 20000, unit: 'Hz', automatable: true },
      { id: 'filter_res', name: 'Filter Resonance', type: 'float', defaultValue: 0.2, minValue: 0, maxValue: 1, automatable: true },
      { id: 'stereo_width', name: 'Stereo Width', type: 'float', defaultValue: 0.8, minValue: 0, maxValue: 1, automatable: true },
      { id: 'attack', name: 'Attack', type: 'float', defaultValue: 0.01, minValue: 0.001, maxValue: 2, unit: 's', automatable: true },
      { id: 'release', name: 'Release', type: 'float', defaultValue: 0.4, minValue: 0.01, maxValue: 5, unit: 's', automatable: true },
      { id: 'volume', name: 'Volume', type: 'float', defaultValue: 0.8, minValue: 0, maxValue: 1, automatable: true },
    ],
    defaultPreset: { voices: 7, detune: 25, filter_cutoff: 12000, filter_res: 0.2, stereo_width: 0.8, attack: 0.01, release: 0.4, volume: 0.8 },
  },
  {
    id: 'mb-acid-bass',
    slug: 'mb-acid-bass',
    name: 'MB Acid Bass',
    category: 'instrument',
    type: 'synth',
    version: '1.0.0',
    description: 'Classic 303-style acid bass synthesizer with squelchy filter',
    author: 'Max Booster',
    oscillators: [
      { type: 'sawtooth', detune: 0, gain: 0.7 },
      { type: 'square', detune: 0, gain: 0.3 },
    ],
    envelope: { attack: 0.001, decay: 0.2, sustain: 0, release: 0.1 },
    parameters: [
      { id: 'waveform', name: 'Waveform', type: 'choice', defaultValue: 'sawtooth', choices: ['sawtooth', 'square'], automatable: false },
      { id: 'cutoff', name: 'Filter Cutoff', type: 'float', defaultValue: 400, minValue: 50, maxValue: 5000, unit: 'Hz', automatable: true },
      { id: 'resonance', name: 'Resonance', type: 'float', defaultValue: 0.8, minValue: 0, maxValue: 1, automatable: true },
      { id: 'env_mod', name: 'Envelope Mod', type: 'float', defaultValue: 0.7, minValue: 0, maxValue: 1, automatable: true },
      { id: 'decay', name: 'Decay', type: 'float', defaultValue: 0.2, minValue: 0.01, maxValue: 2, unit: 's', automatable: true },
      { id: 'accent', name: 'Accent', type: 'float', defaultValue: 0.5, minValue: 0, maxValue: 1, automatable: true },
      { id: 'slide', name: 'Slide Time', type: 'float', defaultValue: 0.05, minValue: 0, maxValue: 0.5, unit: 's', automatable: true },
      { id: 'distortion', name: 'Distortion', type: 'float', defaultValue: 0.2, minValue: 0, maxValue: 1, automatable: true },
      { id: 'volume', name: 'Volume', type: 'float', defaultValue: 0.8, minValue: 0, maxValue: 1, automatable: true },
    ],
    defaultPreset: { waveform: 'sawtooth', cutoff: 400, resonance: 0.8, env_mod: 0.7, decay: 0.2, accent: 0.5, slide: 0.05, distortion: 0.2, volume: 0.8 },
  },
  {
    id: 'mb-fm-electric-piano',
    slug: 'mb-fm-electric-piano',
    name: 'MB FM Electric Piano',
    category: 'instrument',
    type: 'fm',
    version: '1.0.0',
    description: 'Classic DX7-style FM electric piano with warm tines and bells',
    author: 'Max Booster',
    oscillators: [
      { type: 'sine', detune: 0, gain: 0.5 },
      { type: 'sine', detune: 0, gain: 0.3 },
      { type: 'sine', detune: 0, gain: 0.2 },
    ],
    envelope: { attack: 0.001, decay: 2.0, sustain: 0.2, release: 0.5 },
    parameters: [
      { id: 'algorithm', name: 'Algorithm', type: 'int', defaultValue: 1, minValue: 1, maxValue: 32, automatable: false },
      { id: 'mod_index', name: 'Modulation Index', type: 'float', defaultValue: 2.5, minValue: 0, maxValue: 10, automatable: true },
      { id: 'ratio', name: 'Operator Ratio', type: 'float', defaultValue: 14, minValue: 0.5, maxValue: 32, automatable: true },
      { id: 'brightness', name: 'Brightness', type: 'float', defaultValue: 0.6, minValue: 0, maxValue: 1, automatable: true },
      { id: 'decay', name: 'Decay', type: 'float', defaultValue: 2.0, minValue: 0.1, maxValue: 10, unit: 's', automatable: true },
      { id: 'velocity_sens', name: 'Velocity Sensitivity', type: 'float', defaultValue: 0.7, minValue: 0, maxValue: 1, automatable: false },
      { id: 'tremolo_rate', name: 'Tremolo Rate', type: 'float', defaultValue: 5, minValue: 0, maxValue: 20, unit: 'Hz', automatable: true },
      { id: 'tremolo_depth', name: 'Tremolo Depth', type: 'float', defaultValue: 0.3, minValue: 0, maxValue: 1, automatable: true },
      { id: 'volume', name: 'Volume', type: 'float', defaultValue: 0.8, minValue: 0, maxValue: 1, automatable: true },
    ],
    defaultPreset: { algorithm: 1, mod_index: 2.5, ratio: 14, brightness: 0.6, decay: 2.0, velocity_sens: 0.7, tremolo_rate: 5, tremolo_depth: 0.3, volume: 0.8 },
  },
  {
    id: 'mb-granular-synth',
    slug: 'mb-granular-synth',
    name: 'MB Granular Synth',
    category: 'instrument',
    type: 'wavetable',
    version: '1.0.0',
    description: 'Advanced granular synthesizer for textural and ambient sounds',
    author: 'Max Booster',
    oscillators: [
      { type: 'sine', detune: 0, gain: 0.5 },
      { type: 'triangle', detune: 0, gain: 0.3 },
    ],
    envelope: { attack: 0.5, decay: 1.0, sustain: 0.7, release: 2.0 },
    parameters: [
      { id: 'grain_size', name: 'Grain Size', type: 'float', defaultValue: 50, minValue: 1, maxValue: 500, unit: 'ms', automatable: true },
      { id: 'grain_density', name: 'Grain Density', type: 'float', defaultValue: 20, minValue: 1, maxValue: 100, unit: 'grains/s', automatable: true },
      { id: 'position', name: 'Sample Position', type: 'float', defaultValue: 0, minValue: 0, maxValue: 1, automatable: true },
      { id: 'position_spread', name: 'Position Spread', type: 'float', defaultValue: 0.1, minValue: 0, maxValue: 1, automatable: true },
      { id: 'pitch_spread', name: 'Pitch Spread', type: 'float', defaultValue: 0, minValue: -24, maxValue: 24, unit: 'semitones', automatable: true },
      { id: 'pan_spread', name: 'Pan Spread', type: 'float', defaultValue: 0.5, minValue: 0, maxValue: 1, automatable: true },
      { id: 'reverse', name: 'Reverse Probability', type: 'float', defaultValue: 0, minValue: 0, maxValue: 1, automatable: true },
      { id: 'freeze', name: 'Freeze', type: 'bool', defaultValue: false, automatable: true },
      { id: 'volume', name: 'Volume', type: 'float', defaultValue: 0.8, minValue: 0, maxValue: 1, automatable: true },
    ],
    defaultPreset: { grain_size: 50, grain_density: 20, position: 0, position_spread: 0.1, pitch_spread: 0, pan_spread: 0.5, reverse: 0, freeze: false, volume: 0.8 },
  },
  {
    id: 'mb-organ',
    slug: 'mb-organ',
    name: 'MB Tonewheel Organ',
    category: 'instrument',
    type: 'synth',
    version: '1.0.0',
    description: 'Classic tonewheel organ with drawbars and rotary speaker simulation',
    author: 'Max Booster',
    oscillators: [
      { type: 'sine', detune: -1200, gain: 0 },
      { type: 'sine', detune: -700, gain: 0 },
      { type: 'sine', detune: 0, gain: 0.8 },
      { type: 'sine', detune: 1200, gain: 0.6 },
      { type: 'sine', detune: 1900, gain: 0.4 },
      { type: 'sine', detune: 2400, gain: 0.3 },
      { type: 'sine', detune: 2800, gain: 0.2 },
      { type: 'sine', detune: 3100, gain: 0.1 },
      { type: 'sine', detune: 3600, gain: 0.05 },
    ],
    envelope: { attack: 0.005, decay: 0, sustain: 1, release: 0.1 },
    parameters: [
      { id: 'drawbar_16', name: '16\' Drawbar', type: 'int', defaultValue: 0, minValue: 0, maxValue: 8, automatable: true },
      { id: 'drawbar_513', name: '5 1/3\' Drawbar', type: 'int', defaultValue: 0, minValue: 0, maxValue: 8, automatable: true },
      { id: 'drawbar_8', name: '8\' Drawbar', type: 'int', defaultValue: 8, minValue: 0, maxValue: 8, automatable: true },
      { id: 'drawbar_4', name: '4\' Drawbar', type: 'int', defaultValue: 6, minValue: 0, maxValue: 8, automatable: true },
      { id: 'drawbar_223', name: '2 2/3\' Drawbar', type: 'int', defaultValue: 4, minValue: 0, maxValue: 8, automatable: true },
      { id: 'drawbar_2', name: '2\' Drawbar', type: 'int', defaultValue: 3, minValue: 0, maxValue: 8, automatable: true },
      { id: 'percussion', name: 'Percussion', type: 'bool', defaultValue: true, automatable: false },
      { id: 'leslie_speed', name: 'Leslie Speed', type: 'choice', defaultValue: 'slow', choices: ['stop', 'slow', 'fast'], automatable: true },
      { id: 'leslie_depth', name: 'Leslie Depth', type: 'float', defaultValue: 0.5, minValue: 0, maxValue: 1, automatable: true },
      { id: 'overdrive', name: 'Overdrive', type: 'float', defaultValue: 0.3, minValue: 0, maxValue: 1, automatable: true },
      { id: 'volume', name: 'Volume', type: 'float', defaultValue: 0.8, minValue: 0, maxValue: 1, automatable: true },
    ],
    defaultPreset: { drawbar_16: 0, drawbar_513: 0, drawbar_8: 8, drawbar_4: 6, drawbar_223: 4, drawbar_2: 3, percussion: true, leslie_speed: 'slow', leslie_depth: 0.5, overdrive: 0.3, volume: 0.8 },
  },
];

export const ADDITIONAL_EFFECT_PLUGINS: PluginDefinition[] = [
  {
    id: 'mb-multiband-compressor',
    slug: 'mb-multiband-compressor',
    name: 'MB Multiband Compressor',
    category: 'effect',
    type: 'compressor',
    version: '1.0.0',
    description: 'Professional 4-band dynamics processor for mixing and mastering',
    author: 'Max Booster',
    parameters: [
      { id: 'crossover_low', name: 'Low Crossover', type: 'float', defaultValue: 100, minValue: 20, maxValue: 500, unit: 'Hz', automatable: true },
      { id: 'crossover_mid', name: 'Mid Crossover', type: 'float', defaultValue: 1000, minValue: 200, maxValue: 5000, unit: 'Hz', automatable: true },
      { id: 'crossover_high', name: 'High Crossover', type: 'float', defaultValue: 8000, minValue: 2000, maxValue: 16000, unit: 'Hz', automatable: true },
      { id: 'low_threshold', name: 'Low Threshold', type: 'float', defaultValue: -20, minValue: -60, maxValue: 0, unit: 'dB', automatable: true },
      { id: 'low_ratio', name: 'Low Ratio', type: 'float', defaultValue: 4, minValue: 1, maxValue: 20, automatable: true },
      { id: 'mid_threshold', name: 'Mid Threshold', type: 'float', defaultValue: -18, minValue: -60, maxValue: 0, unit: 'dB', automatable: true },
      { id: 'mid_ratio', name: 'Mid Ratio', type: 'float', defaultValue: 3, minValue: 1, maxValue: 20, automatable: true },
      { id: 'high_threshold', name: 'High Threshold', type: 'float', defaultValue: -15, minValue: -60, maxValue: 0, unit: 'dB', automatable: true },
      { id: 'high_ratio', name: 'High Ratio', type: 'float', defaultValue: 2, minValue: 1, maxValue: 20, automatable: true },
      { id: 'output', name: 'Output Gain', type: 'float', defaultValue: 0, minValue: -12, maxValue: 12, unit: 'dB', automatable: true },
    ],
    defaultPreset: { crossover_low: 100, crossover_mid: 1000, crossover_high: 8000, low_threshold: -20, low_ratio: 4, mid_threshold: -18, mid_ratio: 3, high_threshold: -15, high_ratio: 2, output: 0 },
  },
  {
    id: 'mb-tape-saturation',
    slug: 'mb-tape-saturation',
    name: 'MB Tape Saturation',
    category: 'effect',
    type: 'distortion',
    version: '1.0.0',
    description: 'Warm analog tape emulation with compression and harmonics',
    author: 'Max Booster',
    parameters: [
      { id: 'input_gain', name: 'Input Gain', type: 'float', defaultValue: 0, minValue: -12, maxValue: 24, unit: 'dB', automatable: true },
      { id: 'saturation', name: 'Saturation', type: 'float', defaultValue: 0.5, minValue: 0, maxValue: 1, automatable: true },
      { id: 'tape_speed', name: 'Tape Speed', type: 'choice', defaultValue: '15ips', choices: ['7.5ips', '15ips', '30ips'], automatable: false },
      { id: 'bias', name: 'Bias', type: 'float', defaultValue: 0.5, minValue: 0, maxValue: 1, automatable: true },
      { id: 'wow_flutter', name: 'Wow & Flutter', type: 'float', defaultValue: 0.1, minValue: 0, maxValue: 1, automatable: true },
      { id: 'noise', name: 'Tape Noise', type: 'float', defaultValue: 0, minValue: 0, maxValue: 1, automatable: true },
      { id: 'output_gain', name: 'Output Gain', type: 'float', defaultValue: 0, minValue: -12, maxValue: 12, unit: 'dB', automatable: true },
      { id: 'mix', name: 'Mix', type: 'float', defaultValue: 1, minValue: 0, maxValue: 1, automatable: true },
    ],
    defaultPreset: { input_gain: 0, saturation: 0.5, tape_speed: '15ips', bias: 0.5, wow_flutter: 0.1, noise: 0, output_gain: 0, mix: 1 },
  },
  {
    id: 'mb-stereo-imager',
    slug: 'mb-stereo-imager',
    name: 'MB Stereo Imager',
    category: 'effect',
    type: 'eq',
    version: '1.0.0',
    description: 'Multiband stereo width processor for spatial enhancement',
    author: 'Max Booster',
    parameters: [
      { id: 'low_width', name: 'Low Width', type: 'float', defaultValue: 0.5, minValue: 0, maxValue: 2, automatable: true },
      { id: 'mid_width', name: 'Mid Width', type: 'float', defaultValue: 1, minValue: 0, maxValue: 2, automatable: true },
      { id: 'high_width', name: 'High Width', type: 'float', defaultValue: 1.5, minValue: 0, maxValue: 2, automatable: true },
      { id: 'crossover_low', name: 'Low Crossover', type: 'float', defaultValue: 200, minValue: 50, maxValue: 500, unit: 'Hz', automatable: true },
      { id: 'crossover_high', name: 'High Crossover', type: 'float', defaultValue: 5000, minValue: 1000, maxValue: 15000, unit: 'Hz', automatable: true },
      { id: 'correlation', name: 'Correlation', type: 'bool', defaultValue: true, automatable: false },
      { id: 'mono_below', name: 'Mono Below', type: 'float', defaultValue: 80, minValue: 0, maxValue: 300, unit: 'Hz', automatable: true },
    ],
    defaultPreset: { low_width: 0.5, mid_width: 1, high_width: 1.5, crossover_low: 200, crossover_high: 5000, correlation: true, mono_below: 80 },
  },
  {
    id: 'mb-transient-shaper',
    slug: 'mb-transient-shaper',
    name: 'MB Transient Shaper',
    category: 'effect',
    type: 'compressor',
    version: '1.0.0',
    description: 'Attack and sustain control for drums and percussive sounds',
    author: 'Max Booster',
    parameters: [
      { id: 'attack', name: 'Attack', type: 'float', defaultValue: 0, minValue: -100, maxValue: 100, unit: '%', automatable: true },
      { id: 'sustain', name: 'Sustain', type: 'float', defaultValue: 0, minValue: -100, maxValue: 100, unit: '%', automatable: true },
      { id: 'attack_time', name: 'Attack Time', type: 'float', defaultValue: 5, minValue: 0.1, maxValue: 50, unit: 'ms', automatable: true },
      { id: 'sustain_time', name: 'Sustain Time', type: 'float', defaultValue: 100, minValue: 10, maxValue: 500, unit: 'ms', automatable: true },
      { id: 'sensitivity', name: 'Sensitivity', type: 'float', defaultValue: 0.5, minValue: 0, maxValue: 1, automatable: true },
      { id: 'output', name: 'Output', type: 'float', defaultValue: 0, minValue: -12, maxValue: 12, unit: 'dB', automatable: true },
      { id: 'mix', name: 'Mix', type: 'float', defaultValue: 1, minValue: 0, maxValue: 1, automatable: true },
    ],
    defaultPreset: { attack: 0, sustain: 0, attack_time: 5, sustain_time: 100, sensitivity: 0.5, output: 0, mix: 1 },
  },
  {
    id: 'mb-harmonic-exciter',
    slug: 'mb-harmonic-exciter',
    name: 'MB Harmonic Exciter',
    category: 'effect',
    type: 'distortion',
    version: '1.0.0',
    description: 'Multiband harmonic enhancer for adding presence and clarity',
    author: 'Max Booster',
    parameters: [
      { id: 'low_amount', name: 'Low Harmonics', type: 'float', defaultValue: 0, minValue: 0, maxValue: 100, unit: '%', automatable: true },
      { id: 'mid_amount', name: 'Mid Harmonics', type: 'float', defaultValue: 0, minValue: 0, maxValue: 100, unit: '%', automatable: true },
      { id: 'high_amount', name: 'High Harmonics', type: 'float', defaultValue: 0, minValue: 0, maxValue: 100, unit: '%', automatable: true },
      { id: 'crossover_low', name: 'Low Crossover', type: 'float', defaultValue: 200, minValue: 50, maxValue: 500, unit: 'Hz', automatable: true },
      { id: 'crossover_high', name: 'High Crossover', type: 'float', defaultValue: 4000, minValue: 1000, maxValue: 10000, unit: 'Hz', automatable: true },
      { id: 'odd_even', name: 'Odd/Even Balance', type: 'float', defaultValue: 0.5, minValue: 0, maxValue: 1, automatable: true },
      { id: 'mix', name: 'Mix', type: 'float', defaultValue: 0.5, minValue: 0, maxValue: 1, automatable: true },
    ],
    defaultPreset: { low_amount: 0, mid_amount: 0, high_amount: 0, crossover_low: 200, crossover_high: 4000, odd_even: 0.5, mix: 0.5 },
  },
  {
    id: 'mb-vintage-eq',
    slug: 'mb-vintage-eq',
    name: 'MB Vintage EQ',
    category: 'effect',
    type: 'eq',
    version: '1.0.0',
    description: 'Classic Pultec-style passive EQ with musical curves',
    author: 'Max Booster',
    parameters: [
      { id: 'low_freq', name: 'Low Frequency', type: 'choice', defaultValue: '100', choices: ['20', '30', '60', '100'], automatable: false },
      { id: 'low_boost', name: 'Low Boost', type: 'float', defaultValue: 0, minValue: 0, maxValue: 10, unit: 'dB', automatable: true },
      { id: 'low_atten', name: 'Low Attenuation', type: 'float', defaultValue: 0, minValue: 0, maxValue: 10, unit: 'dB', automatable: true },
      { id: 'high_freq', name: 'High Frequency', type: 'choice', defaultValue: '10k', choices: ['3k', '4k', '5k', '8k', '10k', '12k', '16k'], automatable: false },
      { id: 'high_boost', name: 'High Boost', type: 'float', defaultValue: 0, minValue: 0, maxValue: 10, unit: 'dB', automatable: true },
      { id: 'high_bandwidth', name: 'High Bandwidth', type: 'float', defaultValue: 0.5, minValue: 0, maxValue: 1, automatable: true },
      { id: 'high_atten_freq', name: 'High Atten Freq', type: 'choice', defaultValue: '10k', choices: ['5k', '10k', '20k'], automatable: false },
      { id: 'high_atten', name: 'High Attenuation', type: 'float', defaultValue: 0, minValue: 0, maxValue: 10, unit: 'dB', automatable: true },
      { id: 'output', name: 'Output', type: 'float', defaultValue: 0, minValue: -12, maxValue: 12, unit: 'dB', automatable: true },
    ],
    defaultPreset: { low_freq: '100', low_boost: 0, low_atten: 0, high_freq: '10k', high_boost: 0, high_bandwidth: 0.5, high_atten_freq: '10k', high_atten: 0, output: 0 },
  },
  {
    id: 'mb-pitch-shifter',
    slug: 'mb-pitch-shifter',
    name: 'MB Pitch Shifter',
    category: 'effect',
    type: 'eq',
    version: '1.0.0',
    description: 'High-quality pitch shifting with formant preservation',
    author: 'Max Booster',
    parameters: [
      { id: 'semitones', name: 'Semitones', type: 'float', defaultValue: 0, minValue: -24, maxValue: 24, automatable: true },
      { id: 'cents', name: 'Fine Tune', type: 'float', defaultValue: 0, minValue: -100, maxValue: 100, unit: 'cents', automatable: true },
      { id: 'formant', name: 'Formant Shift', type: 'float', defaultValue: 0, minValue: -12, maxValue: 12, unit: 'semitones', automatable: true },
      { id: 'preserve_formant', name: 'Preserve Formant', type: 'bool', defaultValue: true, automatable: false },
      { id: 'grain_size', name: 'Grain Size', type: 'float', defaultValue: 50, minValue: 10, maxValue: 200, unit: 'ms', automatable: true },
      { id: 'mix', name: 'Mix', type: 'float', defaultValue: 1, minValue: 0, maxValue: 1, automatable: true },
    ],
    defaultPreset: { semitones: 0, cents: 0, formant: 0, preserve_formant: true, grain_size: 50, mix: 1 },
  },
  {
    id: 'mb-vintage-limiter',
    slug: 'mb-vintage-limiter',
    name: 'MB Vintage Limiter',
    category: 'effect',
    type: 'limiter',
    version: '1.0.0',
    description: 'Warm optical-style limiter for gentle peak control',
    author: 'Max Booster',
    parameters: [
      { id: 'input', name: 'Input Gain', type: 'float', defaultValue: 0, minValue: 0, maxValue: 24, unit: 'dB', automatable: true },
      { id: 'release', name: 'Release', type: 'float', defaultValue: 100, minValue: 10, maxValue: 1000, unit: 'ms', automatable: true },
      { id: 'ceiling', name: 'Ceiling', type: 'float', defaultValue: -0.3, minValue: -6, maxValue: 0, unit: 'dB', automatable: true },
      { id: 'character', name: 'Character', type: 'float', defaultValue: 0.5, minValue: 0, maxValue: 1, automatable: true },
      { id: 'auto_release', name: 'Auto Release', type: 'bool', defaultValue: true, automatable: false },
      { id: 'link_stereo', name: 'Link Stereo', type: 'bool', defaultValue: true, automatable: false },
    ],
    defaultPreset: { input: 0, release: 100, ceiling: -0.3, character: 0.5, auto_release: true, link_stereo: true },
  },
  {
    id: 'mb-spring-reverb',
    slug: 'mb-spring-reverb',
    name: 'MB Spring Reverb',
    category: 'effect',
    type: 'reverb',
    version: '1.0.0',
    description: 'Classic spring reverb emulation with drip and splash',
    author: 'Max Booster',
    parameters: [
      { id: 'mix', name: 'Mix', type: 'float', defaultValue: 0.3, minValue: 0, maxValue: 1, automatable: true },
      { id: 'decay', name: 'Decay', type: 'float', defaultValue: 2, minValue: 0.5, maxValue: 6, unit: 's', automatable: true },
      { id: 'tension', name: 'Spring Tension', type: 'float', defaultValue: 0.5, minValue: 0, maxValue: 1, automatable: true },
      { id: 'drip', name: 'Drip', type: 'float', defaultValue: 0.3, minValue: 0, maxValue: 1, automatable: true },
      { id: 'diffusion', name: 'Diffusion', type: 'float', defaultValue: 0.5, minValue: 0, maxValue: 1, automatable: true },
      { id: 'low_cut', name: 'Low Cut', type: 'float', defaultValue: 100, minValue: 20, maxValue: 500, unit: 'Hz', automatable: true },
      { id: 'high_cut', name: 'High Cut', type: 'float', defaultValue: 8000, minValue: 1000, maxValue: 20000, unit: 'Hz', automatable: true },
    ],
    defaultPreset: { mix: 0.3, decay: 2, tension: 0.5, drip: 0.3, diffusion: 0.5, low_cut: 100, high_cut: 8000 },
  },
  {
    id: 'mb-shimmer-reverb',
    slug: 'mb-shimmer-reverb',
    name: 'MB Shimmer Reverb',
    category: 'effect',
    type: 'reverb',
    version: '1.0.0',
    description: 'Ethereal shimmer reverb with octave-shifted tails',
    author: 'Max Booster',
    parameters: [
      { id: 'mix', name: 'Mix', type: 'float', defaultValue: 0.4, minValue: 0, maxValue: 1, automatable: true },
      { id: 'decay', name: 'Decay', type: 'float', defaultValue: 5, minValue: 1, maxValue: 30, unit: 's', automatable: true },
      { id: 'shimmer', name: 'Shimmer Amount', type: 'float', defaultValue: 0.5, minValue: 0, maxValue: 1, automatable: true },
      { id: 'pitch', name: 'Shimmer Pitch', type: 'choice', defaultValue: '+12', choices: ['-12', '-5', '+5', '+7', '+12', '+19', '+24'], automatable: false },
      { id: 'feedback', name: 'Shimmer Feedback', type: 'float', defaultValue: 0.5, minValue: 0, maxValue: 0.95, automatable: true },
      { id: 'modulation', name: 'Modulation', type: 'float', defaultValue: 0.3, minValue: 0, maxValue: 1, automatable: true },
      { id: 'diffusion', name: 'Diffusion', type: 'float', defaultValue: 0.8, minValue: 0, maxValue: 1, automatable: true },
      { id: 'damping', name: 'Damping', type: 'float', defaultValue: 0.5, minValue: 0, maxValue: 1, automatable: true },
    ],
    defaultPreset: { mix: 0.4, decay: 5, shimmer: 0.5, pitch: '+12', feedback: 0.5, modulation: 0.3, diffusion: 0.8, damping: 0.5 },
  },
  {
    id: 'mb-ping-pong-delay',
    slug: 'mb-ping-pong-delay',
    name: 'MB Ping Pong Delay',
    category: 'effect',
    type: 'delay',
    version: '1.0.0',
    description: 'Stereo ping pong delay with tempo sync',
    author: 'Max Booster',
    parameters: [
      { id: 'time_l', name: 'Time Left', type: 'float', defaultValue: 250, minValue: 1, maxValue: 2000, unit: 'ms', automatable: true },
      { id: 'time_r', name: 'Time Right', type: 'float', defaultValue: 375, minValue: 1, maxValue: 2000, unit: 'ms', automatable: true },
      { id: 'sync', name: 'Tempo Sync', type: 'bool', defaultValue: true, automatable: false },
      { id: 'sync_l', name: 'Sync Left', type: 'choice', defaultValue: '1/4', choices: ['1/16', '1/8', '1/4', '1/2', '1/1', '3/16', '3/8'], automatable: false },
      { id: 'sync_r', name: 'Sync Right', type: 'choice', defaultValue: '1/4D', choices: ['1/16', '1/8', '1/4', '1/2', '1/1', '1/4D', '1/8D'], automatable: false },
      { id: 'feedback', name: 'Feedback', type: 'float', defaultValue: 0.4, minValue: 0, maxValue: 0.95, automatable: true },
      { id: 'cross_feedback', name: 'Cross Feedback', type: 'float', defaultValue: 0.3, minValue: 0, maxValue: 0.95, automatable: true },
      { id: 'low_cut', name: 'Low Cut', type: 'float', defaultValue: 100, minValue: 20, maxValue: 2000, unit: 'Hz', automatable: true },
      { id: 'high_cut', name: 'High Cut', type: 'float', defaultValue: 8000, minValue: 500, maxValue: 20000, unit: 'Hz', automatable: true },
      { id: 'mix', name: 'Mix', type: 'float', defaultValue: 0.3, minValue: 0, maxValue: 1, automatable: true },
    ],
    defaultPreset: { time_l: 250, time_r: 375, sync: true, sync_l: '1/4', sync_r: '1/4D', feedback: 0.4, cross_feedback: 0.3, low_cut: 100, high_cut: 8000, mix: 0.3 },
  },
  {
    id: 'mb-auto-filter',
    slug: 'mb-auto-filter',
    name: 'MB Auto Filter',
    category: 'effect',
    type: 'eq',
    version: '1.0.0',
    description: 'Resonant filter with envelope follower and LFO modulation',
    author: 'Max Booster',
    parameters: [
      { id: 'filter_type', name: 'Filter Type', type: 'choice', defaultValue: 'lowpass', choices: ['lowpass', 'highpass', 'bandpass', 'notch'], automatable: false },
      { id: 'cutoff', name: 'Cutoff', type: 'float', defaultValue: 1000, minValue: 20, maxValue: 20000, unit: 'Hz', automatable: true },
      { id: 'resonance', name: 'Resonance', type: 'float', defaultValue: 0.5, minValue: 0, maxValue: 1, automatable: true },
      { id: 'env_amount', name: 'Envelope Amount', type: 'float', defaultValue: 0, minValue: -100, maxValue: 100, unit: '%', automatable: true },
      { id: 'env_attack', name: 'Env Attack', type: 'float', defaultValue: 10, minValue: 0.1, maxValue: 500, unit: 'ms', automatable: true },
      { id: 'env_release', name: 'Env Release', type: 'float', defaultValue: 100, minValue: 1, maxValue: 2000, unit: 'ms', automatable: true },
      { id: 'lfo_rate', name: 'LFO Rate', type: 'float', defaultValue: 1, minValue: 0.01, maxValue: 20, unit: 'Hz', automatable: true },
      { id: 'lfo_amount', name: 'LFO Amount', type: 'float', defaultValue: 0, minValue: 0, maxValue: 100, unit: '%', automatable: true },
      { id: 'lfo_shape', name: 'LFO Shape', type: 'choice', defaultValue: 'sine', choices: ['sine', 'triangle', 'square', 'sawtooth', 'random'], automatable: false },
      { id: 'drive', name: 'Drive', type: 'float', defaultValue: 0, minValue: 0, maxValue: 1, automatable: true },
    ],
    defaultPreset: { filter_type: 'lowpass', cutoff: 1000, resonance: 0.5, env_amount: 0, env_attack: 10, env_release: 100, lfo_rate: 1, lfo_amount: 0, lfo_shape: 'sine', drive: 0 },
  },
  {
    id: 'mb-bitcrusher',
    slug: 'mb-bitcrusher',
    name: 'MB Bitcrusher',
    category: 'effect',
    type: 'distortion',
    version: '1.0.0',
    description: 'Bit reduction and sample rate destruction for lo-fi effects',
    author: 'Max Booster',
    parameters: [
      { id: 'bit_depth', name: 'Bit Depth', type: 'float', defaultValue: 16, minValue: 1, maxValue: 16, automatable: true },
      { id: 'sample_rate', name: 'Sample Rate', type: 'float', defaultValue: 44100, minValue: 100, maxValue: 44100, unit: 'Hz', automatable: true },
      { id: 'jitter', name: 'Jitter', type: 'float', defaultValue: 0, minValue: 0, maxValue: 1, automatable: true },
      { id: 'dither', name: 'Dither', type: 'bool', defaultValue: false, automatable: false },
      { id: 'drive', name: 'Drive', type: 'float', defaultValue: 0, minValue: 0, maxValue: 24, unit: 'dB', automatable: true },
      { id: 'mix', name: 'Mix', type: 'float', defaultValue: 1, minValue: 0, maxValue: 1, automatable: true },
    ],
    defaultPreset: { bit_depth: 16, sample_rate: 44100, jitter: 0, dither: false, drive: 0, mix: 1 },
  },
  {
    id: 'mb-vinyl-simulator',
    slug: 'mb-vinyl-simulator',
    name: 'MB Vinyl Simulator',
    category: 'effect',
    type: 'distortion',
    version: '1.0.0',
    description: 'Authentic vinyl record emulation with crackle and warmth',
    author: 'Max Booster',
    parameters: [
      { id: 'year', name: 'Year', type: 'choice', defaultValue: '1970s', choices: ['1950s', '1960s', '1970s', '1980s', '1990s'], automatable: false },
      { id: 'wear', name: 'Wear', type: 'float', defaultValue: 0.3, minValue: 0, maxValue: 1, automatable: true },
      { id: 'crackle', name: 'Crackle', type: 'float', defaultValue: 0.2, minValue: 0, maxValue: 1, automatable: true },
      { id: 'dust', name: 'Dust', type: 'float', defaultValue: 0.1, minValue: 0, maxValue: 1, automatable: true },
      { id: 'warp', name: 'Warp', type: 'float', defaultValue: 0, minValue: 0, maxValue: 1, automatable: true },
      { id: 'mechanical', name: 'Mechanical Noise', type: 'float', defaultValue: 0.1, minValue: 0, maxValue: 1, automatable: true },
      { id: 'low_boost', name: 'Low Boost', type: 'float', defaultValue: 0.3, minValue: 0, maxValue: 1, automatable: true },
      { id: 'high_roll', name: 'High Roll-off', type: 'float', defaultValue: 0.4, minValue: 0, maxValue: 1, automatable: true },
      { id: 'mix', name: 'Mix', type: 'float', defaultValue: 1, minValue: 0, maxValue: 1, automatable: true },
    ],
    defaultPreset: { year: '1970s', wear: 0.3, crackle: 0.2, dust: 0.1, warp: 0, mechanical: 0.1, low_boost: 0.3, high_roll: 0.4, mix: 1 },
  },
];

export const ALL_ADDITIONAL_PLUGINS = [
  ...ADDITIONAL_SYNTH_PLUGINS,
  ...ADDITIONAL_EFFECT_PLUGINS,
];
