import { PIANO_PLUGINS, STRINGS_PLUGINS, DRUMS_PLUGINS, BASS_PLUGINS, PAD_PLUGINS, SYNTH_PLUGINS, FM_PLUGINS, WAVETABLE_PLUGINS, SAMPLER_PLUGINS } from '../../../built-in plugins dsp/server/instrumentPlugins';
import { REVERB_PLUGINS, DELAY_PLUGINS, COMPRESSOR_PLUGINS, EQ_PLUGINS, DISTORTION_PLUGINS, MODULATION_PLUGINS, DYNAMICS_PLUGINS, VOCAL_PLUGINS, MICROPHONE_PLUGINS } from '../../../built-in plugins dsp/server/effectPlugins';
import { ADDITIONAL_SYNTH_PLUGINS, ADDITIONAL_EFFECT_PLUGINS } from '../../../built-in plugins dsp/server/expandedPlugins';
import { ALL_ADDITIONAL_INSTRUMENTS } from '../../../built-in plugins dsp/server/additionalInstrumentPlugins';
import { ALL_ADDITIONAL_EFFECTS } from '../../../built-in plugins dsp/server/additionalEffectPlugins';
import type { PluginDefinition } from '../pluginHostService';

export const EXPANDED_INSTRUMENTS: PluginDefinition[] = [
  ...PIANO_PLUGINS,
  ...STRINGS_PLUGINS,
  ...DRUMS_PLUGINS,
  ...BASS_PLUGINS,
  ...PAD_PLUGINS,
  ...SYNTH_PLUGINS,
  ...FM_PLUGINS,
  ...WAVETABLE_PLUGINS,
  ...SAMPLER_PLUGINS,
  ...ADDITIONAL_SYNTH_PLUGINS,
  ...ALL_ADDITIONAL_INSTRUMENTS,
];

export const EXPANDED_EFFECTS: PluginDefinition[] = [
  ...REVERB_PLUGINS,
  ...DELAY_PLUGINS,
  ...COMPRESSOR_PLUGINS,
  ...EQ_PLUGINS,
  ...DISTORTION_PLUGINS,
  ...MODULATION_PLUGINS,
  ...DYNAMICS_PLUGINS,
  ...VOCAL_PLUGINS,
  ...MICROPHONE_PLUGINS,
  ...ADDITIONAL_EFFECT_PLUGINS,
  ...ALL_ADDITIONAL_EFFECTS,
];

export const ALL_PLUGINS: PluginDefinition[] = [
  ...EXPANDED_INSTRUMENTS,
  ...EXPANDED_EFFECTS,
];

export {
  PIANO_PLUGINS,
  STRINGS_PLUGINS,
  DRUMS_PLUGINS,
  BASS_PLUGINS,
  PAD_PLUGINS,
  SYNTH_PLUGINS,
  FM_PLUGINS,
  WAVETABLE_PLUGINS,
  SAMPLER_PLUGINS,
  REVERB_PLUGINS,
  DELAY_PLUGINS,
  COMPRESSOR_PLUGINS,
  EQ_PLUGINS,
  DISTORTION_PLUGINS,
  MODULATION_PLUGINS,
  DYNAMICS_PLUGINS,
  VOCAL_PLUGINS,
  MICROPHONE_PLUGINS,
};
