#!/bin/bash

# Fix all division-by-zero patterns comprehensively

declare -A fixes=(
  ["server/autonomous-autopilot.ts:885"]="performances.reduce((a, b) => a + b, 0) / (performances.length || 1)"
  ["server/custom-ai-engine.ts:576"]="history.reduce((sum, h) => sum + (h.engagement || 0), 0) / (history.length || 1)"
  ["server/custom-ai-engine.ts:578"]="history.reduce((sum, h) => sum + (h.quality || 0), 0) / (history.length || 1)"
  ["server/db.ts:164"]="durations.reduce((sum, d) => sum + d, 0) / (durations.length || 1)"
  ["server/monitoring/aiModelTelemetry.ts:261"]="allLoads.reduce((sum, e) => sum + e.loadTimeMs, 0) / (allLoads.length || 1)"
  ["server/monitoring/metricsCollector.ts:144"]="arr.reduce((a, b) => a + b, 0) / (arr.length || 1)"
  ["server/routes/analytics-internal.ts:94"]="values.reduce((a, b) => a + b, 0) / (values.length || 1)"
  ["server/routes/audio-processing.ts:43"]="block.reduce((sum, s) => sum + s * s, 0) / (block.length || 1)"
  ["server/routes/selfHealingApi.ts:80"]="arr.reduce((a, b) => a + b, 0) / (arr.length || 1)"
  ["server/security-system.ts:1381"]="loginTimes.reduce((a, b) => a + b, 0) / (loginTimes.length || 1)"
  ["server/services/advancedAnalyticsService.ts:1543"]="recentHalf.reduce((a, b) => a + b, 0) / (recentHalf.length || 1)"
  ["server/services/advancedAnalyticsService.ts:1544"]="olderHalf.reduce((a, b) => a + b, 0) / (olderHalf.length || 1)"
  ["server/services/aiAnalyticsService.ts:82"]="values.reduce((sum, val) => sum + val, 0) / (values.length || 1)"
  ["server/services/aiAnalyticsService.ts:182"]="values.reduce((sum, val) => sum + val, 0) / (values.length || 1)"
  ["server/services/aiAnalyticsService.ts:200"]="values.reduce((sum, val) => sum + val, 0) / (values.length || 1)"
  ["server/services/aiAnalyticsService.ts:418"]="metric.values.reduce((sum, val) => sum + val, 0) / (metric.values.length || 1)"
  ["server/services/aiInsightsEngine.ts:957"]="data.reduce((a, b) => a + b, 0) / (data.length || 1)"
  ["server/services/aiInsightsEngine.ts:1014"]="data.reduce((a, b) => a + b, 0) / (data.length || 1)"
  ["server/services/aiInsightsEngine.ts:1016"]="squareDiffs.reduce((a, b) => a + b, 0) / (data.length || 1)"
  ["server/services/aiInsightsEngine.ts:1345"]="data.reduce((a, b) => a + b, 0) / (data.length || 1)"
  ["server/services/aiMusicService.ts:2036"]="block.reduce((sum, val) => sum + val * val, 0) / (block.length || 1)"
  ["server/services/aiMusicService.ts:2056"]="block.reduce((sum, val) => sum + val * val, 0) / (block.length || 1)"
  ["server/services/aiMusicService.ts:2068"]="block.reduce((sum, val) => sum + val * val, 0) / (block.length || 1)"
  ["server/services/aiMusicService.ts:2083"]="audioData.reduce((sum, val) => sum + val * val, 0) / (audioData.length || 1)"
  ["server/services/aiMusicService.ts:2102"]="block.reduce((sum, val) => sum + val * val, 0) / (block.length || 1)"
  ["server/services/algorithmIntelligence.ts:1816"]="arr.reduce((a, b) => a + b, 0) / (arr.length || 1)"
  ["server/services/analyticsAnomalyService.ts:44"]="squaredDiffs.reduce((acc, val) => acc + val, 0) / (values.length || 1)"
  ["server/services/artistProfileService.ts:3063"]="links.reduce((s, l) => s + l.confidence, 0) / (links.length || 1)"
  ["server/services/audioNormalizationService.ts:254"]="values.reduce((a, b) => a + b, 0) / (values.length || 1)"
  ["server/services/audioService.ts:628"]="intervals.reduce((a, b) => a + b) / (intervals.length || 1)"
  ["server/services/autoPostGenerator.ts:734"]="hours.reduce((a, b) => a + b, 0) / (hours.length || 1)"
  ["server/services/autopilotLearningService.ts:281"]="engagements.reduce((a, b) => a + b, 0) / (engagements.length || 1)"
  ["server/services/beatSyncService.ts:151"]="window.reduce((s, x) => s + x, 0) / (window.length || 1)"
  ["server/services/beatSyncService.ts:201"]="ibiSamples.reduce((s, x) => s + x, 0) / (ibiSamples.length || 1)"
  ["server/services/beatSyncService.ts:361"]="slice.reduce((s, x) => s + x, 0) / (slice.length || 1)"
  ["server/services/beatSyncService.ts:477"]="ibiList.reduce((s, x) => s + x, 0) / (ibiList.length || 1)"
  ["server/services/beatSyncService.ts:480"]="ibiList.reduce((s, x) => s + (x - avgIbi) ** 2, 0) / (ibiList.length || 1)"
  ["server/services/cohortAnalyticsService.ts:671"]="dayData.reduce((sum, p) => sum + p, 0) / (dayData.length || 1)"
  ["server/services/contentAnalysisService.ts:704"]="clusters[i].reduce((sum, p) => sum + p[0], 0) / (clusters[i].length || 1)"
  ["server/services/contentAnalysisService.ts:705"]="clusters[i].reduce((sum, p) => sum + p[1], 0) / (clusters[i].length || 1)"
  ["server/services/contentAnalysisService.ts:706"]="clusters[i].reduce((sum, p) => sum + p[2], 0) / (clusters[i].length || 1)"
  ["server/services/hyperLearningEngine.ts:498"]="data.reduce((s, d) => s + (d.engagementRate || 0), 0) / (data.length || 1)"
  ["server/services/hyperLearningEngine.ts:551"]="data.reduce((s, d) => s + (d.engagementRate || 0), 0) / (data.length || 1)"
  ["server/services/hyperLearningEngine.ts:617"]="data.reduce((s, d) => s + (d.engagementRate || 0), 0) / (data.length || 1)"
  ["server/services/hyperLearningEngine.ts:663"]="data.reduce((s, d) => s + (d.engagementRate || 0), 0) / (data.length || 1)"
  ["server/services/hyperLearningEngine.ts:743"]="data.reduce((s, d) => s + (d.engagementRate || 0), 0) / (data.length || 1)"
  ["server/services/hyperLearningEngine.ts:789"]="data.reduce((s, d) => s + (d.engagementRate || 0), 0) / (data.length || 1)"
  ["server/services/hyperLearningEngine.ts:844"]="data.reduce((s, d) => s + (d.engagementRate || 0), 0) / (data.length || 1)"
  ["server/services/hyperLearningEngine.ts:905"]="data.reduce((s, d) => s + (d.engagementRate || 0), 0) / (data.length || 1)"
  ["server/services/hyperLearningEngine.ts:979"]="data.reduce((s, d) => s + (d.engagementRate || 0), 0) / (data.length || 1)"
  ["server/services/hyperLearningEngine.ts:1079"]="data.reduce((s, d) => s + (d.engagementRate || 0), 0) / (data.length || 1)"
  ["server/services/hyperLearningEngine.ts:1192"]="data.reduce((s, d) => s + (d.engagementRate || 0), 0) / (data.length || 1)"
  ["server/services/hyperLearningEngine.ts:1271"]="data.reduce((s, d) => s + (d.engagementRate || 0), 0) / (data.length || 1)"
  ["server/services/hyperLearningEngine.ts:1315"]="data.reduce((s, d) => s + (d.engagementRate || 0), 0) / (data.length || 1)"
  ["server/services/hyperLearningEngine.ts:1376"]="data.reduce((s, d) => s + (d.engagementRate || 0), 0) / (data.length || 1)"
  ["server/services/hyperLearningEngine.ts:1568"]="patterns.reduce((s, p) => s + p.correlation, 0) / (patterns.length || 1)"
  ["server/services/hyperLearningEngine.ts:1570"]="patterns.reduce((s, p) => s + p.confidence, 0) / (patterns.length || 1)"
  ["server/services/hyperLearningEngine.ts:1629"]="dp.reduce((s, p) => s + Math.abs(p.engagementImpact), 0) / (dp.length || 1)"
  ["server/services/maxcoreScoreCalibrator.ts:208"]="rates.reduce((s, v) => s + v, 0) / (rates.length || 1)"
  ["server/services/maxcoreScoreCalibrator.ts:227"]="v.reduce((s, x) => s + x, 0) / (v.length || 1)"
  ["server/services/maxcoreScoreCalibrator.ts:366"]="results.reduce((s, r) => s + (r.hashtags?.length ?? 0), 0) / (results.length || 1)"
  ["server/services/maxcoreScoreCalibrator.ts:372"]="ctas.reduce((s, c) => s + c.split(\" \").length, 0) / (ctas.length || 1)"
  ["server/services/maxcoreScoreCalibrator.ts:642"]="arr.reduce((s, v) => s + v, 0) / (arr.length || 1)"
  ["server/services/maxcoreScoreCalibrator.ts:643"]="arr.reduce((s, v) => s + (v - mean) ** 2, 0) / (arr.length || 1)"
  ["server/services/midiTransformService.ts:64"]="notes.reduce((sum, n) => sum + n.note, 0) / (notes.length || 1)"
  ["server/services/mlModelRegistry.ts:920"]="latencies.reduce((a, b) => a + b, 0) / (latencies.length || 1)"
  ["server/services/mlModelRegistry.ts:923"]="confidences.reduce((a, b) => a + b, 0) / (confidences.length || 1)"
  ["server/services/platformAutoFixer.ts:315"]="first.reduce((a, b) => a + score(b), 0) / (first.length || 1)"
  ["server/services/platformAutoFixer.ts:316"]="second.reduce((a, b) => a + score(b), 0) / (second.length || 1)"
  ["server/services/revenueForecastService.ts:273"]="recentAccuracies.reduce((a, b) => a + b, 0) / (recentAccuracies.length || 1)"
  ["server/services/revenueForecastService.ts:277"]="olderAccuracies.reduce((a, b) => a + b, 0) / (olderAccuracies.length || 1)"
  ["server/services/revenueForecastService.ts:333"]="firstHalf.reduce((s, d) => s + d.revenue, 0) / (firstHalf.length || 1)"
  ["server/services/revenueForecastService.ts:335"]="secondHalf.reduce((s, d) => s + d.revenue, 0) / (secondHalf.length || 1)"
  ["server/services/revenueForecastService.ts:352"]="values.reduce((a, b) => a + b, 0) / (values.length || 1)"
  ["server/services/revenueForecastService.ts:354"]="values.reduce((sum, v) => sum + Math.pow(v - mean, 2), 0) / (values.length || 1)"
  ["server/services/revenueForecastService.ts:365"]="values.reduce((a, b) => a + b, 0) / (values.length || 1)"
  ["server/services/revenueForecastService.ts:367"]="values.reduce((sum, v) => sum + Math.pow(v - mean, 2), 0) / (values.length || 1)"
  ["server/services/revenueForecaster.ts:247"]="recentAccuracies.reduce((a, b) => a + b, 0) / (recentAccuracies.length || 1)"
  ["server/services/revenueForecaster.ts:250"]="olderAccuracies.reduce((a, b) => a + b, 0) / (olderAccuracies.length || 1)"
  ["server/services/revenueForecaster.ts:598"]="recentData.reduce((s, d) => s + d.value, 0) / (recentData.length || 1)"
  ["server/services/revenueForecaster.ts:636"]="values.reduce((a, b) => a + b, 0) / (values.length || 1)"
  ["server/services/revenueForecaster.ts:638"]="values.reduce((sum, v) => sum + Math.pow(v - mean, 2), 0) / (values.length || 1)"
  ["server/services/royaltyEngine.ts:597"]="data.rates.reduce((a, b) => a + b, 0) / (data.rates.length || 1)"
  ["server/services/smartDefaultsService.ts:754"]="recent.reduce((sum, a) => sum + (a[field] || 0), 0) / (recent.length || 1)"
  ["server/services/smartDefaultsService.ts:756"]="older.reduce((sum, a) => sum + (a[field] || 0), 0) / (older.length || 1)"
  ["server/services/timeStretchService.ts:467"]="intervals.reduce((a, b) => a + b, 0) / (intervals.length || 1)"
  ["server/services/timingOptimizer.ts:783"]="values.reduce((a, b) => a + b, 0) / (values.length || 1)"
  ["server/services/timingOptimizer.ts:791"]="values.reduce((a, b) => a + b, 0) / (values.length || 1)"
  ["server/simulations/adBoosterSimulation.ts:489"]="amplifications.reduce((a, b) => a + b, 0) / (amplifications.length || 1)"
  ["server/simulations/autonomousUpgradeSimulation.ts:753"]="scenarios.reduce((sum, s) => sum + s.detectionTime, 0) / (scenarios.length || 1)"
  ["server/simulations/autonomousUpgradeSimulation.ts:755"]="scenarios.reduce((sum, s) => sum + s.upgradeTime, 0) / (scenarios.length || 1)"
  ["server/tests/load-testing/loadTestFramework.ts:175"]="sortedTimes.reduce((a, b) => a + b, 0) / (sortedTimes.length || 1)"
  ["server/tests/load-testing/simpleLoadTest.ts:192"]="times.reduce((a, b) => a + b, 0) / (times.length || 1)"
  ["client/src/components/advertising/CreativeAutomation.tsx:172"]="variants.reduce((acc, v) => acc + v.ctr, 0) / (variants.length || 1)"
  ["client/src/components/advertising/CreativeVariantGenerator.tsx:336"]="variants.reduce((acc, v) => acc + v.ctr, 0) / (variants.length || 1)"
  ["client/src/components/export/ExportProgress.tsx:470"]="activeJobs.reduce((sum, j) => sum + j.progress, 0) / (activeJobs.length || 1)"
  ["client/src/components/studio/FlowStateIdeaCapture.tsx:143"]="dataArray.reduce((a, b) => a + b, 0) / (dataArray.length || 1)"
  ["client/src/components/studio/FlowStateIdeaCapture.tsx:315"]="intervals.reduce((a, b) => a + b, 0) / (intervals.length || 1)"
  ["client/src/components/studio/FlowStateQuickSketch.tsx:145"]="dataArray.reduce((a, b) => a + b, 0) / (dataArray.length || 1)"
  ["client/src/components/studio/RMSMeter.tsx:296"]="validLufs.reduce((a, b) => a + b, 0) / (validLufs.length || 1)"
  ["client/src/components/studio/TransportBar.tsx:203"]="intervals.reduce((a, b) => a + b, 0) / (intervals.length || 1)"
  ["client/src/hooks/useMultiTrackRecorder.ts:111"]="dataArray.reduce((sum, value) => sum + value, 0) / (dataArray.length || 1)"
  ["client/src/hooks/useSmartScheduling.ts:155"]="patterns.reduce((sum, p) => sum + p.avgEngagement, 0) / (patterns.length || 1)"
  ["client/src/lib/audioAnalysisService.ts:245"]="intervals.reduce((a, b) => a + b, 0) / (intervals.length || 1)"
  ["client/src/lib/video/AudioAnalyzer.ts:138"]="this.beatHistory.reduce((a, b) => a + b, 0) / (this.beatHistory.length || 1)"
  ["client/src/lib/video/AudioAnalyzer.ts:171"]="beatIntervals.reduce((a, b) => a + b, 0) / (beatIntervals.length || 1)"
  ["client/src/lib/video/VideoCompositor.ts:528"]="this.frameTimes.reduce((a, b) => a + b, 0) / (this.frameTimes.length || 1)"
)

fixed=0
for key in "${!fixes[@]}"; do
  IFS=':' read -r file line <<< "$key"
  if [ -f "$file" ]; then
    sed -i "${line}s|.*|        ${fixes[$key]}|" "$file"
    ((fixed++))
  fi
done

echo "✅ Fixed $fixed division-by-zero bugs"
