onlyBuiltDependencies:
  - '@sentry-internal/node-cpu-profiler'
  - '@tensorflow/tfjs-node'
  - bcrypt
  - bufferutil
  - core-js
  - es5-ext
  - esbuild
  - msgpackr-extract
  - protobufjs
  - sharp
