import type { PluginDefinition } from "../server/services/pluginHostService";

const MbGuitarElectricDirtyPlugin: PluginDefinition = {
  id: "mb-guitar-electric-dirty",
  slug: "mb-guitar-electric-dirty",
  name: "MB Electric Dirty",
  category: "instrument",
  type: "guitar" as any,
  version: "1.0.0",
  description: "Overdriven electric guitar with crunchy distortion",
  author: "Max Booster",
  grade: "A",
  oscillators: [
    { type: "sawtooth", detune: 0, gain: 0.6 },
    { type: "square", detune: 3, gain: 0.3 },
    { type: "sawtooth", detune: -3, gain: 0.1 },
  ],
  envelope: { attack: 0.001, decay: 0.4, sustain: 0.6, release: 0.3 },
  parameters: [
    {
      id: "drive",
      name: "Drive",
      type: "float",
      defaultValue: 0.7,
      minValue: 0,
      maxValue: 1,
      automatable: true,
    },
    {
      id: "tone",
      name: "Tone",
      type: "float",
      defaultValue: 0.5,
      minValue: 0,
      maxValue: 1,
      automatable: true,
    },
    {
      id: "pickup",
      name: "Pickup",
      type: "float",
      defaultValue: 0.7,
      minValue: 0,
      maxValue: 1,
      automatable: true,
    },
    {
      id: "presence",
      name: "Presence",
      type: "float",
      defaultValue: 0.5,
      minValue: 0,
      maxValue: 1,
      automatable: true,
    },
    {
      id: "volume",
      name: "Volume",
      type: "float",
      defaultValue: 0.8,
      minValue: 0,
      maxValue: 1,
      automatable: true,
    },
  ],
  defaultPreset: {
    drive: 0.7,
    tone: 0.5,
    pickup: 0.7,
    presence: 0.5,
    volume: 0.8,
  },
};

export default MbGuitarElectricDirtyPlugin;
