"""
Real Frame Extractor — Video-Native Training Data

Extracts T=32 frame sequences from real rendered video sources:

Source 1 — Scene Renderer (primary):
  Calls the existing Python frameGenerator at multiple time steps t=[0..1].
  Each t produces a different moment in the animation cycle.
  Gives temporally coherent sequences: same scene, advancing time.

Source 2 — Existing generated video cache:
  Reads any .mp4 files already generated by the video pipeline.
  Uses OpenCV (if available) or PIL frame-by-frame extraction.
  Gives diverse real sequences the model has never explicitly trained on.

Source 3 — Procedural motion sequences:
  Generates T frames with controlled parametric motion:
  pan, zoom, fade, parallax, particle flow, color shift.
  Guarantees large diversity even without stored videos.

Source 4 — Template animation sequences:
  Extends the PIL training templates (training_data_v2.py) to render
  the same scene at T different time points, applying:
  - Spotlight sweep animations
  - Crowd bob/wave cycles
  - Rain streak motion
  - Particle field advection
  Gives ~100,000 unique frame sequences per epoch.

All frames returned as float32 in [-1, 1], shape (T, H, W, 3).
Native resolution: 96×96 (trained resolution of v4 UNet).
"""

import os
import sys
import math
import time
import numpy as np
from typing import List, Tuple, Optional

_here = os.path.dirname(os.path.abspath(__file__))
_parent = os.path.dirname(_here)
if _parent not in sys.path:
    sys.path.insert(0, _parent)

TARGET_H = 96
TARGET_W = 96
DEFAULT_T = 32


def _resize_frame(frame: np.ndarray, H: int = TARGET_H, W: int = TARGET_W) -> np.ndarray:
    """Bilinear resize to (H, W, C) using numpy stride tricks."""
    h, w = frame.shape[:2]
    if h == H and w == W:
        return frame
    y_coords = np.linspace(0, h - 1, H)
    x_coords = np.linspace(0, w - 1, W)
    y0 = np.floor(y_coords).astype(int).clip(0, h - 2)
    x0 = np.floor(x_coords).astype(int).clip(0, w - 2)
    y1 = y0 + 1
    x1 = x0 + 1
    wy = (y_coords - y0)[:, None, None]
    wx = (x_coords - x0)[None, :, None]
    out = ((1 - wy) * (1 - wx) * frame[y0[:, None], x0[None, :]] +
           (1 - wy) *      wx  * frame[y0[:, None], x1[None, :]] +
                wy  * (1 - wx) * frame[y1[:, None], x0[None, :]] +
                wy  *      wx  * frame[y1[:, None], x1[None, :]])
    return out.astype(np.float32)


def _to_model_space(frame_uint8: np.ndarray) -> np.ndarray:
    """uint8 [0,255] → float32 [-1, 1]"""
    return (frame_uint8.astype(np.float32) / 127.5) - 1.0


def _from_model_space(frame_f32: np.ndarray) -> np.ndarray:
    """float32 [-1, 1] → uint8 [0, 255]"""
    return ((frame_f32 + 1.0) * 127.5).clip(0, 255).astype(np.uint8)


# ── Source 1: Scene Renderer Sequences ───────────────────────────────────────

def extract_from_scene_renderer(scene: str, T: int = DEFAULT_T,
                                 H: int = TARGET_H, W: int = TARGET_W,
                                 seed: int = 0) -> np.ndarray:
    """
    Render T frames from the scene animation cycle at times t=[0..1).
    Returns: (T, H, W, 3) float32 in [-1, 1]
    """
    try:
        from frameGenerator import generate_frame
        frames = []
        for i in range(T):
            t = i / T
            frame = generate_frame(scene, t=t, width=256, height=256, seed=seed)
            if hasattr(frame, '__array__'):
                frame = np.array(frame)
            frame = _resize_frame(frame.astype(np.float32), H, W)
            frames.append(_to_model_space(frame.astype(np.uint8)))
        return np.stack(frames, axis=0)
    except Exception:
        return _extract_procedural_sequence(scene, T, H, W, seed=seed)


# ── Source 2: Video Cache Extraction ──────────────────────────────────────────

def extract_from_video_cache(T: int = DEFAULT_T,
                              H: int = TARGET_H, W: int = TARGET_W,
                              max_files: int = 50) -> List[np.ndarray]:
    """
    Extract T-frame sequences from any .mp4/.webm files in generated video cache.
    Returns list of (T, H, W, 3) arrays.
    """
    sequences = []
    cache_dirs = [
        os.path.join(_here, '..', '..', '..', 'cache', 'videos'),
        os.path.join(_here, '..', '..', 'uploads'),
        '/tmp/video_cache',
    ]

    try:
        import cv2  # OpenCV for video frame extraction
        cv2_available = True
    except ImportError:
        cv2_available = False

    for cache_dir in cache_dirs:
        cache_dir = os.path.abspath(cache_dir)
        if not os.path.exists(cache_dir):
            continue
        for fname in sorted(os.listdir(cache_dir))[:max_files]:
            if not fname.endswith(('.mp4', '.webm', '.avi')):
                continue
            fpath = os.path.join(cache_dir, fname)
            seq = _extract_video_frames(fpath, T, H, W, cv2_available)
            if seq is not None:
                sequences.append(seq)

    return sequences


def _extract_video_frames(path: str, T: int, H: int, W: int,
                           use_cv2: bool) -> Optional[np.ndarray]:
    """Extract T evenly-spaced frames from a video file."""
    try:
        if use_cv2:
            import cv2
            cap = cv2.VideoCapture(path)
            n_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
            if n_frames < T:
                cap.release()
                return None
            indices = np.linspace(0, n_frames - 1, T).astype(int)
            frames = []
            for idx in indices:
                cap.set(cv2.CAP_PROP_POS_FRAMES, idx)
                ret, frame = cap.read()
                if not ret:
                    break
                frame_rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
                frame_r   = _resize_frame(frame_rgb.astype(np.float32), H, W)
                frames.append(_to_model_space(frame_r.astype(np.uint8)))
            cap.release()
            if len(frames) == T:
                return np.stack(frames, axis=0)
    except Exception:
        pass
    return None


# ── Source 3: Procedural Motion Sequences ─────────────────────────────────────

def _extract_procedural_sequence(scene: str, T: int = DEFAULT_T,
                                  H: int = TARGET_H, W: int = TARGET_W,
                                  seed: int = 0) -> np.ndarray:
    """
    Generate T frames of controlled parametric motion for a scene.
    Uses PIL for rendering with advancing animation parameters.
    """
    from PIL import Image, ImageDraw, ImageFilter
    rng = np.random.default_rng(seed + hash(scene) % (2**32))

    SCENE_PALETTES = {
        'concert_stage':    [(20,0,50),(80,0,120),(200,0,255),(255,50,200)],
        'city_nights':      [(5,10,25),(20,40,80),(0,100,200),(200,220,255)],
        'studio_session':   [(30,20,10),(80,60,30),(180,140,80),(255,220,160)],
        'golden_hour':      [(40,10,0),(120,50,0),(255,130,0),(255,220,100)],
        'neon_cityscape':   [(5,0,20),(0,50,100),(0,200,255),(255,0,150)],
        'trap_aesthetic':   [(10,10,10),(30,20,50),(100,0,200),(200,150,255)],
        'gospel_choir':     [(60,30,0),(150,80,20),(255,180,80),(255,240,200)],
        'hip_hop_cypher':   [(15,5,5),(60,10,10),(180,30,30),(255,100,50)],
        'dj_booth':         [(0,5,30),(0,30,100),(0,100,255),(100,200,255)],
        'luxury_yacht':     [(5,20,40),(10,60,100),(30,120,180),(200,240,255)],
    }

    palette = SCENE_PALETTES.get(scene, [(20,20,60),(60,60,150),(150,150,255),(220,220,255)])
    BG, MID, BRIGHT, ACCENT = palette

    frames = []
    for i in range(T):
        t = i / max(T - 1, 1)  # 0 → 1
        img = Image.new('RGB', (256, 256), BG)
        draw = ImageDraw.Draw(img)

        # ── Background gradient ──────────────────────────────────────────────
        for row in range(256):
            fade = row / 255.0
            r = int(BG[0] + (MID[0] - BG[0]) * fade)
            g = int(BG[1] + (MID[1] - BG[1]) * fade)
            b = int(BG[2] + (MID[2] - BG[2]) * fade)
            draw.line([(0, row), (255, row)], fill=(r, g, b))

        # ── Animated spotlight sweep ──────────────────────────────────────────
        spotlight_x = int(60 + 136 * (0.5 + 0.5 * math.sin(2 * math.pi * t)))
        spotlight_y = int(20 + 60 * abs(math.sin(math.pi * t)))
        for radius in range(80, 5, -5):
            alpha = max(0, 1.0 - radius / 80.0)
            brightness = int(alpha * 120)
            sr = min(255, BRIGHT[0] + brightness)
            sg = min(255, BRIGHT[1] + brightness)
            sb = min(255, BRIGHT[2] + brightness)
            draw.ellipse([
                spotlight_x - radius, spotlight_y - radius // 2,
                spotlight_x + radius, spotlight_y + radius // 2
            ], fill=(sr, sg, sb))

        # ── Animated particles/crowd ──────────────────────────────────────────
        rng_local = np.random.default_rng(seed)
        n_particles = 60
        px = rng_local.integers(10, 246, n_particles)
        py_base = rng_local.integers(150, 230, n_particles)
        for j in range(n_particles):
            bob = int(4 * math.sin(2 * math.pi * t + j * 0.3))
            py = py_base[j] + bob
            phase = (t + j / n_particles) % 1.0
            intensity = int(80 + 100 * phase)
            r = min(255, ACCENT[0] + intensity // 3)
            g = min(255, ACCENT[1] + intensity // 3)
            b = min(255, ACCENT[2] + intensity // 3)
            draw.ellipse([px[j]-3, py-3, px[j]+3, py+3], fill=(r, g, b))

        # ── Moving light beam ──────────────────────────────────────────────────
        beam_angle = math.pi * (0.3 + 0.4 * t)
        beam_len = 200
        bx2 = int(spotlight_x + beam_len * math.cos(beam_angle))
        by2 = int(spotlight_y + beam_len * math.sin(beam_angle))
        for w_beam in range(8, 0, -2):
            bcolor = tuple(min(255, int(c * 0.3)) for c in BRIGHT)
            draw.line([(spotlight_x, spotlight_y), (bx2, by2)],
                      fill=bcolor, width=w_beam)

        # ── Color shift over time (subtle hue rotation) ───────────────────────
        hue_shift = int(20 * math.sin(2 * math.pi * t * 0.5))
        r_shift = min(255, max(0, ACCENT[0] + hue_shift))
        b_shift = min(255, max(0, ACCENT[2] - hue_shift))

        # ── Soft blur for atmosphere ──────────────────────────────────────────
        img = img.filter(ImageFilter.GaussianBlur(radius=1))
        frame_np = np.array(img)
        frame_r  = _resize_frame(frame_np.astype(np.float32), H, W)
        frames.append(_to_model_space(frame_r.astype(np.uint8)))

    return np.stack(frames, axis=0)


# ── Source 4: PIL Template Animation Sequences ────────────────────────────────

def extract_from_templates(scene: str, T: int = DEFAULT_T,
                            H: int = TARGET_H, W: int = TARGET_W,
                            template_idx: int = 0,
                            seed: int = 0) -> np.ndarray:
    """
    Animate an existing PIL training template over T time steps.
    Applies: spotlight sweep, particle motion, color pulsing, zoom drift.
    Returns: (T, H, W, 3) float32 in [-1, 1]
    """
    try:
        from .training_data_v2 import get_templates_for_scene
        templates = get_templates_for_scene(scene)
        if not templates:
            return _extract_procedural_sequence(scene, T, H, W, seed)
        template_fn = templates[template_idx % len(templates)]
        frames = []
        for i in range(T):
            t = i / max(T - 1, 1)
            frame = template_fn(t=t, seed=seed)
            if not isinstance(frame, np.ndarray):
                frame = np.array(frame)
            frame_r = _resize_frame(frame.astype(np.float32), H, W)
            frames.append(_to_model_space(frame_r.astype(np.uint8)))
        return np.stack(frames, axis=0)
    except Exception:
        return _extract_procedural_sequence(scene, T, H, W, seed)


# ── Main FrameExtractor class ──────────────────────────────────────────────────

class FrameExtractor:
    """
    Unified frame sequence extractor for v4 video training.

    Sampling strategy (when real datasets available):
      25% — Real dataset frames (HMDB51 / UCF101 gulp_rgb)
      35% — Scene renderer (most temporally coherent)
      25% — PIL template animations (highest visual quality)
      15% — Procedural motion (most diverse)

    Sampling strategy (synthetic-only fallback):
      40% — Scene renderer
      30% — PIL template animations
      20% — Procedural motion
      10% — Video cache

    Usage:
        extractor = FrameExtractor(T=32, H=96, W=96)
        seq = extractor.sample(scene='concert_stage', seed=42)
        # seq.shape == (32, 96, 96, 3), float32 in [-1, 1]

        batch = extractor.sample_batch(scenes=['concert_stage']*8, seeds=range(8))
        # batch.shape == (8, 32, 96, 96, 3)
    """

    def __init__(self, T: int = DEFAULT_T, H: int = TARGET_H, W: int = TARGET_W):
        self.T = T
        self.H = H
        self.W = W
        self._video_cache   = None
        self._cache_loaded  = False
        self._real_reader   = None
        self._real_checked  = False

    def _get_real_reader(self):
        """Lazy-init the real dataset reader. Returns None if no video data available."""
        if not self._real_checked:
            self._real_checked = True
            try:
                from .dataset_reader import get_reader
                r = get_reader()
                if r.has_video_data():
                    self._real_reader = r
            except Exception:
                pass
        return self._real_reader

    def _load_video_cache(self):
        if not self._cache_loaded:
            self._video_cache = extract_from_video_cache(self.T, self.H, self.W)
            self._cache_loaded = True

    def sample(self, scene: str, seed: int = 0,
               source: str = 'auto') -> np.ndarray:
        """
        Sample a single T-frame sequence for a given scene.
        source: 'auto' | 'real_dataset' | 'renderer' | 'template' | 'procedural' | 'cache'
        """
        rng = np.random.default_rng(seed)
        real_reader = self._get_real_reader()

        if source == 'auto':
            r = rng.random()
            if real_reader is not None:
                if r < 0.25:
                    source = 'real_dataset'
                elif r < 0.60:
                    source = 'renderer'
                elif r < 0.85:
                    source = 'template'
                else:
                    source = 'procedural'
            else:
                if r < 0.40:
                    source = 'renderer'
                elif r < 0.70:
                    source = 'template'
                elif r < 0.90:
                    source = 'procedural'
                else:
                    source = 'cache'

        if source == 'real_dataset' and real_reader is not None:
            result = real_reader.sample_frames(self.T, self.H, self.W, seed=seed)
            if result is not None:
                return result
            source = 'renderer'

        if source == 'renderer':
            return extract_from_scene_renderer(scene, self.T, self.H, self.W, seed)
        elif source == 'template':
            tidx = int(rng.integers(0, 20))
            return extract_from_templates(scene, self.T, self.H, self.W, tidx, seed)
        elif source == 'cache':
            self._load_video_cache()
            if self._video_cache:
                idx = seed % len(self._video_cache)
                return self._video_cache[idx]
            return _extract_procedural_sequence(scene, self.T, self.H, self.W, seed)
        else:
            return _extract_procedural_sequence(scene, self.T, self.H, self.W, seed)

    def sample_batch(self, scenes: List[str],
                     seeds: Optional[List[int]] = None) -> np.ndarray:
        """
        Sample a batch of frame sequences.
        Returns: (B, T, H, W, 3) float32 in [-1, 1]
        """
        B = len(scenes)
        if seeds is None:
            seeds = list(range(B))
        batch = []
        for i, (scene, seed) in enumerate(zip(scenes, seeds)):
            seq = self.sample(scene, seed=seed)
            batch.append(seq)
        return np.stack(batch, axis=0)

    def sample_subsequence(self, seq: np.ndarray,
                           T_sub: int = 8,
                           start: Optional[int] = None) -> np.ndarray:
        """
        Extract a random contiguous sub-sequence for progressive training.
        seq:   (T, H, W, 3)
        T_sub: length of subsequence to extract
        Returns: (T_sub, H, W, 3)
        """
        T = seq.shape[0]
        if T_sub >= T:
            return seq
        if start is None:
            start = np.random.randint(0, T - T_sub + 1)
        return seq[start:start + T_sub]

    def augment(self, seq: np.ndarray, seed: int = 0) -> np.ndarray:
        """
        Temporal-consistent data augmentation:
        - Horizontal flip (all frames flipped consistently)
        - Brightness/contrast jitter (same params across frames)
        - Temporal reverse (50% probability) — model learns bidirectional motion
        - Frame dropout (5% of frames replaced with adjacent frame blend)
        Returns: (T, H, W, 3) float32 in [-1, 1]
        """
        rng = np.random.default_rng(seed)
        T, H, W, C = seq.shape
        out = seq.copy()

        # Consistent horizontal flip
        if rng.random() < 0.5:
            out = out[:, :, ::-1, :].copy()

        # Brightness jitter (same across all T frames)
        brightness = rng.uniform(-0.15, 0.15)
        out = (out + brightness).clip(-1.0, 1.0)

        # Contrast jitter
        contrast = rng.uniform(0.85, 1.15)
        out = (out * contrast).clip(-1.0, 1.0)

        # Temporal reverse (teaches model temporal symmetry)
        if rng.random() < 0.3:
            out = out[::-1].copy()

        # Frame dropout — blend with neighbor (teaches smooth interpolation)
        for t in range(T):
            if rng.random() < 0.05:
                t_neighbor = min(t + 1, T - 1)
                out[t] = 0.5 * out[t] + 0.5 * out[t_neighbor]

        return out

    @staticmethod
    def to_uint8(seq: np.ndarray) -> np.ndarray:
        """(T, H, W, 3) float32 [-1,1] → uint8 [0,255]"""
        return ((seq + 1.0) * 127.5).clip(0, 255).astype(np.uint8)

    @staticmethod
    def from_uint8(seq: np.ndarray) -> np.ndarray:
        """(T, H, W, 3) uint8 [0,255] → float32 [-1,1]"""
        return seq.astype(np.float32) / 127.5 - 1.0
