stream {
    upstream dns_backend {
        server 127.0.0.1:5353;
    }

    server {
        listen 53 udp;
        listen 53; # tcp
        proxy_pass dns_backend;
        proxy_timeout 3s;
        proxy_responses 1;
    }
}
