import { db } from '../db';
import { distroProviders } from '@shared/schema';
import { eq } from 'drizzle-orm';
import { logger } from '../logger.js';

export const DISTRIBUTION_PLATFORMS = [
  {
    name: 'Spotify',
    slug: 'spotify',
    apiBase: 'https://api.spotify.com/v1',
    authType: 'OAuth2',
    deliveryMethod: 'api',
    processingTime: '1-5 days',
    region: 'global',
    category: 'streaming',
    status: 'active',
    requirements: {
      isrc: true,
      upc: true,
      metadata: ['title', 'artist', 'album'],
      audioFormats: ['WAV', 'FLAC'],
    },
  },
  {
    name: 'Apple Music',
    slug: 'apple-music',
    apiBase: 'https://api.music.apple.com/v1',
    authType: 'JWT',
    deliveryMethod: 'api',
    processingTime: '1-3 days',
    region: 'global',
    category: 'streaming',
    status: 'active',
    requirements: {
      isrc: true,
      upc: true,
      metadata: ['title', 'artist', 'album'],
      audioFormats: ['WAV', 'FLAC'],
    },
  },
  {
    name: 'Amazon Music',
    slug: 'amazon-music',
    apiBase: 'https://api.amazonmusic.com/v1',
    authType: 'AWS_SigV4',
    deliveryMethod: 'api',
    processingTime: '3-7 days',
    region: 'global',
    category: 'streaming',
    status: 'active',
    requirements: {
      isrc: true,
      upc: true,
      metadata: ['title', 'artist', 'album'],
      audioFormats: ['WAV', 'FLAC'],
    },
  },
  {
    name: 'Amazon MP3',
    slug: 'amazon-mp3',
    apiBase: 'https://api.amazonmusic.com/mp3/v1',
    authType: 'AWS_SigV4',
    deliveryMethod: 'api',
    processingTime: '3-7 days',
    region: 'global',
    category: 'store',
    status: 'active',
    requirements: {
      isrc: true,
      upc: true,
      metadata: ['title', 'artist', 'album'],
      audioFormats: ['WAV', 'MP3'],
    },
  },
  {
    name: 'YouTube Music',
    slug: 'youtube-music',
    apiBase: 'https://www.googleapis.com/youtube/v3',
    authType: 'OAuth2',
    deliveryMethod: 'api',
    processingTime: '1-2 days',
    region: 'global',
    category: 'streaming',
    status: 'active',
    requirements: {
      isrc: true,
      upc: false,
      metadata: ['title', 'artist'],
      audioFormats: ['WAV', 'MP3'],
    },
  },
  {
    name: 'Deezer',
    slug: 'deezer',
    apiBase: 'https://api.deezer.com',
    authType: 'OAuth2',
    deliveryMethod: 'api',
    processingTime: '3-7 days',
    region: 'global',
    category: 'streaming',
    status: 'active',
    requirements: {
      isrc: true,
      upc: true,
      metadata: ['title', 'artist', 'album'],
      audioFormats: ['WAV', 'FLAC'],
    },
  },
  {
    name: 'Tidal',
    slug: 'tidal',
    apiBase: 'https://api.tidal.com/v1',
    authType: 'OAuth2',
    deliveryMethod: 'api',
    processingTime: '5-10 days',
    region: 'global',
    category: 'streaming',
    status: 'active',
    requirements: {
      isrc: true,
      upc: true,
      metadata: ['title', 'artist', 'album'],
      audioFormats: ['WAV', 'FLAC'],
    },
  },
  {
    name: 'Pandora',
    slug: 'pandora',
    apiBase: 'https://api.pandora.com/v1',
    authType: 'API_Key',
    deliveryMethod: 'api',
    processingTime: '7-14 days',
    region: 'north_america',
    category: 'streaming',
    status: 'active',
    requirements: {
      isrc: true,
      upc: false,
      metadata: ['title', 'artist', 'album'],
      audioFormats: ['WAV', 'MP3'],
    },
  },
  {
    name: 'iHeartRadio',
    slug: 'iheartradio',
    apiBase: 'https://api.iheart.com/v1',
    authType: 'API_Key',
    deliveryMethod: 'ftp',
    processingTime: '7-14 days',
    region: 'north_america',
    category: 'streaming',
    status: 'active',
    requirements: {
      isrc: true,
      upc: false,
      metadata: ['title', 'artist', 'album'],
      audioFormats: ['WAV', 'MP3'],
    },
  },
  {
    name: 'SoundCloud',
    slug: 'soundcloud',
    apiBase: 'https://api.soundcloud.com',
    authType: 'OAuth2',
    deliveryMethod: 'api',
    processingTime: '1-3 days',
    region: 'global',
    category: 'streaming',
    status: 'active',
    requirements: {
      isrc: false,
      upc: false,
      metadata: ['title', 'artist'],
      audioFormats: ['WAV', 'MP3'],
    },
  },
  {
    name: 'Napster',
    slug: 'napster',
    apiBase: 'https://api.napster.com/v2.2',
    authType: 'API_Key',
    deliveryMethod: 'api',
    processingTime: '5-10 days',
    region: 'global',
    category: 'streaming',
    status: 'active',
    requirements: {
      isrc: true,
      upc: true,
      metadata: ['title', 'artist', 'album'],
      audioFormats: ['WAV', 'FLAC'],
    },
  },
  {
    name: 'TikTok',
    slug: 'tiktok',
    apiBase: 'https://open-api.tiktok.com',
    authType: 'OAuth2',
    deliveryMethod: 'api',
    processingTime: '1-3 days',
    region: 'global',
    category: 'social',
    status: 'active',
    requirements: {
      isrc: false,
      upc: false,
      metadata: ['title', 'artist'],
      audioFormats: ['WAV', 'MP3'],
    },
  },
  {
    name: 'Instagram',
    slug: 'instagram',
    apiBase: 'https://graph.facebook.com/v18.0',
    authType: 'OAuth2',
    deliveryMethod: 'api',
    processingTime: '3-7 days',
    region: 'global',
    category: 'social',
    status: 'active',
    requirements: {
      isrc: false,
      upc: false,
      metadata: ['title', 'artist'],
      audioFormats: ['WAV', 'MP3'],
    },
  },
  {
    name: 'Facebook',
    slug: 'facebook',
    apiBase: 'https://graph.facebook.com/v18.0',
    authType: 'OAuth2',
    deliveryMethod: 'api',
    processingTime: '3-7 days',
    region: 'global',
    category: 'social',
    status: 'active',
    requirements: {
      isrc: false,
      upc: false,
      metadata: ['title', 'artist'],
      audioFormats: ['WAV', 'MP3'],
    },
  },
  {
    name: 'Snapchat',
    slug: 'snapchat',
    apiBase: 'https://adsapi.snapchat.com/v1',
    authType: 'OAuth2',
    deliveryMethod: 'api',
    processingTime: '5-10 days',
    region: 'global',
    category: 'social',
    status: 'active',
    requirements: {
      isrc: false,
      upc: false,
      metadata: ['title', 'artist'],
      audioFormats: ['WAV', 'MP3'],
    },
  },
  {
    name: 'Tencent Music',
    slug: 'tencent-music',
    apiBase: 'https://api.tencentmusic.com/v1',
    authType: 'API_Key',
    deliveryMethod: 'api',
    processingTime: '7-14 days',
    region: 'china',
    category: 'streaming',
    status: 'active',
    requirements: {
      isrc: true,
      upc: true,
      metadata: ['title', 'artist', 'album'],
      audioFormats: ['WAV', 'FLAC'],
    },
  },
  {
    name: 'NetEase Cloud Music',
    slug: 'netease-cloud-music',
    apiBase: 'https://api.music.163.com/api',
    authType: 'API_Key',
    deliveryMethod: 'api',
    processingTime: '7-14 days',
    region: 'china',
    category: 'streaming',
    status: 'active',
    requirements: {
      isrc: true,
      upc: true,
      metadata: ['title', 'artist', 'album'],
      audioFormats: ['WAV', 'FLAC'],
    },
  },
  {
    name: 'JioSaavn',
    slug: 'jiosaavn',
    apiBase: 'https://api.jiosaavn.com/v1',
    authType: 'API_Key',
    deliveryMethod: 'api',
    processingTime: '5-10 days',
    region: 'india',
    category: 'streaming',
    status: 'active',
    requirements: {
      isrc: true,
      upc: false,
      metadata: ['title', 'artist', 'album'],
      audioFormats: ['WAV', 'MP3'],
    },
  },
  {
    name: 'Gaana',
    slug: 'gaana',
    apiBase: 'https://api.gaana.com/v1',
    authType: 'API_Key',
    deliveryMethod: 'api',
    processingTime: '7-14 days',
    region: 'india',
    category: 'streaming',
    status: 'active',
    requirements: {
      isrc: true,
      upc: false,
      metadata: ['title', 'artist', 'album'],
      audioFormats: ['WAV', 'MP3'],
    },
  },
  {
    name: 'Anghami',
    slug: 'anghami',
    apiBase: 'https://api.anghami.com/v1',
    authType: 'OAuth2',
    deliveryMethod: 'api',
    processingTime: '5-10 days',
    region: 'middle_east',
    category: 'streaming',
    status: 'active',
    requirements: {
      isrc: true,
      upc: true,
      metadata: ['title', 'artist', 'album'],
      audioFormats: ['WAV', 'FLAC'],
    },
  },
  {
    name: 'Boomplay',
    slug: 'boomplay',
    apiBase: 'https://api.boomplay.com/v1',
    authType: 'API_Key',
    deliveryMethod: 'api',
    processingTime: '7-14 days',
    region: 'africa',
    category: 'streaming',
    status: 'active',
    requirements: {
      isrc: true,
      upc: false,
      metadata: ['title', 'artist', 'album'],
      audioFormats: ['WAV', 'MP3'],
    },
  },
  {
    name: 'Yandex Music',
    slug: 'yandex-music',
    apiBase: 'https://api.music.yandex.net/v1',
    authType: 'OAuth2',
    deliveryMethod: 'api',
    processingTime: '7-14 days',
    region: 'russia',
    category: 'streaming',
    status: 'active',
    requirements: {
      isrc: true,
      upc: true,
      metadata: ['title', 'artist', 'album'],
      audioFormats: ['WAV', 'FLAC'],
    },
  },
  {
    name: 'Melon',
    slug: 'melon',
    apiBase: 'https://api.melon.com/v1',
    authType: 'API_Key',
    deliveryMethod: 'api',
    processingTime: '7-14 days',
    region: 'korea',
    category: 'streaming',
    status: 'active',
    requirements: {
      isrc: true,
      upc: true,
      metadata: ['title', 'artist', 'album'],
      audioFormats: ['WAV', 'FLAC'],
    },
  },
  {
    name: 'KKBOX',
    slug: 'kkbox',
    apiBase: 'https://api.kkbox.com/v1.1',
    authType: 'OAuth2',
    deliveryMethod: 'api',
    processingTime: '5-10 days',
    region: 'taiwan',
    category: 'streaming',
    status: 'active',
    requirements: {
      isrc: true,
      upc: true,
      metadata: ['title', 'artist', 'album'],
      audioFormats: ['WAV', 'FLAC'],
    },
  },
  {
    name: 'VK Music',
    slug: 'vk-music',
    apiBase: 'https://api.vk.com/method',
    authType: 'OAuth2',
    deliveryMethod: 'api',
    processingTime: '7-14 days',
    region: 'russia',
    category: 'streaming',
    status: 'active',
    requirements: {
      isrc: true,
      upc: false,
      metadata: ['title', 'artist', 'album'],
      audioFormats: ['WAV', 'MP3'],
    },
  },
  {
    name: 'Joox',
    slug: 'joox',
    apiBase: 'https://api.joox.com/v1',
    authType: 'API_Key',
    deliveryMethod: 'api',
    processingTime: '7-14 days',
    region: 'asia',
    category: 'streaming',
    status: 'active',
    requirements: {
      isrc: true,
      upc: false,
      metadata: ['title', 'artist', 'album'],
      audioFormats: ['WAV', 'MP3'],
    },
  },
  {
    name: '7digital',
    slug: '7digital',
    apiBase: 'https://api.7digital.com/1.2',
    authType: 'OAuth1',
    deliveryMethod: 'api',
    processingTime: '5-10 days',
    region: 'global',
    category: 'store',
    status: 'active',
    requirements: {
      isrc: true,
      upc: true,
      metadata: ['title', 'artist', 'album'],
      audioFormats: ['WAV', 'FLAC'],
    },
  },
  {
    name: 'Qobuz',
    slug: 'qobuz',
    apiBase: 'https://api.qobuz.com/v1',
    authType: 'API_Key',
    deliveryMethod: 'api',
    processingTime: '7-14 days',
    region: 'europe',
    category: 'store',
    status: 'active',
    requirements: {
      isrc: true,
      upc: true,
      metadata: ['title', 'artist', 'album'],
      audioFormats: ['WAV', 'FLAC'],
    },
  },
  {
    name: 'MediaNet',
    slug: 'medianet',
    apiBase: 'https://api.mndigital.com/v1',
    authType: 'API_Key',
    deliveryMethod: 'api',
    processingTime: '10-14 days',
    region: 'global',
    category: 'store',
    status: 'active',
    requirements: {
      isrc: true,
      upc: true,
      metadata: ['title', 'artist', 'album'],
      audioFormats: ['WAV', 'FLAC'],
    },
  },
  {
    name: 'Gracenote',
    slug: 'gracenote',
    apiBase: 'https://api.gracenote.com/v1',
    authType: 'API_Key',
    deliveryMethod: 'api',
    processingTime: '3-7 days',
    region: 'global',
    category: 'metadata',
    status: 'active',
    requirements: {
      isrc: true,
      upc: true,
      metadata: ['title', 'artist', 'album'],
      audioFormats: ['WAV', 'FLAC'],
    },
  },
  {
    name: 'Shazam',
    slug: 'shazam',
    apiBase: 'https://api.shazam.com/v1',
    authType: 'API_Key',
    deliveryMethod: 'api',
    processingTime: '5-10 days',
    region: 'global',
    category: 'discovery',
    status: 'active',
    requirements: {
      isrc: true,
      upc: false,
      metadata: ['title', 'artist'],
      audioFormats: ['WAV', 'MP3'],
    },
  },
  {
    name: 'Trebel',
    slug: 'trebel',
    apiBase: 'https://api.trebelmusic.com/v1',
    authType: 'API_Key',
    deliveryMethod: 'api',
    processingTime: '7-14 days',
    region: 'latin_america',
    category: 'streaming',
    status: 'active',
    requirements: {
      isrc: true,
      upc: false,
      metadata: ['title', 'artist', 'album'],
      audioFormats: ['WAV', 'MP3'],
    },
  },
  {
    name: 'Audiomack',
    slug: 'audiomack',
    apiBase: 'https://api.audiomack.com/v1',
    authType: 'OAuth2',
    deliveryMethod: 'api',
    processingTime: '3-7 days',
    region: 'global',
    category: 'streaming',
    status: 'active',
    requirements: {
      isrc: false,
      upc: false,
      metadata: ['title', 'artist'],
      audioFormats: ['WAV', 'MP3'],
    },
  },
  {
    name: 'Claro Música',
    slug: 'claro-musica',
    apiBase: 'https://api.claromusica.com/v1',
    authType: 'API_Key',
    deliveryMethod: 'api',
    processingTime: '10-14 days',
    region: 'latin_america',
    category: 'streaming',
    status: 'active',
    requirements: {
      isrc: true,
      upc: false,
      metadata: ['title', 'artist', 'album'],
      audioFormats: ['WAV', 'MP3'],
    },
  },
];

/**
 * TODO: Add function documentation
 */
export async function seedDistributionPlatforms() {
  logger.info('🌱 Seeding distribution platforms...');

  try {
    for (const platform of DISTRIBUTION_PLATFORMS) {
      const [existing] = await db
        .select()
        .from(distroProviders)
        .where(eq(distroProviders.slug, platform.slug))
        .limit(1);

      if (!existing) {
        await db.insert(distroProviders).values(platform);
        logger.info(`  ✅ Added platform: ${platform.name}`);
      } else {
        logger.info(`  ⏭️  Platform exists: ${platform.name}`);
      }
    }

    logger.info(
      `✅ Distribution platform seeding complete! ${DISTRIBUTION_PLATFORMS.length} platforms available.`
    );
  } catch (error: unknown) {
    logger.error('❌ Error seeding distribution platforms:', error);
    throw error;
  }
}
