/**
 * readiness-gauge — report renderers (Markdown and JSON).
 */
import type { CheckStatus, GaugeReport, ScoredCheck, Verdict } from "./types.js";

const STATUS_ICON: Record<CheckStatus, string> = {
  pass: "✅",
  warn: "⚠️",
  fail: "❌",
  blocked: "🚫",
};

const VERDICT_LINE: Record<Verdict, string> = {
  GO: "## Verdict: GO — cleared for production",
  "CONDITIONAL GO": "## Verdict: CONDITIONAL GO — ship with the conditions below",
  "NO GO": "## Verdict: NO GO — do not ship",
};

function fmtDuration(ms: number): string {
  if (ms < 1000) return `${ms}ms`;
  return `${(ms / 1000).toFixed(1)}s`;
}

function checkSection(s: ScoredCheck): string {
  const lines: string[] = [];
  const req = s.required ? " · **required**" : "";
  const pts = s.points === null ? "excluded" : `${s.points}/100`;
  lines.push(
    `### ${STATUS_ICON[s.status]} ${s.name} \`${s.id}\``,
    ``,
    `- Status: **${s.status.toUpperCase()}** · Weight: ${s.weight}${req} · Score: ${pts} · ${fmtDuration(s.durationMs)}`,
    `- Category: ${s.category}`,
    `- ${s.summary}`,
  );
  if (s.evidence.length > 0) {
    lines.push(``, `<details>`, `<summary>Evidence</summary>`, ``);
    for (const e of s.evidence.slice(0, 15)) lines.push(`- \`${e}\``);
    lines.push(``, `</details>`);
  }
  if (s.remediation) lines.push(``, `> Remediation: ${s.remediation}`);
  return lines.join("\n");
}

export function renderMarkdown(report: GaugeReport): string {
  const lines: string[] = [];
  const scoreLine =
    report.score === null ? "n/a (no checks scored)" : `${report.score}/100`;
  lines.push(
    `# Production Readiness Gauge`,
    ``,
    `- Profile: **${report.profile.displayName}** (\`${report.profile.name}\` v${report.profile.version})`,
    `- Generated: ${report.generatedAt}`,
    `- Repository: \`${report.cwd}\``,
    `- **Score: ${scoreLine}**`,
    ``,
    VERDICT_LINE[report.verdict],
    ``,
    `Thresholds: GO ≥ ${report.thresholds.go} · CONDITIONAL GO ≥ ${report.thresholds.conditionalGo}`,
    ``,
    `### Why this verdict`,
    ``,
  );
  for (const r of report.verdictReasons) lines.push(`- ${r}`);
  lines.push(``, `### Score by category`, ``);
  lines.push(`| Category | Checks | Score |`);
  lines.push(`| --- | ---: | ---: |`);
  for (const c of report.categories) {
    lines.push(`| ${c.category} | ${c.checks} | ${c.score === null ? "n/a" : c.score} |`);
  }
  lines.push(``, `### Checks`, ``);
  for (const s of report.checks) {
    lines.push(checkSection(s), ``);
  }
  lines.push(
    `---`,
    ``,
    `Tune this gauge: copy \`scripts/readiness-gauge/profiles/${report.profile.name}.json\`, adjust weights / required flags / thresholds, and rerun with \`--profile-file <path>\`. See \`scripts/readiness-gauge/READINESS_GAUGE.md\`.`,
    ``,
    `_Generated by readiness-gauge v${report.toolVersion}._`,
  );
  return lines.join("\n") + "\n";
}

export function renderJson(report: GaugeReport): string {
  return JSON.stringify(report, null, 2) + "\n";
}
