export {
  type AspectRatio,
  type Platform,
  type AspectRatioConfig,
  type ColorPalette,
  type BackgroundType,
  type BackgroundConfig,
  type TextLayerConfig,
  type LogoConfig,
  type CallToActionConfig,
  type AudioReactiveConfig,
  type BaseTemplateOptions,
  type ReleaseAnnouncementOptions,
  type TourEventOptions,
  type BehindTheScenesOptions,
  type QuoteLyricOptions,
  type CountdownTimerOptions,
  type SplitScreenOptions,
  type SocialTeaserOptions,
  type PromoTemplateOptions,
  type TemplateLayer,
  type CompiledTemplate,
  ASPECT_RATIOS,
  DEFAULT_PALETTES,
  compileReleaseAnnouncement,
  compileTourEvent,
  compileBehindTheScenes,
  compileQuoteLyric,
  compileCountdownTimer,
  compileSplitScreen,
  compileSocialTeaser,
  compileTemplate,
} from './PromoTemplates';

export {
  type TemplateType,
  type TemplateMetadata,
  type TemplatePreset,
  type TemplateCustomization,
  type TemplatePreviewConfig,
  type ExportedTemplateConfig,
  TemplateManager,
  templateManager,
} from './TemplateManager';
