import type { PluginDefinition } from "../server/services/pluginHostService";

const MbFlangerPlugin: PluginDefinition = {
  id: "mb-flanger",
  slug: "mb-flanger",
  name: "MB Flanger",
  category: "effect",
  type: "flanger",
  version: "1.0.0",
  description: "Vintage flanger with through-zero capability",
  author: "Max Booster",
  grade: "A",
  parameters: [
    {
      id: "rate",
      name: "Rate",
      type: "float",
      defaultValue: 0.3,
      minValue: 0.01,
      maxValue: 10,
      automatable: true,
    },
    {
      id: "depth",
      name: "Depth",
      type: "float",
      defaultValue: 0.6,
      minValue: 0,
      maxValue: 1,
      automatable: true,
    },
    {
      id: "delay",
      name: "Delay",
      type: "float",
      defaultValue: 5,
      minValue: 0.5,
      maxValue: 20,
      automatable: true,
    },
    {
      id: "feedback",
      name: "Feedback",
      type: "float",
      defaultValue: 0.5,
      minValue: -0.99,
      maxValue: 0.99,
      automatable: true,
    },
    {
      id: "mix",
      name: "Mix",
      type: "float",
      defaultValue: 0.5,
      minValue: 0,
      maxValue: 1,
      automatable: true,
    },
    {
      id: "stereoPhase",
      name: "Stereo Phase",
      type: "float",
      defaultValue: 0.25,
      minValue: 0,
      maxValue: 0.5,
      automatable: true,
    },
  ],
  defaultPreset: {
    rate: 0.3,
    depth: 0.6,
    delay: 5,
    feedback: 0.5,
    mix: 0.5,
    stereoPhase: 0.25,
  },
};

export default MbFlangerPlugin;
