import type { PluginDefinition } from "../server/services/pluginHostService";

const MbMultibandCompressorPlugin: PluginDefinition = {
  id: "mb-multiband-compressor",
  slug: "mb-multiband-compressor",
  name: "MB Multiband Compressor",
  category: "effect",
  type: "compressor",
  version: "1.0.0",
  description:
    "Professional 4-band dynamics processor for mixing and mastering",
  author: "Max Booster",
  grade: "A",
  parameters: [
    {
      id: "crossover_low",
      name: "Low Crossover",
      type: "float",
      defaultValue: 100,
      minValue: 20,
      maxValue: 500,
      unit: "Hz",
      automatable: true,
    },
    {
      id: "crossover_mid",
      name: "Mid Crossover",
      type: "float",
      defaultValue: 1000,
      minValue: 200,
      maxValue: 5000,
      unit: "Hz",
      automatable: true,
    },
    {
      id: "crossover_high",
      name: "High Crossover",
      type: "float",
      defaultValue: 8000,
      minValue: 2000,
      maxValue: 16000,
      unit: "Hz",
      automatable: true,
    },
    {
      id: "low_threshold",
      name: "Low Threshold",
      type: "float",
      defaultValue: -20,
      minValue: -60,
      maxValue: 0,
      unit: "dB",
      automatable: true,
    },
    {
      id: "low_ratio",
      name: "Low Ratio",
      type: "float",
      defaultValue: 4,
      minValue: 1,
      maxValue: 20,
      automatable: true,
    },
    {
      id: "mid_threshold",
      name: "Mid Threshold",
      type: "float",
      defaultValue: -18,
      minValue: -60,
      maxValue: 0,
      unit: "dB",
      automatable: true,
    },
    {
      id: "mid_ratio",
      name: "Mid Ratio",
      type: "float",
      defaultValue: 3,
      minValue: 1,
      maxValue: 20,
      automatable: true,
    },
    {
      id: "high_threshold",
      name: "High Threshold",
      type: "float",
      defaultValue: -15,
      minValue: -60,
      maxValue: 0,
      unit: "dB",
      automatable: true,
    },
    {
      id: "high_ratio",
      name: "High Ratio",
      type: "float",
      defaultValue: 2,
      minValue: 1,
      maxValue: 20,
      automatable: true,
    },
    {
      id: "output",
      name: "Output Gain",
      type: "float",
      defaultValue: 0,
      minValue: -12,
      maxValue: 12,
      unit: "dB",
      automatable: true,
    },
  ],
  defaultPreset: {
    crossover_low: 100,
    crossover_mid: 1000,
    crossover_high: 8000,
    low_threshold: -20,
    low_ratio: 4,
    mid_threshold: -18,
    mid_ratio: 3,
    high_threshold: -15,
    high_ratio: 2,
    output: 0,
  },
};

export default MbMultibandCompressorPlugin;
