import type { PluginDefinition } from "../server/services/pluginHostService";

const MbOrganPlugin: PluginDefinition = {
  id: "mb-organ",
  slug: "mb-organ",
  name: "MB Tonewheel Organ",
  category: "instrument",
  type: "synth",
  version: "1.0.0",
  description:
    "Classic tonewheel organ with drawbars and rotary speaker simulation",
  author: "Max Booster",
  grade: "A",
  oscillators: [
    { type: "sine", detune: -1200, gain: 0 },
    { type: "sine", detune: -700, gain: 0 },
    { type: "sine", detune: 0, gain: 0.8 },
    { type: "sine", detune: 1200, gain: 0.6 },
    { type: "sine", detune: 1900, gain: 0.4 },
    { type: "sine", detune: 2400, gain: 0.3 },
    { type: "sine", detune: 2800, gain: 0.2 },
    { type: "sine", detune: 3100, gain: 0.1 },
    { type: "sine", detune: 3600, gain: 0.05 },
  ],
  envelope: { attack: 0.005, decay: 0, sustain: 1, release: 0.1 },
  parameters: [
    {
      id: "drawbar_16",
      name: "16' Drawbar",
      type: "int",
      defaultValue: 0,
      minValue: 0,
      maxValue: 8,
      automatable: true,
    },
    {
      id: "drawbar_513",
      name: "5 1/3' Drawbar",
      type: "int",
      defaultValue: 0,
      minValue: 0,
      maxValue: 8,
      automatable: true,
    },
    {
      id: "drawbar_8",
      name: "8' Drawbar",
      type: "int",
      defaultValue: 8,
      minValue: 0,
      maxValue: 8,
      automatable: true,
    },
    {
      id: "drawbar_4",
      name: "4' Drawbar",
      type: "int",
      defaultValue: 6,
      minValue: 0,
      maxValue: 8,
      automatable: true,
    },
    {
      id: "drawbar_223",
      name: "2 2/3' Drawbar",
      type: "int",
      defaultValue: 4,
      minValue: 0,
      maxValue: 8,
      automatable: true,
    },
    {
      id: "drawbar_2",
      name: "2' Drawbar",
      type: "int",
      defaultValue: 3,
      minValue: 0,
      maxValue: 8,
      automatable: true,
    },
    {
      id: "percussion",
      name: "Percussion",
      type: "bool",
      defaultValue: true,
      automatable: false,
    },
    {
      id: "leslie_speed",
      name: "Leslie Speed",
      type: "choice",
      defaultValue: "slow",
      choices: ["stop", "slow", "fast"],
      automatable: true,
    },
    {
      id: "leslie_depth",
      name: "Leslie Depth",
      type: "float",
      defaultValue: 0.5,
      minValue: 0,
      maxValue: 1,
      automatable: true,
    },
    {
      id: "overdrive",
      name: "Overdrive",
      type: "float",
      defaultValue: 0.3,
      minValue: 0,
      maxValue: 1,
      automatable: true,
    },
    {
      id: "volume",
      name: "Volume",
      type: "float",
      defaultValue: 0.8,
      minValue: 0,
      maxValue: 1,
      automatable: true,
    },
  ],
  defaultPreset: {
    drawbar_16: 0,
    drawbar_513: 0,
    drawbar_8: 8,
    drawbar_4: 6,
    drawbar_223: 4,
    drawbar_2: 3,
    percussion: true,
    leslie_speed: "slow",
    leslie_depth: 0.5,
    overdrive: 0.3,
    volume: 0.8,
  },
};

export default MbOrganPlugin;
