import type { PluginDefinition } from "../server/services/pluginHostService";

const MbTapeSaturationPlugin: PluginDefinition = {
  id: "mb-tape-saturation",
  slug: "mb-tape-saturation",
  name: "MB Tape Saturation",
  category: "effect",
  type: "distortion",
  version: "1.0.0",
  description: "Warm analog tape emulation with compression and harmonics",
  author: "Max Booster",
  grade: "A",
  parameters: [
    {
      id: "input_gain",
      name: "Input Gain",
      type: "float",
      defaultValue: 0,
      minValue: -12,
      maxValue: 24,
      unit: "dB",
      automatable: true,
    },
    {
      id: "saturation",
      name: "Saturation",
      type: "float",
      defaultValue: 0.5,
      minValue: 0,
      maxValue: 1,
      automatable: true,
    },
    {
      id: "tape_speed",
      name: "Tape Speed",
      type: "choice",
      defaultValue: "15ips",
      choices: ["7.5ips", "15ips", "30ips"],
      automatable: false,
    },
    {
      id: "bias",
      name: "Bias",
      type: "float",
      defaultValue: 0.5,
      minValue: 0,
      maxValue: 1,
      automatable: true,
    },
    {
      id: "wow_flutter",
      name: "Wow & Flutter",
      type: "float",
      defaultValue: 0.1,
      minValue: 0,
      maxValue: 1,
      automatable: true,
    },
    {
      id: "noise",
      name: "Tape Noise",
      type: "float",
      defaultValue: 0,
      minValue: 0,
      maxValue: 1,
      automatable: true,
    },
    {
      id: "output_gain",
      name: "Output Gain",
      type: "float",
      defaultValue: 0,
      minValue: -12,
      maxValue: 12,
      unit: "dB",
      automatable: true,
    },
    {
      id: "mix",
      name: "Mix",
      type: "float",
      defaultValue: 1,
      minValue: 0,
      maxValue: 1,
      automatable: true,
    },
  ],
  defaultPreset: {
    input_gain: 0,
    saturation: 0.5,
    tape_speed: "15ips",
    bias: 0.5,
    wow_flutter: 0.1,
    noise: 0,
    output_gain: 0,
    mix: 1,
  },
};

export default MbTapeSaturationPlugin;
