import type { PluginDefinition } from "../server/services/pluginHostService";

const MbTimeGrainDelayPlugin: PluginDefinition = {
  id: "mb-time-grain-delay",
  slug: "mb-time-grain-delay",
  name: "MB Grain Delay",
  category: "effect",
  type: "delay" as any,
  version: "1.0.0",
  description: "Granular delay with pitch, density, and size randomization",
  author: "Max Booster",
  grade: "A",
  parameters: [
    {
      id: "time",
      name: "Time",
      type: "float",
      defaultValue: 300,
      minValue: 10,
      maxValue: 2000,
      automatable: true,
    },
    {
      id: "grainSize",
      name: "Grain Size",
      type: "float",
      defaultValue: 50,
      minValue: 5,
      maxValue: 500,
      automatable: true,
    },
    {
      id: "density",
      name: "Density",
      type: "float",
      defaultValue: 0.5,
      minValue: 0,
      maxValue: 1,
      automatable: true,
    },
    {
      id: "pitch",
      name: "Pitch",
      type: "float",
      defaultValue: 0,
      minValue: -24,
      maxValue: 24,
      automatable: true,
    },
    {
      id: "feedback",
      name: "Feedback",
      type: "float",
      defaultValue: 0.3,
      minValue: 0,
      maxValue: 0.95,
      automatable: true,
    },
    {
      id: "mix",
      name: "Mix",
      type: "float",
      defaultValue: 0.5,
      minValue: 0,
      maxValue: 1,
      automatable: true,
    },
  ],
  defaultPreset: {
    time: 300,
    grainSize: 50,
    density: 0.5,
    pitch: 0,
    feedback: 0.3,
    mix: 0.5,
  },
};

export default MbTimeGrainDelayPlugin;
