import type { PluginDefinition } from "../server/services/pluginHostService";

const MbVinylSimulatorPlugin: PluginDefinition = {
  id: "mb-vinyl-simulator",
  slug: "mb-vinyl-simulator",
  name: "MB Vinyl Simulator",
  category: "effect",
  type: "distortion",
  version: "1.0.0",
  description: "Authentic vinyl record emulation with crackle and warmth",
  author: "Max Booster",
  grade: "A",
  parameters: [
    {
      id: "year",
      name: "Year",
      type: "choice",
      defaultValue: "1970s",
      choices: ["1950s", "1960s", "1970s", "1980s", "1990s"],
      automatable: false,
    },
    {
      id: "wear",
      name: "Wear",
      type: "float",
      defaultValue: 0.3,
      minValue: 0,
      maxValue: 1,
      automatable: true,
    },
    {
      id: "crackle",
      name: "Crackle",
      type: "float",
      defaultValue: 0.2,
      minValue: 0,
      maxValue: 1,
      automatable: true,
    },
    {
      id: "dust",
      name: "Dust",
      type: "float",
      defaultValue: 0.1,
      minValue: 0,
      maxValue: 1,
      automatable: true,
    },
    {
      id: "warp",
      name: "Warp",
      type: "float",
      defaultValue: 0,
      minValue: 0,
      maxValue: 1,
      automatable: true,
    },
    {
      id: "mechanical",
      name: "Mechanical Noise",
      type: "float",
      defaultValue: 0.1,
      minValue: 0,
      maxValue: 1,
      automatable: true,
    },
    {
      id: "low_boost",
      name: "Low Boost",
      type: "float",
      defaultValue: 0.3,
      minValue: 0,
      maxValue: 1,
      automatable: true,
    },
    {
      id: "high_roll",
      name: "High Roll-off",
      type: "float",
      defaultValue: 0.4,
      minValue: 0,
      maxValue: 1,
      automatable: true,
    },
    {
      id: "mix",
      name: "Mix",
      type: "float",
      defaultValue: 1,
      minValue: 0,
      maxValue: 1,
      automatable: true,
    },
  ],
  defaultPreset: {
    year: "1970s",
    wear: 0.3,
    crackle: 0.2,
    dust: 0.1,
    warp: 0,
    mechanical: 0.1,
    low_boost: 0.3,
    high_roll: 0.4,
    mix: 1,
  },
};

export default MbVinylSimulatorPlugin;
