import type { PluginDefinition } from '../pluginHostService';

export const REVERB_PLUGINS: PluginDefinition[] = [
  { id: 'mb-reverb-hall', slug: 'mb-reverb-hall', name: 'MB Hall Reverb', category: 'effect', type: 'reverb', version: '1.0.0', description: 'Large concert hall reverb', author: 'Max Booster', parameters: [{ id: 'size', name: 'Size', type: 'float', defaultValue: 0.8, minValue: 0, maxValue: 1, automatable: true }, { id: 'decay', name: 'Decay', type: 'float', defaultValue: 3.0, minValue: 0.5, maxValue: 10, automatable: true }, { id: 'mix', name: 'Mix', type: 'float', defaultValue: 0.3, minValue: 0, maxValue: 1, automatable: true }], defaultPreset: { size: 0.8, decay: 3.0, mix: 0.3 } },
  { id: 'mb-reverb-room', slug: 'mb-reverb-room', name: 'MB Room Reverb', category: 'effect', type: 'reverb', version: '1.0.0', description: 'Natural room ambience', author: 'Max Booster', parameters: [{ id: 'size', name: 'Size', type: 'float', defaultValue: 0.4, minValue: 0, maxValue: 1, automatable: true }, { id: 'decay', name: 'Decay', type: 'float', defaultValue: 1.2, minValue: 0.2, maxValue: 4, automatable: true }, { id: 'mix', name: 'Mix', type: 'float', defaultValue: 0.25, minValue: 0, maxValue: 1, automatable: true }], defaultPreset: { size: 0.4, decay: 1.2, mix: 0.25 } },
  { id: 'mb-reverb-plate', slug: 'mb-reverb-plate', name: 'MB Plate Reverb', category: 'effect', type: 'reverb', version: '1.0.0', description: 'Classic plate reverb', author: 'Max Booster', parameters: [{ id: 'size', name: 'Size', type: 'float', defaultValue: 0.6, minValue: 0, maxValue: 1, automatable: true }, { id: 'decay', name: 'Decay', type: 'float', defaultValue: 2.0, minValue: 0.5, maxValue: 6, automatable: true }, { id: 'mix', name: 'Mix', type: 'float', defaultValue: 0.35, minValue: 0, maxValue: 1, automatable: true }], defaultPreset: { size: 0.6, decay: 2.0, mix: 0.35 } },
  { id: 'mb-reverb-spring', slug: 'mb-reverb-spring', name: 'MB Spring Reverb', category: 'effect', type: 'reverb', version: '1.0.0', description: 'Vintage spring reverb', author: 'Max Booster', parameters: [{ id: 'tension', name: 'Tension', type: 'float', defaultValue: 0.5, minValue: 0, maxValue: 1, automatable: true }, { id: 'decay', name: 'Decay', type: 'float', defaultValue: 1.5, minValue: 0.3, maxValue: 4, automatable: true }, { id: 'mix', name: 'Mix', type: 'float', defaultValue: 0.3, minValue: 0, maxValue: 1, automatable: true }], defaultPreset: { tension: 0.5, decay: 1.5, mix: 0.3 } },
  { id: 'mb-reverb-chamber', slug: 'mb-reverb-chamber', name: 'MB Chamber Reverb', category: 'effect', type: 'reverb', version: '1.0.0', description: 'Echo chamber reverb', author: 'Max Booster', parameters: [{ id: 'size', name: 'Size', type: 'float', defaultValue: 0.5, minValue: 0, maxValue: 1, automatable: true }, { id: 'decay', name: 'Decay', type: 'float', defaultValue: 2.5, minValue: 0.5, maxValue: 8, automatable: true }, { id: 'mix', name: 'Mix', type: 'float', defaultValue: 0.3, minValue: 0, maxValue: 1, automatable: true }], defaultPreset: { size: 0.5, decay: 2.5, mix: 0.3 } },
  { id: 'mb-reverb-shimmer', slug: 'mb-reverb-shimmer', name: 'MB Shimmer Reverb', category: 'effect', type: 'reverb', version: '1.0.0', description: 'Pitched shimmer reverb', author: 'Max Booster', parameters: [{ id: 'shimmer', name: 'Shimmer', type: 'float', defaultValue: 0.6, minValue: 0, maxValue: 1, automatable: true }, { id: 'decay', name: 'Decay', type: 'float', defaultValue: 4.0, minValue: 1, maxValue: 15, automatable: true }, { id: 'mix', name: 'Mix', type: 'float', defaultValue: 0.4, minValue: 0, maxValue: 1, automatable: true }], defaultPreset: { shimmer: 0.6, decay: 4.0, mix: 0.4 } },
  { id: 'mb-reverb-cathedral', slug: 'mb-reverb-cathedral', name: 'MB Cathedral', category: 'effect', type: 'reverb', version: '1.0.0', description: 'Massive cathedral space', author: 'Max Booster', parameters: [{ id: 'size', name: 'Size', type: 'float', defaultValue: 1.0, minValue: 0, maxValue: 1, automatable: true }, { id: 'decay', name: 'Decay', type: 'float', defaultValue: 6.0, minValue: 2, maxValue: 20, automatable: true }, { id: 'mix', name: 'Mix', type: 'float', defaultValue: 0.35, minValue: 0, maxValue: 1, automatable: true }], defaultPreset: { size: 1.0, decay: 6.0, mix: 0.35 } },
  { id: 'mb-reverb-ambient', slug: 'mb-reverb-ambient', name: 'MB Ambient Verb', category: 'effect', type: 'reverb', version: '1.0.0', description: 'Ethereal ambient reverb', author: 'Max Booster', parameters: [{ id: 'space', name: 'Space', type: 'float', defaultValue: 0.9, minValue: 0, maxValue: 1, automatable: true }, { id: 'decay', name: 'Decay', type: 'float', defaultValue: 8.0, minValue: 2, maxValue: 30, automatable: true }, { id: 'mix', name: 'Mix', type: 'float', defaultValue: 0.5, minValue: 0, maxValue: 1, automatable: true }], defaultPreset: { space: 0.9, decay: 8.0, mix: 0.5 } },
  { id: 'mb-reverb-gated', slug: 'mb-reverb-gated', name: 'MB Gated Reverb', category: 'effect', type: 'reverb', version: '1.0.0', description: '80s gated reverb', author: 'Max Booster', parameters: [{ id: 'gate', name: 'Gate Time', type: 'float', defaultValue: 0.3, minValue: 0.1, maxValue: 1, automatable: true }, { id: 'size', name: 'Size', type: 'float', defaultValue: 0.7, minValue: 0, maxValue: 1, automatable: true }, { id: 'mix', name: 'Mix', type: 'float', defaultValue: 0.4, minValue: 0, maxValue: 1, automatable: true }], defaultPreset: { gate: 0.3, size: 0.7, mix: 0.4 } },
  { id: 'mb-reverb-convolution', slug: 'mb-reverb-convolution', name: 'MB Convolution', category: 'effect', type: 'reverb', version: '1.0.0', description: 'IR convolution reverb', author: 'Max Booster', parameters: [{ id: 'ir', name: 'Impulse', type: 'float', defaultValue: 0.5, minValue: 0, maxValue: 1, automatable: true }, { id: 'predelay', name: 'Pre-delay', type: 'float', defaultValue: 20, minValue: 0, maxValue: 200, automatable: true }, { id: 'mix', name: 'Mix', type: 'float', defaultValue: 0.3, minValue: 0, maxValue: 1, automatable: true }], defaultPreset: { ir: 0.5, predelay: 20, mix: 0.3 } },
];

export const DELAY_PLUGINS: PluginDefinition[] = [
  { id: 'mb-delay-stereo', slug: 'mb-delay-stereo', name: 'MB Stereo Delay', category: 'effect', type: 'delay', version: '1.0.0', description: 'Classic stereo delay', author: 'Max Booster', parameters: [{ id: 'time', name: 'Time', type: 'float', defaultValue: 250, minValue: 1, maxValue: 2000, automatable: true }, { id: 'feedback', name: 'Feedback', type: 'float', defaultValue: 0.4, minValue: 0, maxValue: 0.95, automatable: true }, { id: 'mix', name: 'Mix', type: 'float', defaultValue: 0.3, minValue: 0, maxValue: 1, automatable: true }], defaultPreset: { time: 250, feedback: 0.4, mix: 0.3 } },
  { id: 'mb-delay-pingpong', slug: 'mb-delay-pingpong', name: 'MB Ping Pong', category: 'effect', type: 'delay', version: '1.0.0', description: 'Bouncing ping pong delay', author: 'Max Booster', parameters: [{ id: 'time', name: 'Time', type: 'float', defaultValue: 375, minValue: 1, maxValue: 2000, automatable: true }, { id: 'feedback', name: 'Feedback', type: 'float', defaultValue: 0.5, minValue: 0, maxValue: 0.95, automatable: true }, { id: 'mix', name: 'Mix', type: 'float', defaultValue: 0.35, minValue: 0, maxValue: 1, automatable: true }], defaultPreset: { time: 375, feedback: 0.5, mix: 0.35 } },
  { id: 'mb-delay-tape', slug: 'mb-delay-tape', name: 'MB Tape Delay', category: 'effect', type: 'delay', version: '1.0.0', description: 'Warm tape echo', author: 'Max Booster', parameters: [{ id: 'time', name: 'Time', type: 'float', defaultValue: 300, minValue: 50, maxValue: 1500, automatable: true }, { id: 'feedback', name: 'Feedback', type: 'float', defaultValue: 0.45, minValue: 0, maxValue: 0.9, automatable: true }, { id: 'saturation', name: 'Saturation', type: 'float', defaultValue: 0.4, minValue: 0, maxValue: 1, automatable: true }, { id: 'mix', name: 'Mix', type: 'float', defaultValue: 0.3, minValue: 0, maxValue: 1, automatable: true }], defaultPreset: { time: 300, feedback: 0.45, saturation: 0.4, mix: 0.3 } },
  { id: 'mb-delay-analog', slug: 'mb-delay-analog', name: 'MB Analog Delay', category: 'effect', type: 'delay', version: '1.0.0', description: 'BBD-style analog delay', author: 'Max Booster', parameters: [{ id: 'time', name: 'Time', type: 'float', defaultValue: 200, minValue: 20, maxValue: 800, automatable: true }, { id: 'feedback', name: 'Feedback', type: 'float', defaultValue: 0.5, minValue: 0, maxValue: 0.9, automatable: true }, { id: 'color', name: 'Color', type: 'float', defaultValue: 0.5, minValue: 0, maxValue: 1, automatable: true }, { id: 'mix', name: 'Mix', type: 'float', defaultValue: 0.35, minValue: 0, maxValue: 1, automatable: true }], defaultPreset: { time: 200, feedback: 0.5, color: 0.5, mix: 0.35 } },
  { id: 'mb-delay-slapback', slug: 'mb-delay-slapback', name: 'MB Slapback', category: 'effect', type: 'delay', version: '1.0.0', description: 'Short slapback echo', author: 'Max Booster', parameters: [{ id: 'time', name: 'Time', type: 'float', defaultValue: 80, minValue: 30, maxValue: 150, automatable: true }, { id: 'feedback', name: 'Feedback', type: 'float', defaultValue: 0.1, minValue: 0, maxValue: 0.5, automatable: true }, { id: 'mix', name: 'Mix', type: 'float', defaultValue: 0.4, minValue: 0, maxValue: 1, automatable: true }], defaultPreset: { time: 80, feedback: 0.1, mix: 0.4 } },
  { id: 'mb-delay-multi', slug: 'mb-delay-multi', name: 'MB Multi-Tap', category: 'effect', type: 'delay', version: '1.0.0', description: 'Multi-tap rhythm delay', author: 'Max Booster', parameters: [{ id: 'taps', name: 'Taps', type: 'float', defaultValue: 4, minValue: 2, maxValue: 8, automatable: false }, { id: 'time', name: 'Time', type: 'float', defaultValue: 500, minValue: 100, maxValue: 2000, automatable: true }, { id: 'mix', name: 'Mix', type: 'float', defaultValue: 0.35, minValue: 0, maxValue: 1, automatable: true }], defaultPreset: { taps: 4, time: 500, mix: 0.35 } },
  { id: 'mb-delay-mod', slug: 'mb-delay-mod', name: 'MB Modulated Delay', category: 'effect', type: 'delay', version: '1.0.0', description: 'Modulated delay with chorus', author: 'Max Booster', parameters: [{ id: 'time', name: 'Time', type: 'float', defaultValue: 350, minValue: 50, maxValue: 1500, automatable: true }, { id: 'modRate', name: 'Mod Rate', type: 'float', defaultValue: 0.5, minValue: 0.1, maxValue: 5, automatable: true }, { id: 'modDepth', name: 'Mod Depth', type: 'float', defaultValue: 0.3, minValue: 0, maxValue: 1, automatable: true }, { id: 'mix', name: 'Mix', type: 'float', defaultValue: 0.3, minValue: 0, maxValue: 1, automatable: true }], defaultPreset: { time: 350, modRate: 0.5, modDepth: 0.3, mix: 0.3 } },
  { id: 'mb-delay-reverse', slug: 'mb-delay-reverse', name: 'MB Reverse Delay', category: 'effect', type: 'delay', version: '1.0.0', description: 'Backwards reverse delay', author: 'Max Booster', parameters: [{ id: 'time', name: 'Time', type: 'float', defaultValue: 400, minValue: 100, maxValue: 1000, automatable: true }, { id: 'feedback', name: 'Feedback', type: 'float', defaultValue: 0.4, minValue: 0, maxValue: 0.85, automatable: true }, { id: 'mix', name: 'Mix', type: 'float', defaultValue: 0.35, minValue: 0, maxValue: 1, automatable: true }], defaultPreset: { time: 400, feedback: 0.4, mix: 0.35 } },
  { id: 'mb-delay-dub', slug: 'mb-delay-dub', name: 'MB Dub Delay', category: 'effect', type: 'delay', version: '1.0.0', description: 'Classic dub echo', author: 'Max Booster', parameters: [{ id: 'time', name: 'Time', type: 'float', defaultValue: 500, minValue: 100, maxValue: 2000, automatable: true }, { id: 'feedback', name: 'Feedback', type: 'float', defaultValue: 0.6, minValue: 0, maxValue: 0.95, automatable: true }, { id: 'filter', name: 'Filter', type: 'float', defaultValue: 3000, minValue: 500, maxValue: 10000, automatable: true }, { id: 'mix', name: 'Mix', type: 'float', defaultValue: 0.4, minValue: 0, maxValue: 1, automatable: true }], defaultPreset: { time: 500, feedback: 0.6, filter: 3000, mix: 0.4 } },
  { id: 'mb-delay-grain', slug: 'mb-delay-grain', name: 'MB Grain Delay', category: 'effect', type: 'delay', version: '1.0.0', description: 'Granular pitch delay', author: 'Max Booster', parameters: [{ id: 'size', name: 'Grain Size', type: 'float', defaultValue: 100, minValue: 10, maxValue: 500, automatable: true }, { id: 'pitch', name: 'Pitch', type: 'float', defaultValue: 0, minValue: -12, maxValue: 12, automatable: true }, { id: 'feedback', name: 'Feedback', type: 'float', defaultValue: 0.4, minValue: 0, maxValue: 0.9, automatable: true }, { id: 'mix', name: 'Mix', type: 'float', defaultValue: 0.35, minValue: 0, maxValue: 1, automatable: true }], defaultPreset: { size: 100, pitch: 0, feedback: 0.4, mix: 0.35 } },
];

export const COMPRESSOR_PLUGINS: PluginDefinition[] = [
  { id: 'mb-comp-studio', slug: 'mb-comp-studio', name: 'MB Studio Comp', category: 'effect', type: 'compressor', version: '1.0.0', description: 'Clean studio compressor', author: 'Max Booster', parameters: [{ id: 'threshold', name: 'Threshold', type: 'float', defaultValue: -20, minValue: -60, maxValue: 0, automatable: true }, { id: 'ratio', name: 'Ratio', type: 'float', defaultValue: 4, minValue: 1, maxValue: 20, automatable: true }, { id: 'attack', name: 'Attack', type: 'float', defaultValue: 10, minValue: 0.1, maxValue: 100, automatable: true }, { id: 'release', name: 'Release', type: 'float', defaultValue: 100, minValue: 10, maxValue: 1000, automatable: true }], defaultPreset: { threshold: -20, ratio: 4, attack: 10, release: 100 } },
  { id: 'mb-comp-vca', slug: 'mb-comp-vca', name: 'MB VCA Comp', category: 'effect', type: 'compressor', version: '1.0.0', description: 'Fast VCA compressor', author: 'Max Booster', parameters: [{ id: 'threshold', name: 'Threshold', type: 'float', defaultValue: -18, minValue: -60, maxValue: 0, automatable: true }, { id: 'ratio', name: 'Ratio', type: 'float', defaultValue: 6, minValue: 1, maxValue: 20, automatable: true }, { id: 'attack', name: 'Attack', type: 'float', defaultValue: 1, minValue: 0.1, maxValue: 50, automatable: true }, { id: 'release', name: 'Release', type: 'float', defaultValue: 50, minValue: 5, maxValue: 500, automatable: true }], defaultPreset: { threshold: -18, ratio: 6, attack: 1, release: 50 } },
  { id: 'mb-comp-opto', slug: 'mb-comp-opto', name: 'MB Opto Comp', category: 'effect', type: 'compressor', version: '1.0.0', description: 'Smooth optical compressor', author: 'Max Booster', parameters: [{ id: 'threshold', name: 'Threshold', type: 'float', defaultValue: -24, minValue: -60, maxValue: 0, automatable: true }, { id: 'ratio', name: 'Ratio', type: 'float', defaultValue: 3, minValue: 1, maxValue: 10, automatable: true }, { id: 'attack', name: 'Attack', type: 'float', defaultValue: 20, minValue: 5, maxValue: 100, automatable: true }, { id: 'release', name: 'Release', type: 'float', defaultValue: 200, minValue: 50, maxValue: 2000, automatable: true }], defaultPreset: { threshold: -24, ratio: 3, attack: 20, release: 200 } },
  { id: 'mb-comp-tube', slug: 'mb-comp-tube', name: 'MB Tube Comp', category: 'effect', type: 'compressor', version: '1.0.0', description: 'Warm tube compression', author: 'Max Booster', parameters: [{ id: 'threshold', name: 'Threshold', type: 'float', defaultValue: -16, minValue: -60, maxValue: 0, automatable: true }, { id: 'ratio', name: 'Ratio', type: 'float', defaultValue: 4, minValue: 1, maxValue: 12, automatable: true }, { id: 'drive', name: 'Drive', type: 'float', defaultValue: 0.3, minValue: 0, maxValue: 1, automatable: true }], defaultPreset: { threshold: -16, ratio: 4, drive: 0.3 } },
  { id: 'mb-comp-bus', slug: 'mb-comp-bus', name: 'MB Bus Comp', category: 'effect', type: 'compressor', version: '1.0.0', description: 'Mix bus glue compressor', author: 'Max Booster', parameters: [{ id: 'threshold', name: 'Threshold', type: 'float', defaultValue: -12, minValue: -40, maxValue: 0, automatable: true }, { id: 'ratio', name: 'Ratio', type: 'float', defaultValue: 2, minValue: 1, maxValue: 8, automatable: true }, { id: 'attack', name: 'Attack', type: 'float', defaultValue: 30, minValue: 0.1, maxValue: 100, automatable: true }, { id: 'release', name: 'Release', type: 'float', defaultValue: 300, minValue: 50, maxValue: 1000, automatable: true }], defaultPreset: { threshold: -12, ratio: 2, attack: 30, release: 300 } },
  { id: 'mb-comp-multiband', slug: 'mb-comp-multiband', name: 'MB Multiband Comp', category: 'effect', type: 'compressor', version: '1.0.0', description: '3-band multiband compressor', author: 'Max Booster', parameters: [{ id: 'lowThresh', name: 'Low Thresh', type: 'float', defaultValue: -20, minValue: -60, maxValue: 0, automatable: true }, { id: 'midThresh', name: 'Mid Thresh', type: 'float', defaultValue: -18, minValue: -60, maxValue: 0, automatable: true }, { id: 'highThresh', name: 'High Thresh', type: 'float', defaultValue: -16, minValue: -60, maxValue: 0, automatable: true }], defaultPreset: { lowThresh: -20, midThresh: -18, highThresh: -16 } },
  { id: 'mb-comp-sidechain', slug: 'mb-comp-sidechain', name: 'MB Sidechain Comp', category: 'effect', type: 'compressor', version: '1.0.0', description: 'Pumping sidechain compressor', author: 'Max Booster', parameters: [{ id: 'threshold', name: 'Threshold', type: 'float', defaultValue: -30, minValue: -60, maxValue: 0, automatable: true }, { id: 'ratio', name: 'Ratio', type: 'float', defaultValue: 10, minValue: 1, maxValue: 20, automatable: true }, { id: 'attack', name: 'Attack', type: 'float', defaultValue: 1, minValue: 0.1, maxValue: 20, automatable: true }, { id: 'release', name: 'Release', type: 'float', defaultValue: 150, minValue: 20, maxValue: 500, automatable: true }], defaultPreset: { threshold: -30, ratio: 10, attack: 1, release: 150 } },
  { id: 'mb-comp-mastering', slug: 'mb-comp-mastering', name: 'MB Mastering Comp', category: 'effect', type: 'compressor', version: '1.0.0', description: 'Transparent mastering compressor', author: 'Max Booster', parameters: [{ id: 'threshold', name: 'Threshold', type: 'float', defaultValue: -8, minValue: -30, maxValue: 0, automatable: true }, { id: 'ratio', name: 'Ratio', type: 'float', defaultValue: 1.5, minValue: 1, maxValue: 4, automatable: true }, { id: 'attack', name: 'Attack', type: 'float', defaultValue: 20, minValue: 1, maxValue: 100, automatable: true }, { id: 'release', name: 'Release', type: 'float', defaultValue: 250, minValue: 50, maxValue: 1000, automatable: true }], defaultPreset: { threshold: -8, ratio: 1.5, attack: 20, release: 250 } },
  { id: 'mb-comp-parallel', slug: 'mb-comp-parallel', name: 'MB Parallel Comp', category: 'effect', type: 'compressor', version: '1.0.0', description: 'NY-style parallel compression', author: 'Max Booster', parameters: [{ id: 'threshold', name: 'Threshold', type: 'float', defaultValue: -35, minValue: -60, maxValue: 0, automatable: true }, { id: 'ratio', name: 'Ratio', type: 'float', defaultValue: 8, minValue: 1, maxValue: 20, automatable: true }, { id: 'blend', name: 'Blend', type: 'float', defaultValue: 0.4, minValue: 0, maxValue: 1, automatable: true }], defaultPreset: { threshold: -35, ratio: 8, blend: 0.4 } },
  { id: 'mb-comp-transient', slug: 'mb-comp-transient', name: 'MB Transient Shaper', category: 'effect', type: 'compressor', version: '1.0.0', description: 'Attack and sustain shaper', author: 'Max Booster', parameters: [{ id: 'attack', name: 'Attack', type: 'float', defaultValue: 0, minValue: -100, maxValue: 100, automatable: true }, { id: 'sustain', name: 'Sustain', type: 'float', defaultValue: 0, minValue: -100, maxValue: 100, automatable: true }], defaultPreset: { attack: 0, sustain: 0 } },
];

export const EQ_PLUGINS: PluginDefinition[] = [
  { id: 'mb-eq-parametric', slug: 'mb-eq-parametric', name: 'MB Parametric EQ', category: 'effect', type: 'eq', version: '1.0.0', description: '4-band parametric EQ', author: 'Max Booster', parameters: [{ id: 'lowFreq', name: 'Low Freq', type: 'float', defaultValue: 80, minValue: 20, maxValue: 500, automatable: true }, { id: 'lowGain', name: 'Low Gain', type: 'float', defaultValue: 0, minValue: -24, maxValue: 24, automatable: true }, { id: 'highFreq', name: 'High Freq', type: 'float', defaultValue: 8000, minValue: 2000, maxValue: 20000, automatable: true }, { id: 'highGain', name: 'High Gain', type: 'float', defaultValue: 0, minValue: -24, maxValue: 24, automatable: true }], defaultPreset: { lowFreq: 80, lowGain: 0, highFreq: 8000, highGain: 0 } },
  { id: 'mb-eq-graphic', slug: 'mb-eq-graphic', name: 'MB Graphic EQ', category: 'effect', type: 'eq', version: '1.0.0', description: '10-band graphic EQ', author: 'Max Booster', parameters: [{ id: 'band1', name: '31Hz', type: 'float', defaultValue: 0, minValue: -12, maxValue: 12, automatable: true }, { id: 'band2', name: '62Hz', type: 'float', defaultValue: 0, minValue: -12, maxValue: 12, automatable: true }, { id: 'band3', name: '125Hz', type: 'float', defaultValue: 0, minValue: -12, maxValue: 12, automatable: true }, { id: 'band4', name: '250Hz', type: 'float', defaultValue: 0, minValue: -12, maxValue: 12, automatable: true }, { id: 'band5', name: '500Hz', type: 'float', defaultValue: 0, minValue: -12, maxValue: 12, automatable: true }], defaultPreset: { band1: 0, band2: 0, band3: 0, band4: 0, band5: 0 } },
  { id: 'mb-eq-vintage', slug: 'mb-eq-vintage', name: 'MB Vintage EQ', category: 'effect', type: 'eq', version: '1.0.0', description: 'Pultec-style vintage EQ', author: 'Max Booster', parameters: [{ id: 'lowBoost', name: 'Low Boost', type: 'float', defaultValue: 0, minValue: 0, maxValue: 10, automatable: true }, { id: 'lowCut', name: 'Low Cut', type: 'float', defaultValue: 0, minValue: 0, maxValue: 10, automatable: true }, { id: 'highBoost', name: 'High Boost', type: 'float', defaultValue: 0, minValue: 0, maxValue: 10, automatable: true }, { id: 'highAtten', name: 'High Atten', type: 'float', defaultValue: 0, minValue: 0, maxValue: 10, automatable: true }], defaultPreset: { lowBoost: 0, lowCut: 0, highBoost: 0, highAtten: 0 } },
  { id: 'mb-eq-channel', slug: 'mb-eq-channel', name: 'MB Channel EQ', category: 'effect', type: 'eq', version: '1.0.0', description: 'Console channel strip EQ', author: 'Max Booster', parameters: [{ id: 'low', name: 'Low', type: 'float', defaultValue: 0, minValue: -15, maxValue: 15, automatable: true }, { id: 'mid', name: 'Mid', type: 'float', defaultValue: 0, minValue: -15, maxValue: 15, automatable: true }, { id: 'high', name: 'High', type: 'float', defaultValue: 0, minValue: -15, maxValue: 15, automatable: true }], defaultPreset: { low: 0, mid: 0, high: 0 } },
  { id: 'mb-eq-linear', slug: 'mb-eq-linear', name: 'MB Linear Phase EQ', category: 'effect', type: 'eq', version: '1.0.0', description: 'Zero-latency linear phase EQ', author: 'Max Booster', parameters: [{ id: 'lowGain', name: 'Low', type: 'float', defaultValue: 0, minValue: -24, maxValue: 24, automatable: true }, { id: 'midGain', name: 'Mid', type: 'float', defaultValue: 0, minValue: -24, maxValue: 24, automatable: true }, { id: 'highGain', name: 'High', type: 'float', defaultValue: 0, minValue: -24, maxValue: 24, automatable: true }], defaultPreset: { lowGain: 0, midGain: 0, highGain: 0 } },
  { id: 'mb-eq-dynamic', slug: 'mb-eq-dynamic', name: 'MB Dynamic EQ', category: 'effect', type: 'eq', version: '1.0.0', description: 'Frequency-dependent dynamics', author: 'Max Booster', parameters: [{ id: 'freq', name: 'Frequency', type: 'float', defaultValue: 3000, minValue: 100, maxValue: 15000, automatable: true }, { id: 'threshold', name: 'Threshold', type: 'float', defaultValue: -20, minValue: -60, maxValue: 0, automatable: true }, { id: 'range', name: 'Range', type: 'float', defaultValue: -6, minValue: -24, maxValue: 24, automatable: true }], defaultPreset: { freq: 3000, threshold: -20, range: -6 } },
  { id: 'mb-eq-surgical', slug: 'mb-eq-surgical', name: 'MB Surgical EQ', category: 'effect', type: 'eq', version: '1.0.0', description: 'Precision notch filtering', author: 'Max Booster', parameters: [{ id: 'freq', name: 'Frequency', type: 'float', defaultValue: 1000, minValue: 20, maxValue: 20000, automatable: true }, { id: 'gain', name: 'Gain', type: 'float', defaultValue: 0, minValue: -24, maxValue: 24, automatable: true }, { id: 'q', name: 'Q', type: 'float', defaultValue: 5, minValue: 0.5, maxValue: 20, automatable: true }], defaultPreset: { freq: 1000, gain: 0, q: 5 } },
  { id: 'mb-eq-air', slug: 'mb-eq-air', name: 'MB Air EQ', category: 'effect', type: 'eq', version: '1.0.0', description: 'High frequency air band', author: 'Max Booster', parameters: [{ id: 'freq', name: 'Frequency', type: 'float', defaultValue: 12000, minValue: 8000, maxValue: 20000, automatable: true }, { id: 'amount', name: 'Amount', type: 'float', defaultValue: 0, minValue: -12, maxValue: 12, automatable: true }], defaultPreset: { freq: 12000, amount: 0 } },
  { id: 'mb-eq-bass', slug: 'mb-eq-bass', name: 'MB Bass Enhancer', category: 'effect', type: 'eq', version: '1.0.0', description: 'Low end enhancement', author: 'Max Booster', parameters: [{ id: 'freq', name: 'Frequency', type: 'float', defaultValue: 60, minValue: 30, maxValue: 120, automatable: true }, { id: 'amount', name: 'Amount', type: 'float', defaultValue: 0, minValue: -12, maxValue: 12, automatable: true }, { id: 'harmonics', name: 'Harmonics', type: 'float', defaultValue: 0.3, minValue: 0, maxValue: 1, automatable: true }], defaultPreset: { freq: 60, amount: 0, harmonics: 0.3 } },
  { id: 'mb-eq-presence', slug: 'mb-eq-presence', name: 'MB Presence EQ', category: 'effect', type: 'eq', version: '1.0.0', description: 'Vocal presence enhancer', author: 'Max Booster', parameters: [{ id: 'freq', name: 'Frequency', type: 'float', defaultValue: 3000, minValue: 1500, maxValue: 6000, automatable: true }, { id: 'amount', name: 'Amount', type: 'float', defaultValue: 0, minValue: -12, maxValue: 12, automatable: true }], defaultPreset: { freq: 3000, amount: 0 } },
];

export const DISTORTION_PLUGINS: PluginDefinition[] = [
  { id: 'mb-dist-tube', slug: 'mb-dist-tube', name: 'MB Tube Distortion', category: 'effect', type: 'distortion', version: '1.0.0', description: 'Warm tube saturation', author: 'Max Booster', parameters: [{ id: 'drive', name: 'Drive', type: 'float', defaultValue: 0.3, minValue: 0, maxValue: 1, automatable: true }, { id: 'tone', name: 'Tone', type: 'float', defaultValue: 0.5, minValue: 0, maxValue: 1, automatable: true }, { id: 'mix', name: 'Mix', type: 'float', defaultValue: 1, minValue: 0, maxValue: 1, automatable: true }], defaultPreset: { drive: 0.3, tone: 0.5, mix: 1 } },
  { id: 'mb-dist-tape', slug: 'mb-dist-tape', name: 'MB Tape Saturation', category: 'effect', type: 'distortion', version: '1.0.0', description: 'Analog tape warmth', author: 'Max Booster', parameters: [{ id: 'saturation', name: 'Saturation', type: 'float', defaultValue: 0.4, minValue: 0, maxValue: 1, automatable: true }, { id: 'bias', name: 'Bias', type: 'float', defaultValue: 0.5, minValue: 0, maxValue: 1, automatable: true }, { id: 'mix', name: 'Mix', type: 'float', defaultValue: 1, minValue: 0, maxValue: 1, automatable: true }], defaultPreset: { saturation: 0.4, bias: 0.5, mix: 1 } },
  { id: 'mb-dist-transistor', slug: 'mb-dist-transistor', name: 'MB Transistor', category: 'effect', type: 'distortion', version: '1.0.0', description: 'Aggressive transistor clipping', author: 'Max Booster', parameters: [{ id: 'drive', name: 'Drive', type: 'float', defaultValue: 0.5, minValue: 0, maxValue: 1, automatable: true }, { id: 'tone', name: 'Tone', type: 'float', defaultValue: 0.6, minValue: 0, maxValue: 1, automatable: true }, { id: 'mix', name: 'Mix', type: 'float', defaultValue: 1, minValue: 0, maxValue: 1, automatable: true }], defaultPreset: { drive: 0.5, tone: 0.6, mix: 1 } },
  { id: 'mb-dist-fuzz', slug: 'mb-dist-fuzz', name: 'MB Fuzz', category: 'effect', type: 'distortion', version: '1.0.0', description: 'Vintage fuzz pedal', author: 'Max Booster', parameters: [{ id: 'fuzz', name: 'Fuzz', type: 'float', defaultValue: 0.7, minValue: 0, maxValue: 1, automatable: true }, { id: 'tone', name: 'Tone', type: 'float', defaultValue: 0.4, minValue: 0, maxValue: 1, automatable: true }, { id: 'mix', name: 'Mix', type: 'float', defaultValue: 1, minValue: 0, maxValue: 1, automatable: true }], defaultPreset: { fuzz: 0.7, tone: 0.4, mix: 1 } },
  { id: 'mb-dist-bitcrush', slug: 'mb-dist-bitcrush', name: 'MB Bitcrusher', category: 'effect', type: 'distortion', version: '1.0.0', description: 'Lo-fi bit reduction', author: 'Max Booster', parameters: [{ id: 'bits', name: 'Bits', type: 'float', defaultValue: 8, minValue: 1, maxValue: 16, automatable: true }, { id: 'rate', name: 'Sample Rate', type: 'float', defaultValue: 22050, minValue: 1000, maxValue: 44100, automatable: true }, { id: 'mix', name: 'Mix', type: 'float', defaultValue: 1, minValue: 0, maxValue: 1, automatable: true }], defaultPreset: { bits: 8, rate: 22050, mix: 1 } },
  { id: 'mb-dist-overdrive', slug: 'mb-dist-overdrive', name: 'MB Overdrive', category: 'effect', type: 'distortion', version: '1.0.0', description: 'Smooth overdrive', author: 'Max Booster', parameters: [{ id: 'drive', name: 'Drive', type: 'float', defaultValue: 0.4, minValue: 0, maxValue: 1, automatable: true }, { id: 'tone', name: 'Tone', type: 'float', defaultValue: 0.5, minValue: 0, maxValue: 1, automatable: true }, { id: 'mix', name: 'Mix', type: 'float', defaultValue: 1, minValue: 0, maxValue: 1, automatable: true }], defaultPreset: { drive: 0.4, tone: 0.5, mix: 1 } },
  { id: 'mb-dist-amp', slug: 'mb-dist-amp', name: 'MB Amp Sim', category: 'effect', type: 'distortion', version: '1.0.0', description: 'Guitar amp simulation', author: 'Max Booster', parameters: [{ id: 'gain', name: 'Gain', type: 'float', defaultValue: 0.5, minValue: 0, maxValue: 1, automatable: true }, { id: 'bass', name: 'Bass', type: 'float', defaultValue: 0.5, minValue: 0, maxValue: 1, automatable: true }, { id: 'mid', name: 'Mid', type: 'float', defaultValue: 0.5, minValue: 0, maxValue: 1, automatable: true }, { id: 'treble', name: 'Treble', type: 'float', defaultValue: 0.5, minValue: 0, maxValue: 1, automatable: true }], defaultPreset: { gain: 0.5, bass: 0.5, mid: 0.5, treble: 0.5 } },
  { id: 'mb-dist-waveshape', slug: 'mb-dist-waveshape', name: 'MB Waveshaper', category: 'effect', type: 'distortion', version: '1.0.0', description: 'Custom waveshaping', author: 'Max Booster', parameters: [{ id: 'curve', name: 'Curve', type: 'float', defaultValue: 0.5, minValue: 0, maxValue: 1, automatable: true }, { id: 'drive', name: 'Drive', type: 'float', defaultValue: 0.5, minValue: 0, maxValue: 1, automatable: true }, { id: 'mix', name: 'Mix', type: 'float', defaultValue: 1, minValue: 0, maxValue: 1, automatable: true }], defaultPreset: { curve: 0.5, drive: 0.5, mix: 1 } },
  { id: 'mb-dist-soft', slug: 'mb-dist-soft', name: 'MB Soft Clipper', category: 'effect', type: 'distortion', version: '1.0.0', description: 'Gentle soft clipping', author: 'Max Booster', parameters: [{ id: 'threshold', name: 'Threshold', type: 'float', defaultValue: -6, minValue: -24, maxValue: 0, automatable: true }, { id: 'knee', name: 'Knee', type: 'float', defaultValue: 0.5, minValue: 0, maxValue: 1, automatable: true }], defaultPreset: { threshold: -6, knee: 0.5 } },
  { id: 'mb-dist-harmonics', slug: 'mb-dist-harmonics', name: 'MB Harmonic Exciter', category: 'effect', type: 'distortion', version: '1.0.0', description: 'Harmonic enhancement', author: 'Max Booster', parameters: [{ id: 'odd', name: 'Odd', type: 'float', defaultValue: 0.3, minValue: 0, maxValue: 1, automatable: true }, { id: 'even', name: 'Even', type: 'float', defaultValue: 0.3, minValue: 0, maxValue: 1, automatable: true }, { id: 'mix', name: 'Mix', type: 'float', defaultValue: 0.5, minValue: 0, maxValue: 1, automatable: true }], defaultPreset: { odd: 0.3, even: 0.3, mix: 0.5 } },
];

export const MODULATION_PLUGINS: PluginDefinition[] = [
  { id: 'mb-chorus-classic', slug: 'mb-chorus-classic', name: 'MB Classic Chorus', category: 'effect', type: 'chorus', version: '1.0.0', description: 'Rich stereo chorus', author: 'Max Booster', parameters: [{ id: 'rate', name: 'Rate', type: 'float', defaultValue: 1, minValue: 0.1, maxValue: 10, automatable: true }, { id: 'depth', name: 'Depth', type: 'float', defaultValue: 0.5, minValue: 0, maxValue: 1, automatable: true }, { id: 'mix', name: 'Mix', type: 'float', defaultValue: 0.5, minValue: 0, maxValue: 1, automatable: true }], defaultPreset: { rate: 1, depth: 0.5, mix: 0.5 } },
  { id: 'mb-chorus-vintage', slug: 'mb-chorus-vintage', name: 'MB Vintage Chorus', category: 'effect', type: 'chorus', version: '1.0.0', description: '80s vintage chorus', author: 'Max Booster', parameters: [{ id: 'rate', name: 'Rate', type: 'float', defaultValue: 0.8, minValue: 0.1, maxValue: 5, automatable: true }, { id: 'depth', name: 'Depth', type: 'float', defaultValue: 0.6, minValue: 0, maxValue: 1, automatable: true }, { id: 'mix', name: 'Mix', type: 'float', defaultValue: 0.5, minValue: 0, maxValue: 1, automatable: true }], defaultPreset: { rate: 0.8, depth: 0.6, mix: 0.5 } },
  { id: 'mb-chorus-dimension', slug: 'mb-chorus-dimension', name: 'MB Dimension', category: 'effect', type: 'chorus', version: '1.0.0', description: 'Dimension D style', author: 'Max Booster', parameters: [{ id: 'mode', name: 'Mode', type: 'float', defaultValue: 2, minValue: 1, maxValue: 4, automatable: false }, { id: 'mix', name: 'Mix', type: 'float', defaultValue: 0.5, minValue: 0, maxValue: 1, automatable: true }], defaultPreset: { mode: 2, mix: 0.5 } },
  { id: 'mb-flanger-jet', slug: 'mb-flanger-jet', name: 'MB Jet Flanger', category: 'effect', type: 'flanger', version: '1.0.0', description: 'Jet airplane flanging', author: 'Max Booster', parameters: [{ id: 'rate', name: 'Rate', type: 'float', defaultValue: 0.3, minValue: 0.01, maxValue: 5, automatable: true }, { id: 'depth', name: 'Depth', type: 'float', defaultValue: 0.8, minValue: 0, maxValue: 1, automatable: true }, { id: 'feedback', name: 'Feedback', type: 'float', defaultValue: 0.7, minValue: 0, maxValue: 0.99, automatable: true }, { id: 'mix', name: 'Mix', type: 'float', defaultValue: 0.5, minValue: 0, maxValue: 1, automatable: true }], defaultPreset: { rate: 0.3, depth: 0.8, feedback: 0.7, mix: 0.5 } },
  { id: 'mb-flanger-tape', slug: 'mb-flanger-tape', name: 'MB Tape Flanger', category: 'effect', type: 'flanger', version: '1.0.0', description: 'Classic tape flanging', author: 'Max Booster', parameters: [{ id: 'rate', name: 'Rate', type: 'float', defaultValue: 0.2, minValue: 0.01, maxValue: 3, automatable: true }, { id: 'depth', name: 'Depth', type: 'float', defaultValue: 0.6, minValue: 0, maxValue: 1, automatable: true }, { id: 'feedback', name: 'Feedback', type: 'float', defaultValue: 0.5, minValue: 0, maxValue: 0.95, automatable: true }, { id: 'mix', name: 'Mix', type: 'float', defaultValue: 0.5, minValue: 0, maxValue: 1, automatable: true }], defaultPreset: { rate: 0.2, depth: 0.6, feedback: 0.5, mix: 0.5 } },
  { id: 'mb-phaser-classic', slug: 'mb-phaser-classic', name: 'MB Classic Phaser', category: 'effect', type: 'phaser', version: '1.0.0', description: '4-stage phaser', author: 'Max Booster', parameters: [{ id: 'rate', name: 'Rate', type: 'float', defaultValue: 0.5, minValue: 0.01, maxValue: 10, automatable: true }, { id: 'depth', name: 'Depth', type: 'float', defaultValue: 0.7, minValue: 0, maxValue: 1, automatable: true }, { id: 'feedback', name: 'Feedback', type: 'float', defaultValue: 0.5, minValue: 0, maxValue: 0.99, automatable: true }, { id: 'mix', name: 'Mix', type: 'float', defaultValue: 0.5, minValue: 0, maxValue: 1, automatable: true }], defaultPreset: { rate: 0.5, depth: 0.7, feedback: 0.5, mix: 0.5 } },
  { id: 'mb-phaser-stereo', slug: 'mb-phaser-stereo', name: 'MB Stereo Phaser', category: 'effect', type: 'phaser', version: '1.0.0', description: 'Wide stereo phasing', author: 'Max Booster', parameters: [{ id: 'rate', name: 'Rate', type: 'float', defaultValue: 0.4, minValue: 0.01, maxValue: 8, automatable: true }, { id: 'depth', name: 'Depth', type: 'float', defaultValue: 0.8, minValue: 0, maxValue: 1, automatable: true }, { id: 'spread', name: 'Spread', type: 'float', defaultValue: 0.7, minValue: 0, maxValue: 1, automatable: true }, { id: 'mix', name: 'Mix', type: 'float', defaultValue: 0.5, minValue: 0, maxValue: 1, automatable: true }], defaultPreset: { rate: 0.4, depth: 0.8, spread: 0.7, mix: 0.5 } },
  { id: 'mb-tremolo', slug: 'mb-tremolo', name: 'MB Tremolo', category: 'effect', type: 'chorus', version: '1.0.0', description: 'Amplitude modulation', author: 'Max Booster', parameters: [{ id: 'rate', name: 'Rate', type: 'float', defaultValue: 4, minValue: 0.5, maxValue: 20, automatable: true }, { id: 'depth', name: 'Depth', type: 'float', defaultValue: 0.5, minValue: 0, maxValue: 1, automatable: true }, { id: 'shape', name: 'Shape', type: 'float', defaultValue: 0.5, minValue: 0, maxValue: 1, automatable: true }], defaultPreset: { rate: 4, depth: 0.5, shape: 0.5 } },
  { id: 'mb-vibrato', slug: 'mb-vibrato', name: 'MB Vibrato', category: 'effect', type: 'chorus', version: '1.0.0', description: 'Pitch modulation', author: 'Max Booster', parameters: [{ id: 'rate', name: 'Rate', type: 'float', defaultValue: 5, minValue: 1, maxValue: 15, automatable: true }, { id: 'depth', name: 'Depth', type: 'float', defaultValue: 0.3, minValue: 0, maxValue: 1, automatable: true }], defaultPreset: { rate: 5, depth: 0.3 } },
  { id: 'mb-rotary', slug: 'mb-rotary', name: 'MB Rotary Speaker', category: 'effect', type: 'chorus', version: '1.0.0', description: 'Leslie speaker simulation', author: 'Max Booster', parameters: [{ id: 'speed', name: 'Speed', type: 'float', defaultValue: 0.5, minValue: 0, maxValue: 1, automatable: true }, { id: 'depth', name: 'Depth', type: 'float', defaultValue: 0.7, minValue: 0, maxValue: 1, automatable: true }, { id: 'mix', name: 'Mix', type: 'float', defaultValue: 0.6, minValue: 0, maxValue: 1, automatable: true }], defaultPreset: { speed: 0.5, depth: 0.7, mix: 0.6 } },
];

export const DYNAMICS_PLUGINS: PluginDefinition[] = [
  { id: 'mb-limiter-master', slug: 'mb-limiter-master', name: 'MB Master Limiter', category: 'effect', type: 'limiter', version: '1.0.0', description: 'Transparent mastering limiter', author: 'Max Booster', parameters: [{ id: 'ceiling', name: 'Ceiling', type: 'float', defaultValue: -0.3, minValue: -6, maxValue: 0, automatable: true }, { id: 'threshold', name: 'Threshold', type: 'float', defaultValue: -6, minValue: -24, maxValue: 0, automatable: true }, { id: 'release', name: 'Release', type: 'float', defaultValue: 100, minValue: 10, maxValue: 1000, automatable: true }], defaultPreset: { ceiling: -0.3, threshold: -6, release: 100 } },
  { id: 'mb-limiter-brickwall', slug: 'mb-limiter-brickwall', name: 'MB Brickwall Limiter', category: 'effect', type: 'limiter', version: '1.0.0', description: 'Hard brickwall limiting', author: 'Max Booster', parameters: [{ id: 'ceiling', name: 'Ceiling', type: 'float', defaultValue: -0.1, minValue: -3, maxValue: 0, automatable: true }, { id: 'release', name: 'Release', type: 'float', defaultValue: 50, minValue: 5, maxValue: 500, automatable: true }], defaultPreset: { ceiling: -0.1, release: 50 } },
  { id: 'mb-limiter-soft', slug: 'mb-limiter-soft', name: 'MB Soft Limiter', category: 'effect', type: 'limiter', version: '1.0.0', description: 'Gentle peak limiting', author: 'Max Booster', parameters: [{ id: 'ceiling', name: 'Ceiling', type: 'float', defaultValue: -1, minValue: -12, maxValue: 0, automatable: true }, { id: 'knee', name: 'Knee', type: 'float', defaultValue: 6, minValue: 0, maxValue: 12, automatable: true }], defaultPreset: { ceiling: -1, knee: 6 } },
  { id: 'mb-gate-noise', slug: 'mb-gate-noise', name: 'MB Noise Gate', category: 'effect', type: 'gate', version: '1.0.0', description: 'Clean noise removal', author: 'Max Booster', parameters: [{ id: 'threshold', name: 'Threshold', type: 'float', defaultValue: -40, minValue: -80, maxValue: 0, automatable: true }, { id: 'attack', name: 'Attack', type: 'float', defaultValue: 1, minValue: 0.01, maxValue: 50, automatable: true }, { id: 'release', name: 'Release', type: 'float', defaultValue: 100, minValue: 10, maxValue: 2000, automatable: true }], defaultPreset: { threshold: -40, attack: 1, release: 100 } },
  { id: 'mb-gate-expander', slug: 'mb-gate-expander', name: 'MB Expander', category: 'effect', type: 'gate', version: '1.0.0', description: 'Downward expansion', author: 'Max Booster', parameters: [{ id: 'threshold', name: 'Threshold', type: 'float', defaultValue: -35, minValue: -80, maxValue: 0, automatable: true }, { id: 'ratio', name: 'Ratio', type: 'float', defaultValue: 2, minValue: 1, maxValue: 10, automatable: true }, { id: 'range', name: 'Range', type: 'float', defaultValue: -20, minValue: -80, maxValue: 0, automatable: true }], defaultPreset: { threshold: -35, ratio: 2, range: -20 } },
  { id: 'mb-gate-drum', slug: 'mb-gate-drum', name: 'MB Drum Gate', category: 'effect', type: 'gate', version: '1.0.0', description: 'Fast drum gating', author: 'Max Booster', parameters: [{ id: 'threshold', name: 'Threshold', type: 'float', defaultValue: -25, minValue: -60, maxValue: 0, automatable: true }, { id: 'attack', name: 'Attack', type: 'float', defaultValue: 0.1, minValue: 0.01, maxValue: 10, automatable: true }, { id: 'hold', name: 'Hold', type: 'float', defaultValue: 30, minValue: 1, maxValue: 200, automatable: true }, { id: 'release', name: 'Release', type: 'float', defaultValue: 50, minValue: 5, maxValue: 500, automatable: true }], defaultPreset: { threshold: -25, attack: 0.1, hold: 30, release: 50 } },
  { id: 'mb-deesser', slug: 'mb-deesser', name: 'MB De-Esser', category: 'effect', type: 'compressor', version: '1.0.0', description: 'Sibilance reduction', author: 'Max Booster', parameters: [{ id: 'freq', name: 'Frequency', type: 'float', defaultValue: 6000, minValue: 3000, maxValue: 12000, automatable: true }, { id: 'threshold', name: 'Threshold', type: 'float', defaultValue: -20, minValue: -60, maxValue: 0, automatable: true }, { id: 'reduction', name: 'Reduction', type: 'float', defaultValue: 6, minValue: 0, maxValue: 24, automatable: true }], defaultPreset: { freq: 6000, threshold: -20, reduction: 6 } },
  { id: 'mb-maximizer', slug: 'mb-maximizer', name: 'MB Maximizer', category: 'effect', type: 'limiter', version: '1.0.0', description: 'Loudness maximizer', author: 'Max Booster', parameters: [{ id: 'ceiling', name: 'Ceiling', type: 'float', defaultValue: -0.3, minValue: -3, maxValue: 0, automatable: true }, { id: 'gain', name: 'Gain', type: 'float', defaultValue: 6, minValue: 0, maxValue: 24, automatable: true }], defaultPreset: { ceiling: -0.3, gain: 6 } },
  { id: 'mb-leveler', slug: 'mb-leveler', name: 'MB Auto Leveler', category: 'effect', type: 'compressor', version: '1.0.0', description: 'Automatic gain riding', author: 'Max Booster', parameters: [{ id: 'target', name: 'Target', type: 'float', defaultValue: -18, minValue: -36, maxValue: 0, automatable: true }, { id: 'speed', name: 'Speed', type: 'float', defaultValue: 0.5, minValue: 0.1, maxValue: 1, automatable: true }], defaultPreset: { target: -18, speed: 0.5 } },
  { id: 'mb-loudness', slug: 'mb-loudness', name: 'MB Loudness Meter', category: 'effect', type: 'limiter', version: '1.0.0', description: 'LUFS loudness metering', author: 'Max Booster', parameters: [{ id: 'target', name: 'Target LUFS', type: 'float', defaultValue: -14, minValue: -24, maxValue: -6, automatable: false }], defaultPreset: { target: -14 } },
];

export const VOCAL_PLUGINS: PluginDefinition[] = [
  { id: 'mb-vocal-autotune', slug: 'mb-vocal-autotune', name: 'MB Auto-Tune', category: 'effect', type: 'vocal', version: '1.0.0', description: 'Real-time pitch correction', author: 'Max Booster', parameters: [{ id: 'key', name: 'Key', type: 'float', defaultValue: 0, minValue: 0, maxValue: 11, automatable: false }, { id: 'scale', name: 'Scale', type: 'float', defaultValue: 0, minValue: 0, maxValue: 1, automatable: false }, { id: 'speed', name: 'Speed', type: 'float', defaultValue: 0.5, minValue: 0, maxValue: 1, automatable: true }, { id: 'humanize', name: 'Humanize', type: 'float', defaultValue: 0.3, minValue: 0, maxValue: 1, automatable: true }], defaultPreset: { key: 0, scale: 0, speed: 0.5, humanize: 0.3 } },
  { id: 'mb-vocal-harmony', slug: 'mb-vocal-harmony', name: 'MB Harmony Engine', category: 'effect', type: 'vocal', version: '1.0.0', description: 'Intelligent harmony generation', author: 'Max Booster', parameters: [{ id: 'voices', name: 'Voices', type: 'float', defaultValue: 2, minValue: 1, maxValue: 4, automatable: false }, { id: 'interval1', name: 'Interval 1', type: 'float', defaultValue: 3, minValue: -12, maxValue: 12, automatable: true }, { id: 'interval2', name: 'Interval 2', type: 'float', defaultValue: 5, minValue: -12, maxValue: 12, automatable: true }, { id: 'mix', name: 'Mix', type: 'float', defaultValue: 0.5, minValue: 0, maxValue: 1, automatable: true }], defaultPreset: { voices: 2, interval1: 3, interval2: 5, mix: 0.5 } },
  { id: 'mb-vocal-doubler', slug: 'mb-vocal-doubler', name: 'MB Vocal Doubler', category: 'effect', type: 'vocal', version: '1.0.0', description: 'Natural vocal doubling effect', author: 'Max Booster', parameters: [{ id: 'voices', name: 'Voices', type: 'float', defaultValue: 2, minValue: 1, maxValue: 4, automatable: false }, { id: 'timing', name: 'Timing', type: 'float', defaultValue: 20, minValue: 5, maxValue: 100, automatable: true }, { id: 'pitch', name: 'Pitch Var', type: 'float', defaultValue: 5, minValue: 0, maxValue: 30, automatable: true }, { id: 'mix', name: 'Mix', type: 'float', defaultValue: 0.4, minValue: 0, maxValue: 1, automatable: true }], defaultPreset: { voices: 2, timing: 20, pitch: 5, mix: 0.4 } },
  { id: 'mb-vocal-formant', slug: 'mb-vocal-formant', name: 'MB Formant Shifter', category: 'effect', type: 'vocal', version: '1.0.0', description: 'Vocal formant manipulation', author: 'Max Booster', parameters: [{ id: 'shift', name: 'Formant Shift', type: 'float', defaultValue: 0, minValue: -12, maxValue: 12, automatable: true }, { id: 'character', name: 'Character', type: 'float', defaultValue: 0.5, minValue: 0, maxValue: 1, automatable: true }], defaultPreset: { shift: 0, character: 0.5 } },
  { id: 'mb-vocal-comp', slug: 'mb-vocal-comp', name: 'MB Vocal Compressor', category: 'effect', type: 'vocal', version: '1.0.0', description: 'Optimized vocal dynamics', author: 'Max Booster', parameters: [{ id: 'threshold', name: 'Threshold', type: 'float', defaultValue: -18, minValue: -60, maxValue: 0, automatable: true }, { id: 'ratio', name: 'Ratio', type: 'float', defaultValue: 4, minValue: 1, maxValue: 20, automatable: true }, { id: 'attack', name: 'Attack', type: 'float', defaultValue: 5, minValue: 0.1, maxValue: 50, automatable: true }, { id: 'release', name: 'Release', type: 'float', defaultValue: 80, minValue: 10, maxValue: 500, automatable: true }], defaultPreset: { threshold: -18, ratio: 4, attack: 5, release: 80 } },
  { id: 'mb-vocal-eq', slug: 'mb-vocal-eq', name: 'MB Vocal EQ', category: 'effect', type: 'vocal', version: '1.0.0', description: 'Vocal-tuned equalizer', author: 'Max Booster', parameters: [{ id: 'lowCut', name: 'Low Cut', type: 'float', defaultValue: 80, minValue: 20, maxValue: 300, automatable: true }, { id: 'presence', name: 'Presence', type: 'float', defaultValue: 0, minValue: -12, maxValue: 12, automatable: true }, { id: 'air', name: 'Air', type: 'float', defaultValue: 0, minValue: -12, maxValue: 12, automatable: true }], defaultPreset: { lowCut: 80, presence: 0, air: 0 } },
  { id: 'mb-vocal-debreath', slug: 'mb-vocal-debreath', name: 'MB De-Breath', category: 'effect', type: 'vocal', version: '1.0.0', description: 'Breath noise reduction', author: 'Max Booster', parameters: [{ id: 'sensitivity', name: 'Sensitivity', type: 'float', defaultValue: 0.5, minValue: 0, maxValue: 1, automatable: true }, { id: 'reduction', name: 'Reduction', type: 'float', defaultValue: -12, minValue: -40, maxValue: 0, automatable: true }], defaultPreset: { sensitivity: 0.5, reduction: -12 } },
  { id: 'mb-vocal-exciter', slug: 'mb-vocal-exciter', name: 'MB Vocal Exciter', category: 'effect', type: 'vocal', version: '1.0.0', description: 'Vocal clarity enhancer', author: 'Max Booster', parameters: [{ id: 'amount', name: 'Amount', type: 'float', defaultValue: 0.3, minValue: 0, maxValue: 1, automatable: true }, { id: 'freq', name: 'Frequency', type: 'float', defaultValue: 3000, minValue: 1000, maxValue: 8000, automatable: true }, { id: 'mix', name: 'Mix', type: 'float', defaultValue: 0.5, minValue: 0, maxValue: 1, automatable: true }], defaultPreset: { amount: 0.3, freq: 3000, mix: 0.5 } },
  { id: 'mb-vocal-rider', slug: 'mb-vocal-rider', name: 'MB Vocal Rider', category: 'effect', type: 'vocal', version: '1.0.0', description: 'Automatic vocal level riding', author: 'Max Booster', parameters: [{ id: 'target', name: 'Target', type: 'float', defaultValue: -12, minValue: -24, maxValue: 0, automatable: true }, { id: 'speed', name: 'Speed', type: 'float', defaultValue: 0.5, minValue: 0.1, maxValue: 1, automatable: true }, { id: 'range', name: 'Range', type: 'float', defaultValue: 12, minValue: 3, maxValue: 24, automatable: true }], defaultPreset: { target: -12, speed: 0.5, range: 12 } },
  { id: 'mb-vocal-vocoder', slug: 'mb-vocal-vocoder', name: 'MB Vocoder', category: 'effect', type: 'vocal', version: '1.0.0', description: 'Classic vocoder synthesis', author: 'Max Booster', parameters: [{ id: 'bands', name: 'Bands', type: 'float', defaultValue: 16, minValue: 8, maxValue: 32, automatable: false }, { id: 'formant', name: 'Formant', type: 'float', defaultValue: 0, minValue: -12, maxValue: 12, automatable: true }, { id: 'carrier', name: 'Carrier Mix', type: 'float', defaultValue: 0.5, minValue: 0, maxValue: 1, automatable: true }], defaultPreset: { bands: 16, formant: 0, carrier: 0.5 } },
];

export const MICROPHONE_PLUGINS: PluginDefinition[] = [
  { id: 'mb-mic-u87', slug: 'mb-mic-u87', name: 'MB U87 Modeler', category: 'effect', type: 'microphone', version: '1.0.0', description: 'Neumann U87 emulation', author: 'Max Booster', parameters: [{ id: 'pattern', name: 'Pattern', type: 'float', defaultValue: 0.5, minValue: 0, maxValue: 1, automatable: true }, { id: 'presence', name: 'Presence', type: 'float', defaultValue: 0.5, minValue: 0, maxValue: 1, automatable: true }, { id: 'proximity', name: 'Proximity', type: 'float', defaultValue: 0.3, minValue: 0, maxValue: 1, automatable: true }], defaultPreset: { pattern: 0.5, presence: 0.5, proximity: 0.3 } },
  { id: 'mb-mic-c414', slug: 'mb-mic-c414', name: 'MB C414 Modeler', category: 'effect', type: 'microphone', version: '1.0.0', description: 'AKG C414 emulation', author: 'Max Booster', parameters: [{ id: 'pattern', name: 'Pattern', type: 'float', defaultValue: 0.5, minValue: 0, maxValue: 1, automatable: true }, { id: 'brightness', name: 'Brightness', type: 'float', defaultValue: 0.6, minValue: 0, maxValue: 1, automatable: true }, { id: 'proximity', name: 'Proximity', type: 'float', defaultValue: 0.3, minValue: 0, maxValue: 1, automatable: true }], defaultPreset: { pattern: 0.5, brightness: 0.6, proximity: 0.3 } },
  { id: 'mb-mic-sm7b', slug: 'mb-mic-sm7b', name: 'MB SM7B Modeler', category: 'effect', type: 'microphone', version: '1.0.0', description: 'Shure SM7B emulation', author: 'Max Booster', parameters: [{ id: 'bass', name: 'Bass Roll-off', type: 'float', defaultValue: 0, minValue: 0, maxValue: 1, automatable: true }, { id: 'presence', name: 'Presence Peak', type: 'float', defaultValue: 0.5, minValue: 0, maxValue: 1, automatable: true }], defaultPreset: { bass: 0, presence: 0.5 } },
  { id: 'mb-mic-ribbon', slug: 'mb-mic-ribbon', name: 'MB Ribbon Modeler', category: 'effect', type: 'microphone', version: '1.0.0', description: 'Vintage ribbon mic character', author: 'Max Booster', parameters: [{ id: 'warmth', name: 'Warmth', type: 'float', defaultValue: 0.6, minValue: 0, maxValue: 1, automatable: true }, { id: 'roll-off', name: 'HF Roll-off', type: 'float', defaultValue: 0.4, minValue: 0, maxValue: 1, automatable: true }, { id: 'proximity', name: 'Proximity', type: 'float', defaultValue: 0.3, minValue: 0, maxValue: 1, automatable: true }], defaultPreset: { warmth: 0.6, 'roll-off': 0.4, proximity: 0.3 } },
  { id: 'mb-mic-sm58', slug: 'mb-mic-sm58', name: 'MB SM58 Modeler', category: 'effect', type: 'microphone', version: '1.0.0', description: 'Shure SM58 stage mic', author: 'Max Booster', parameters: [{ id: 'presence', name: 'Presence', type: 'float', defaultValue: 0.5, minValue: 0, maxValue: 1, automatable: true }, { id: 'proximity', name: 'Proximity', type: 'float', defaultValue: 0.4, minValue: 0, maxValue: 1, automatable: true }], defaultPreset: { presence: 0.5, proximity: 0.4 } },
  { id: 'mb-mic-preamp', slug: 'mb-mic-preamp', name: 'MB Mic Preamp', category: 'effect', type: 'microphone', version: '1.0.0', description: 'Vintage mic preamp coloration', author: 'Max Booster', parameters: [{ id: 'gain', name: 'Gain', type: 'float', defaultValue: 20, minValue: 0, maxValue: 60, automatable: true }, { id: 'impedance', name: 'Impedance', type: 'float', defaultValue: 0.5, minValue: 0, maxValue: 1, automatable: true }, { id: 'color', name: 'Color', type: 'float', defaultValue: 0.3, minValue: 0, maxValue: 1, automatable: true }], defaultPreset: { gain: 20, impedance: 0.5, color: 0.3 } },
  { id: 'mb-mic-room', slug: 'mb-mic-room', name: 'MB Room Simulator', category: 'effect', type: 'microphone', version: '1.0.0', description: 'Recording room emulation', author: 'Max Booster', parameters: [{ id: 'size', name: 'Room Size', type: 'float', defaultValue: 0.4, minValue: 0, maxValue: 1, automatable: true }, { id: 'distance', name: 'Distance', type: 'float', defaultValue: 0.3, minValue: 0, maxValue: 1, automatable: true }, { id: 'reflection', name: 'Reflections', type: 'float', defaultValue: 0.5, minValue: 0, maxValue: 1, automatable: true }], defaultPreset: { size: 0.4, distance: 0.3, reflection: 0.5 } },
  { id: 'mb-mic-isolation', slug: 'mb-mic-isolation', name: 'MB Mic Isolator', category: 'effect', type: 'microphone', version: '1.0.0', description: 'Background noise isolation', author: 'Max Booster', parameters: [{ id: 'threshold', name: 'Threshold', type: 'float', defaultValue: -40, minValue: -80, maxValue: -10, automatable: true }, { id: 'reduction', name: 'Reduction', type: 'float', defaultValue: 20, minValue: 0, maxValue: 60, automatable: true }, { id: 'attack', name: 'Attack', type: 'float', defaultValue: 5, minValue: 0.1, maxValue: 50, automatable: true }], defaultPreset: { threshold: -40, reduction: 20, attack: 5 } },
  { id: 'mb-mic-plosive', slug: 'mb-mic-plosive', name: 'MB Plosive Reducer', category: 'effect', type: 'microphone', version: '1.0.0', description: 'Pops and plosive control', author: 'Max Booster', parameters: [{ id: 'sensitivity', name: 'Sensitivity', type: 'float', defaultValue: 0.5, minValue: 0, maxValue: 1, automatable: true }, { id: 'freq', name: 'Frequency', type: 'float', defaultValue: 120, minValue: 50, maxValue: 300, automatable: true }, { id: 'reduction', name: 'Reduction', type: 'float', defaultValue: 12, minValue: 0, maxValue: 24, automatable: true }], defaultPreset: { sensitivity: 0.5, freq: 120, reduction: 12 } },
  { id: 'mb-mic-channel', slug: 'mb-mic-channel', name: 'MB Channel Strip', category: 'effect', type: 'microphone', version: '1.0.0', description: 'Complete mic channel strip', author: 'Max Booster', parameters: [{ id: 'preampGain', name: 'Preamp', type: 'float', defaultValue: 20, minValue: 0, maxValue: 60, automatable: true }, { id: 'hpf', name: 'HPF', type: 'float', defaultValue: 80, minValue: 20, maxValue: 300, automatable: true }, { id: 'compThresh', name: 'Comp Thresh', type: 'float', defaultValue: -20, minValue: -60, maxValue: 0, automatable: true }, { id: 'eq', name: 'EQ Shape', type: 'float', defaultValue: 0.5, minValue: 0, maxValue: 1, automatable: true }], defaultPreset: { preampGain: 20, hpf: 80, compThresh: -20, eq: 0.5 } },
];
