// @ts-nocheck
/**
 * AI Audio Generator Service - Server-Side Integration
 *
 * Provides REST API endpoints for the in-house AI audio generation system
 */

import wavefilePkg from "wavefile";
const WaveFile =
  (wavefilePkg as Record<string, unknown>).WaveFile || wavefilePkg;
import { randomBytes } from "crypto";

import { AIAudioGenerator, type GenerationType } from "../../shared/ml/audio/AIAudioGenerator.js";
import { logger } from "../logger.js";
import { storageService } from "./storageService.js";
import { MaxCoreAIClient } from "./maxcoreClient.js";
import { requireMaxCore, AIUnavailableError } from "../lib/aiSource.js";
import { getMaxcoreOriginOrDefault } from "./maxcoreConnector.js";
import { getMaxcoreGenerationKey } from "./maxcoreConnector.js";

// Initialize generator
const audioGenerator = new AIAudioGenerator(48000);
let initialized = false;

async function ensureInitialized() {
  if (!initialized) {
    await audioGenerator?.initialize();
    initialized = true;
  }
}

export interface TextToAudioRequest {
  text: string;
  userId?: string;
  duration?: number;
  bars?: number;
  tempo?: number;
  projectId?: string;
  intent?: unknown;
  direction?: unknown;
  context?: unknown;
  awareness?: unknown;
}

export interface AudioToAudioRequest {
  audioBuffer: Buffer;
  userId?: string;
  targetType: GenerationType;
  text?: string;
  bars?: number;
  projectId?: string;
  intent?: unknown;
  direction?: unknown;
  context?: unknown;
  awareness?: unknown;
}

export interface GenerationResult {
  success: boolean;
  audioFilePath: string;
  parameters: {
    type: GenerationType;
    tempo: number;
    key: string;
    scale: string;
    genre: string;
  };
  duration: number;
  sourceType: "text" | "audio";
  generatedNotes?: Array<{
    note: string;
    octave: number;
    time: number;
    duration: number;
    velocity: number;
  }>;
  generatedChords?: Array<{ chord: string; time: number; duration: number }>;
}

/** Persist generated bytes before returning a URL; a MaxCore scratch URL is
 * not durable and this application must never serve a local uploads copy. */
export async function persistMaxCoreAudio(
  source: string | null,
  encoded: string | null,
  deps: { fetchImpl?: typeof fetch; storage?: typeof storageService } = {},
  userId?: string,
): Promise<string> {
  if (source?.startsWith("/api/storage/file/")) {
    const key = decodeURIComponent(source.slice("/api/storage/file/".length));
    if (!userId || !key.startsWith(`users/${userId}/`)) {
      throw new AIUnavailableError("Generated audio ownership mismatch");
    }
    return source; // Already committed by the originating renderer; never re-upload.
  }
  let bytes: Buffer;
  if (encoded) {
    bytes = Buffer.from(encoded, "base64");
  } else if (source) {
    const origin = new URL(getMaxcoreOriginOrDefault());
    const url = new URL(source, origin);
    if (url.origin !== origin.origin || !url.pathname.startsWith("/uploads/")) {
      throw new AIUnavailableError("audio generation returned an untrusted media URL");
    }
    const response = await (deps.fetchImpl ?? fetch)(url, {
      headers: {
        Authorization: `Bearer ${getMaxcoreGenerationKey()}`,
        "X-MaxCore-User-Id": userId || "",
      },
      signal: AbortSignal.timeout(45_000),
    });
    if (!response.ok) throw new AIUnavailableError(`audio download failed (${response.status})`);
    bytes = Buffer.from(await response.arrayBuffer());
  } else {
    throw new AIUnavailableError("audio generation returned no audio");
  }
  if (bytes.length < 128 || bytes.length > 100 * 1024 * 1024) {
    throw new AIUnavailableError("audio generation returned invalid audio size");
  }
  const riff = bytes.toString("ascii", 0, 4) === "RIFF" && bytes.toString("ascii", 8, 12) === "WAVE";
  const mp3 = bytes.toString("ascii", 0, 3) === "ID3" || (bytes[0] === 0xff && (bytes[1] & 0xe0) === 0xe0);
  const ogg = bytes.toString("ascii", 0, 4) === "OggS";
  const flac = bytes.toString("ascii", 0, 4) === "fLaC";
  const m4a = bytes.toString("ascii", 4, 8) === "ftyp";
  if (!riff && !mp3 && !ogg && !flac && !m4a) {
    throw new AIUnavailableError("audio generation returned non-audio content");
  }
  const mime = riff ? "audio/wav" : mp3 ? "audio/mpeg" : ogg ? "audio/ogg" : flac ? "audio/flac" : "audio/mp4";
  const extension = riff ? "wav" : mp3 ? "mp3" : ogg ? "ogg" : flac ? "flac" : "m4a";
  const store = deps.storage ?? storageService;
  if (!userId) throw new AIUnavailableError("audio persistence requires an authenticated owner");
  const key = await store.uploadGeneratedFile(bytes, userId, "generated-audio", `mc_audio_${randomBytes(8).toString("hex")}.${extension}`, mime);
  return store.getDownloadUrl(key);
}

async function saveToWav(
  audioData: Float32Array,
  sampleRate: number,
): Promise<string> {
  const int16Data = new Int16Array(audioData?.length);
  for (let i = 0; i < audioData?.length; i++) {
    int16Data[i] = Math.max(
      -32768,
      Math.min(32767, Math.floor(audioData[i] * 32767)),
    );
  }

  const wav = new WaveFile();
  wav?.fromScratch(1, sampleRate, "16", Array.from(int16Data));

  const filename = `ai_generated_${Date?.now()}_${randomBytes(8).toString("hex")}.wav`;
  const key = `generated-content/audio/${filename}`;
  const buffer = Buffer?.from(wav?.toBuffer());

  await storageService?.uploadFile(buffer, key, "audio/wav");
  return await storageService?.getDownloadUrl(key);
}

export async function generateFromText(
  request: TextToAudioRequest,
): Promise<GenerationResult> {
  logger.info(`[AI Audio] Generating from text: "${request.text}"`);

  // ── MaxCore audio generation (async job pattern) ─────────────────────────
  // MaxCore returns { job_id, status: "processing" } immediately, then
  // the completed job at GET /api/audio-job/{job_id}.
  type AudioJobResponse = {
    job_id?: string;
    url?: string;
    audioUrl?: string;
    audio_url?: string;
    audio_data?: string;
    duration?: number;
    tempo?: number;
    key?: string;
    scale?: string;
    genre?: string;
    status?: string;
  };

  const submitted = requireMaxCore(
    await MaxCoreAIClient.generate<AudioJobResponse>("/api/generate/audio", {
      text: request.text,
      duration: request.duration ?? null,
      bars: request.bars ?? null,
      tempo: request.tempo ?? null,
      project_id: request.projectId ?? null,
      intent: request.intent,
      direction: request.direction,
      context: request.context,
      awareness: request.awareness,
    }),
    "audio generation",
  );

  let mcAudio: AudioJobResponse = submitted;

  // If MaxCore returned a job_id, poll until the job completes.
  if (submitted.job_id && !submitted.url && !submitted.audioUrl && !submitted.audio_url && !submitted.audio_data) {
    const POLL_BUDGET_MS = 600_000; // 10 min — MaxCore has no server-side timeouts
    const POLL_INTERVAL_MS = 5_000;
    const deadline = Date.now() + POLL_BUDGET_MS;
    const jobPath = `/api/audio-job/${submitted.job_id}`;

    logger.info(`[AI Audio] Job submitted: ${submitted.job_id} — polling…`);

    while (Date.now() < deadline) {
      await new Promise((r) => setTimeout(r, POLL_INTERVAL_MS));
      const jr = await MaxCoreAIClient.poll<AudioJobResponse>(jobPath);
      if (!jr) continue;
      if (jr.status === "failed" || jr.status === "error") {
        throw new AIUnavailableError(`audio generation job ${submitted.job_id} failed`);
      }

      const done =
        jr.status === "completed" ||
        jr.status === "done" ||
        jr.status === "succeeded" ||
        !!(jr.url ?? jr.audioUrl ?? jr.audio_url ?? jr.audio_data);

      if (done) {
        mcAudio = jr;
        logger.info(`[AI Audio] Job ${submitted.job_id} completed`);
        break;
      }
    }

    if (!mcAudio.url && !mcAudio.audioUrl && !mcAudio.audio_url && !mcAudio.audio_data) {
      throw new AIUnavailableError(
        `audio generation — job ${submitted.job_id} did not complete within ${Math.round(POLL_BUDGET_MS / 60000)} min`,
      );
    }
  }

  const audioSrc = mcAudio?.audioUrl ?? mcAudio?.audio_url ?? mcAudio?.url ?? null;
  const audioData = mcAudio?.audio_data ?? null;

  if (!(audioSrc || audioData)) {
    throw new Error("MaxCore audio generation returned no audio");
  }

  const audioFilePath = await persistMaxCoreAudio(audioSrc, audioData, {}, request.userId);
  logger.info("[AI Audio] MaxCore audio generated and persisted to PDIM");
  return {
    success: true,
    audioFilePath,
    parameters: {
      type: "music" as GenerationType,
      tempo: mcAudio?.tempo ?? request.tempo ?? 120,
      key: mcAudio?.key ?? "C",
      scale: mcAudio?.scale ?? "major",
      genre: mcAudio?.genre ?? "electronic",
    },
    duration: mcAudio?.duration ?? request.duration ?? 0,
    sourceType: "text",
  };
}


export async function generateFromReference(
  request: AudioToAudioRequest,
): Promise<GenerationResult> {
  logger.info(
    `[AI Audio] Generating ${request?.targetType} from audio reference`,
  );

  // MaxCore is the ONLY audio-generation source — no local synthesis fallback.
  // The requested target style is described to MaxCore; generation is required
  // and fails explicitly when MaxCore is unavailable or returns no audio.
  const submitted = requireMaxCore(
    await MaxCoreAIClient.generate<{
      job_id?: string;
      status?: string;
      url?: string;
      audioUrl?: string;
      audio_url?: string;
      audio_data?: string;
      duration?: number;
      tempo?: number;
      key?: string;
      scale?: string;
      genre?: string;
      notes?: Array<{
        note: string;
        octave: number;
        time: number;
        duration: number;
        velocity: number;
      }>;
      chords?: Array<{ chord: string; time: number; duration: number }>;
    }>("/api/generate/audio", {
      mode: "audio-to-audio",
      target_type: request.targetType,
      text: request.text ?? null,
      bars: request.bars ?? null,
      project_id: request.projectId ?? null,
      intent: request.intent,
      direction: request.direction,
      context: request.context,
      awareness: request.awareness,
      // Style transfer needs the reference audio itself — send it to MaxCore.
      reference_audio: request.audioBuffer.toString("base64"),
      reference_format: "wav",
    }),
    "audio style transfer",
  );

  let mcAudio = submitted;
  if (submitted.job_id && !submitted.url && !submitted.audioUrl && !submitted.audio_url && !submitted.audio_data) {
    const deadline = Date.now() + 600_000;
    while (Date.now() < deadline) {
      await new Promise((resolve) => setTimeout(resolve, 5_000));
      const status = await MaxCoreAIClient.poll<typeof submitted>(`/api/audio-job/${submitted.job_id}`);
      if (!status) continue;
      if (status.status === "failed" || status.status === "error") {
        throw new AIUnavailableError(`audio style transfer job ${submitted.job_id} failed`);
      }
      if (status.audioUrl || status.audio_url || status.audio_data || status.url) {
        mcAudio = status;
        break;
      }
    }
  }
  const audioSrc = mcAudio?.audioUrl ?? mcAudio?.audio_url ?? mcAudio?.url ?? null;
  const audioData = mcAudio?.audio_data ?? null;
  if (!(audioSrc || audioData)) {
    throw new AIUnavailableError("audio style transfer");
  }

  const audioFilePath = await persistMaxCoreAudio(audioSrc, audioData, {}, request.userId);
  logger.info("[AI Audio] MaxCore reference audio persisted to PDIM");
  return {
    success: true,
    audioFilePath,
    parameters: {
      type: request.targetType,
      tempo: mcAudio?.tempo ?? 120,
      key: mcAudio?.key ?? "C",
      scale: mcAudio?.scale ?? "major",
      genre: mcAudio?.genre ?? "electronic",
    },
    duration: mcAudio?.duration ?? 0,
    sourceType: "audio",
    generatedNotes: mcAudio?.notes,
    generatedChords: mcAudio?.chords,
  };
}

export async function generateDrumHit(
  type: "kick" | "snare" | "hihat" | "clap",
  preset?: string,
): Promise<string> {
  await ensureInitialized();

  // Route through MaxCore — the sole AI source for audio generation.
  const mc = requireMaxCore(
    await MaxCoreAIClient.generate<{
      audioUrl?: string;
      audio_url?: string;
      audio_data?: string;
    }>("/api/generate/audio", {
      instrument: "drum",
      drum_type: type,
      preset: preset ?? "default",
      duration: 1,
    }),
    "drum hit generation",
  );

  const audioSrc = mc?.audioUrl ?? mc?.audio_url ?? null;
  const audioData = mc?.audio_data ?? null;

  const outDir = process.cwd() + "/uploads/audio";
  const { mkdirSync } = await import("fs");
  mkdirSync(outDir, { recursive: true });
  const filename = `drum_${randomBytes(6).toString("hex")}.wav`;
  const filePath = `${outDir}/${filename}`;

  if (audioData) {
    const { writeFile } = await import("fs/promises");
    await writeFile(filePath, Buffer.from(audioData, "base64"));
  } else if (audioSrc) {
    const resp = await fetch(audioSrc, { signal: AbortSignal.timeout(45_000) });
    if (!resp.ok) throw new Error(`MaxCore audio download failed: ${resp.status}`);
    const { writeFile } = await import("fs/promises");
    await writeFile(filePath, Buffer.from(await resp.arrayBuffer()));
  } else {
    throw new AIUnavailableError("drum hit generation");
  }

  return `/uploads/audio/${filename}`;
}

export async function generateBassNote(
  note: string,
  octave: number = 1,
  preset: string = "trap808",
  duration: number = 1,
): Promise<string> {
  await ensureInitialized();

  // Route through MaxCore — the sole AI source for audio generation.
  const mc = requireMaxCore(
    await MaxCoreAIClient.generate<{
      audioUrl?: string;
      audio_url?: string;
      audio_data?: string;
    }>("/api/generate/audio", {
      instrument: "bass",
      note,
      octave,
      preset,
      duration,
    }),
    "bass note generation",
  );

  const audioSrc = mc?.audioUrl ?? mc?.audio_url ?? null;
  const audioData = mc?.audio_data ?? null;

  const outDir = process.cwd() + "/uploads/audio";
  const { mkdirSync } = await import("fs");
  mkdirSync(outDir, { recursive: true });
  const filename = `bass_${randomBytes(6).toString("hex")}.wav`;
  const filePath = `${outDir}/${filename}`;

  if (audioData) {
    const { writeFile } = await import("fs/promises");
    await writeFile(filePath, Buffer.from(audioData, "base64"));
  } else if (audioSrc) {
    const resp = await fetch(audioSrc, { signal: AbortSignal.timeout(45_000) });
    if (!resp.ok) throw new Error(`MaxCore audio download failed: ${resp.status}`);
    const { writeFile } = await import("fs/promises");
    await writeFile(filePath, Buffer.from(await resp.arrayBuffer()));
  } else {
    throw new AIUnavailableError("bass note generation");
  }

  return `/uploads/audio/${filename}`;
}

export async function generateSynthNote(
  note: string,
  octave: number = 4,
  type: "lead" | "pad" | "pluck" = "lead",
  preset: string = "classic",
  duration: number = 1,
): Promise<string> {
  await ensureInitialized();

  // Route through MaxCore — the sole AI source for audio generation.
  const mc = requireMaxCore(
    await MaxCoreAIClient.generate<{
      audioUrl?: string;
      audio_url?: string;
      audio_data?: string;
    }>("/api/generate/audio", {
      instrument: "synth",
      synth_type: type,
      note,
      octave,
      preset,
      duration,
    }),
    "synth note generation",
  );

  const audioSrc = mc?.audioUrl ?? mc?.audio_url ?? null;
  const audioData = mc?.audio_data ?? null;

  const outDir = process.cwd() + "/uploads/audio";
  const { mkdirSync } = await import("fs");
  mkdirSync(outDir, { recursive: true });
  const filename = `synth_${randomBytes(6).toString("hex")}.wav`;
  const filePath = `${outDir}/${filename}`;

  if (audioData) {
    const { writeFile } = await import("fs/promises");
    await writeFile(filePath, Buffer.from(audioData, "base64"));
  } else if (audioSrc) {
    const resp = await fetch(audioSrc, { signal: AbortSignal.timeout(45_000) });
    if (!resp.ok) throw new Error(`MaxCore audio download failed: ${resp.status}`);
    const { writeFile } = await import("fs/promises");
    await writeFile(filePath, Buffer.from(await resp.arrayBuffer()));
  } else {
    throw new AIUnavailableError("synth note generation");
  }

  return `/uploads/audio/${filename}`;
}

export async function getSuggestions(text: string): Promise<string[]> {
  await ensureInitialized();
  return audioGenerator?.getSuggestions(text);
}

export const aiAudioGeneratorService = {
  generateFromText,
  generateFromReference,
  generateDrumHit,
  generateBassNote,
  generateSynthNote,
  getSuggestions,
};
